import React,{useEffect,useMemo,useState} from "react";
import {Banknote,BookOpen,ChevronLeft,ClipboardCheck,FileBarChart2,FileSignature,Headphones,HeartHandshake,LayoutDashboard,LogOut,Menu,PanelLeftClose,PanelLeftOpen,Settings,ShieldCheck,UsersRound,WalletCards,X} from "lucide-react";
import "./desktop.css";
import "./desktop-overrides.css";
import "./avatar-finance-v3.css";
import "./support-avatar-v2.css";
import {api,can,ClassicFallback,ErrorState,initials,Loading,ModuleAccess,Notify,roleFa} from "./core";
import {ContractsPage,DashboardPage,UsersPage} from "./modules-admin";
import {PayrollPage} from "./payroll-v2";
import {FinancialCreditsPage} from "./financial-credits-v3";
import {EvaluationsPage} from "./modules-polish";
import {TrainingPage} from "./training-v2";
import {CaregiversPage} from "./caregiver-activity-scorecard";
import {SupportPage} from "./support-v2";
import {ReportsPage,SettingsPage} from "./modules-support";

type Route="dashboard"|"users"|"caregivers"|"contracts"|"payroll"|"financial_credits"|"training"|"evaluations"|"support"|"reports"|"settings"|"unknown";
type RouteMeta={title:string;subtitle:string;key:string;icon:React.ComponentType<any>};
const meta:Record<Exclude<Route,"unknown">,RouteMeta>={dashboard:{title:"داشبورد",subtitle:"مرکز فرمان باشگاه مراقبین",key:"staff.dashboard",icon:LayoutDashboard},users:{title:"کاربران و دسترسی‌ها",subtitle:"حساب‌ها، نقش‌ها و ماتریس Permission",key:"staff.users",icon:UsersRound},caregivers:{title:"پرونده مراقبین",subtitle:"کارنامه فعالیت، رتبه حرفه‌ای، پروانه و رتبه اعتباری",key:"staff.caregivers",icon:HeartHandshake},contracts:{title:"قراردادها",subtitle:"ثبت، ویرایش و سابقه قراردادهای مراقبین",key:"staff.contracts",icon:FileSignature},payroll:{title:"حقوق و پرداخت",subtitle:"صدور فیش، محاسبه و ثبت پرداخت",key:"staff.payroll",icon:Banknote},financial_credits:{title:"اعتبارات مالی",subtitle:"اعتبارشمارها، وام، کیف پول، تسویه و معرفی",key:"staff.financial_credits",icon:WalletCards},training:{title:"بانک آموزش",subtitle:"بانک محتوا، تخصیص و پایش مشاهده",key:"staff.training",icon:BookOpen},evaluations:{title:"ارزیابی و پروانه",subtitle:"دوره‌ها، شاخص‌ها، امتیازدهی و نهایی‌سازی",key:"staff.evaluations",icon:ClipboardCheck},support:{title:"پشتیبانی",subtitle:"صف پرونده، فوری و امنیتی، متن و وویس",key:"staff.support",icon:Headphones},reports:{title:"گزارش‌ها",subtitle:"گزارش عملیاتی زنده و خروجی",key:"staff.reports",icon:FileBarChart2},settings:{title:"تنظیمات و لاگ",subtitle:"تنظیمات عملیاتی و Audit Trail",key:"staff.settings",icon:Settings}};
const aliases:Record<string,Route>={"staff.dashboard":"dashboard","staff.users":"users","staff.caregivers":"caregivers","staff.contracts":"contracts","staff.payroll":"payroll","staff.financial_credits":"financial_credits","staff.financialCredits":"financial_credits","staff.training":"training","staff.evaluations":"evaluations","staff.support":"support","staff.reports":"reports","staff.settings":"settings"};
function routeFromPath():Route{const part=location.pathname.replace(/^\/app\/?/,"").split("/")[0]||"dashboard";return Object.prototype.hasOwnProperty.call(meta,part)?part as Route:"dashboard"}
function pathFor(route:Route){return route==="dashboard"?"/app/":`/app/${route}`}
function keyFor(route:Route){return route==="unknown"?"":meta[route].key}
function moduleRoute(m:ModuleAccess):Route{return aliases[m.key]||"unknown"}
function visibleStaffModules(access:any){const raw=((access?.modules||[]) as ModuleAccess[]).filter(m=>m.panel==="STAFF"&&m.actions?.view),payroll=raw.find(m=>m.key==="staff.payroll");if(payroll&&!raw.some(m=>["staff.financial_credits","staff.financialCredits"].includes(m.key))){const finance:ModuleAccess={key:"staff.financial_credits",label:"اعتبارات مالی مراقبین",description:"کیف پول، تسهیلات، معرفی و تسویه",panel:"STAFF",actions:{...(payroll.actions||{})}};const index=raw.findIndex(m=>m.key==="staff.training");if(index>=0)raw.splice(index,0,finance);else raw.push(finance)}return raw}

function UnknownModule({module}:{module:ModuleAccess}){return <div className="da-stack"><section className="da-card da-state"><strong>{module.label||module.key}</strong><small>این ماژول در Access Control موجود است اما هنوز Route اختصاصی React برای کلید {module.key} تعریف نشده است. مسیر کلاسیک حذف نشده تا منطق موجود از دسترس خارج نشود.</small><ClassicFallback label="بازکردن ماژول در پنل کلاسیک"/></section></div>}

export function DesktopStaffApp(){
 const [auth,setAuth]=useState<any>(null),[access,setAccess]=useState<any>(null),[route,setRoute]=useState<Route>(()=>routeFromPath()),[unknown,setUnknown]=useState<ModuleAccess|null>(null),[error,setError]=useState(""),[collapsed,setCollapsed]=useState(false),[mobileNav,setMobileNav]=useState(false),[notice,setNotice]=useState<{message:string;tone:string}|null>(null);
 const notify:Notify=(message,tone="info")=>{setNotice({message,tone});window.setTimeout(()=>setNotice(null),3400)};
 const load=async()=>{setError("");try{const [a,x]=await Promise.all([api<any>("/api/auth/me"),api<any>("/api/access/me")]);const user=a.data||a.user||a;if(String(user?.role||x.data?.user?.role||"").toUpperCase()==="CAREGIVER"){location.replace("/mobile/");return}setAuth(user);setAccess(x.data||x)}catch(e:any){if(e.status===401){location.replace("/?desktop=1");return}setError(e.message)}};
 useEffect(()=>{void load();const pop=()=>{setUnknown(null);setRoute(routeFromPath())};window.addEventListener("popstate",pop);return()=>window.removeEventListener("popstate",pop)},[]);
 const modules=useMemo(()=>visibleStaffModules(access),[access]);
 const navigateRoute=(next:Route)=>{if(next==="unknown")return;const key=keyFor(next);if(access&&!can(access,key,"view"))return notify("دسترسی این ماژول برای حساب شما فعال نیست.","error");setUnknown(null);history.pushState({desktopRoute:next},"",pathFor(next));setRoute(next);setMobileNav(false);window.scrollTo({top:0,behavior:"auto"})};
 const navigateModule=(m:ModuleAccess)=>{const r=moduleRoute(m);if(r==="unknown"){setUnknown(m);setMobileNav(false);return}navigateRoute(r)};
 const logout=async()=>{try{await api("/api/auth/logout",{method:"POST"})}catch{}location.replace("/?desktop=1")};
 if(error)return <main className="da-boot"><img src="/logo-salamat-aval.svg" alt="سلامت اول"/><ErrorState message={error} retry={load}/></main>;
 if(!access)return <main className="da-boot"><img src="/logo-salamat-aval.svg" alt="سلامت اول"/><Loading label="در حال آماده‌سازی پنل React سازمانی..."/></main>;
 const current=route==="unknown"?null:meta[route],displayRole=access.user?.roleLabel||roleFa[access.user?.role]||roleFa[auth?.role]||"کاربر سازمانی",displayName=access.user?.fullName||auth?.fullName||"کاربر سازمانی";
 return <div className={`da-app ${collapsed?"collapsed":""}`}>
  <aside className={`da-sidebar ${mobileNav?"mobile-open":""}`}><div className="da-side-brand"><img src="/logo-salamat-aval.svg" alt="سلامت اول"/><div><strong>باشگاه مراقبین</strong><small>سلامت اول • React</small></div><button className="da-mobile-close" onClick={()=>setMobileNav(false)}><X size={20}/></button></div><div className="da-side-user"><span>{initials(displayName)}</span><div><strong>{displayName}</strong><small>{displayRole}</small></div></div><nav>{modules.map(m=>{const r=moduleRoute(m),M=r!=="unknown"?meta[r]:null,Icon=M?.icon||ShieldCheck;return <button key={m.key} className={(unknown?.key===m.key||(!unknown&&r===route))?"active":""} onClick={()=>navigateModule(m)} title={m.label}><Icon size={20}/><span><strong>{m.label}</strong><small>{m.description||m.key}</small></span><ChevronLeft size={15}/></button>})}</nav><div className="da-side-footer"><a href="/panel?classic=1">نسخه کلاسیک سازگار</a><button onClick={logout}><LogOut size={18}/><span>خروج از حساب</span></button></div></aside>
  {mobileNav&&<button className="da-mobile-backdrop" aria-label="بستن منو" onClick={()=>setMobileNav(false)}/>}<section className="da-workspace"><header className="da-topbar"><div className="da-top-actions"><button className="da-mobile-menu" onClick={()=>setMobileNav(true)}><Menu size={21}/></button><button className="da-collapse" onClick={()=>setCollapsed(v=>!v)}>{collapsed?<PanelLeftOpen size={20}/>:<PanelLeftClose size={20}/>}</button></div><div className="da-top-title"><strong>{unknown?.label||current?.title||"پنل سازمانی"}</strong><small>{unknown?.description||current?.subtitle||displayRole}</small></div><div className="da-top-user"><div><strong>{displayName}</strong><small>{displayRole}</small></div><span>{initials(displayName)}</span></div></header><main className="da-main">{unknown?<UnknownModule module={unknown}/>:<>{route==="dashboard"&&<DashboardPage access={access} navigate={key=>{const m=modules.find(x=>x.key===key);if(m)navigateModule(m)}}/>}{route==="users"&&<UsersPage access={access} notify={notify}/>} {route==="caregivers"&&<CaregiversPage access={access} notify={notify}/>} {route==="contracts"&&<ContractsPage access={access} notify={notify}/>} {route==="payroll"&&<PayrollPage access={access} notify={notify}/>} {route==="financial_credits"&&<FinancialCreditsPage access={access} notify={notify}/>} {route==="training"&&<TrainingPage access={access} notify={notify}/>} {route==="evaluations"&&<EvaluationsPage access={access} notify={notify}/>} {route==="support"&&<SupportPage user={auth} notify={notify}/>} {route==="reports"&&<ReportsPage access={access} notify={notify}/>} {route==="settings"&&<SettingsPage access={access} notify={notify}/>}</>}</main></section>{notice&&<div className={`da-toast ${notice.tone}`}>{notice.message}</div>}
 </div>
}
