import React,{FormEvent,useEffect,useMemo,useState} from "react";
import {BadgeCheck,CircleDollarSign,Gift,Landmark,Search,UsersRound,WalletCards} from "lucide-react";
import {api,can,Card,dateFa,Empty,fa,initials,Loading,Metric,money,Notify,status,text} from "./core";

type FinanceTab="scorecard"|"loans"|"referrals"|"wallet"|"requests";
const pct=(value:unknown)=>Math.max(0,Math.min(100,Number(value||0)));
const scoreProgress=(item:any)=>{const metric=Number(item?.evaluation?.metric),threshold=Number(item?.scoreThreshold||item?.evaluation?.threshold||0);return Number.isFinite(metric)&&threshold>0?pct(metric/threshold*100):0};
const combined=(item:any)=>Math.min(pct(item?.progressPercent),scoreProgress(item));
const stateLabel:Record<string,string>={ELIGIBLE:"واجد شرایط",IN_PROGRESS:"در حال تکمیل سابقه",PAUSED:"متوقف",NO_CONTRACTS:"بدون قرارداد",WAITING_EVALUATION:"منتظر ارزیابی نهایی",SCORE_BELOW_THRESHOLD:"امتیاز ناکافی",REQUESTED:"ثبت درخواست",UNDER_REVIEW:"در حال بررسی",APPROVED:"تأیید شده",REJECTED:"رد شده",CANCELLED:"لغو شده",PAID:"پرداخت شده",COMPLETED:"معرفی موفق"};

function Gauge({title,percent,center,caption,badge,icon:Icon}:{title:string;percent:number;center:string;caption:string;badge?:string;icon:any}){const p=pct(percent);return <article className="fv3-gauge-card"><div className="fv3-gauge" style={{"--fv3-p":`${p}%`} as React.CSSProperties}><div className="fv3-gauge-center"><Icon size={19}/><strong>{center}</strong><small>{fa(p)}٪</small></div></div><div className="fv3-gauge-copy"><span className="fv3-gauge-icon"><Icon size={17}/></span><h4>{title}</h4><p>{caption}</p>{badge&&<span className="fv3-status">{badge}</span>}</div></article>}

function LoanCards({profile}:{profile:any}){const items=[profile.allowance,...(profile.loans||[])].filter(Boolean);return <div className="fv3-gauge-grid">{items.map((x:any,i:number)=>{const isAllowance=i===0&&x===profile.allowance,progress=isAllowance?Math.min(pct(x.progressPercent),scoreProgress(x)):combined(x);return <Gauge key={x.key||x.id||i} icon={isAllowance?Gift:Landmark} title={x.title||(isAllowance?"کمک‌هزینه ماندگاری":"وام مراقبین")} percent={progress} center={`${fa(progress)}٪`} caption={`${x.targetMonths?`${fa(x.targetMonths)} ماه ${x.serviceMode==="CUMULATIVE"?"تجمیعی":"ممتد"} • `:""}امتیاز مؤثر ${x.evaluation?.metric==null?"—":fa(x.evaluation.metric)}`} badge={stateLabel[String(x.status)]||status(x.status)}/>} )}</div>}

function CreditProfile({profile,access,reload,notify}:{profile:any;access:any;reload:()=>void;notify:Notify}){
 const [tab,setTab]=useState<FinanceTab>("scorecard");const c=profile.caregiver||{},w=profile.wallet||{},ws=w.summary||{},r=profile.referrals||{},rs=r.summary||{},loans=profile.loans||[],credit=profile.service?.credit||{};
 const bestLoan=useMemo(()=>[...loans].sort((a:any,b:any)=>Number(b.amountToman||0)-Number(a.amountToman||0)).find((x:any)=>x.eligible)||[...loans].sort((a:any,b:any)=>Number(b.progressPercent||0)-Number(a.progressPercent||0))[0]||{},[loans]);
 const loanPercent=combined(bestLoan),creditPercent=Math.max(pct(credit.progressPercent),loanPercent),refPercent=pct(Number(rs.progressInCycle||0)/Math.max(1,Number(rs.milestoneSize||10))*100);
 const adjust=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());body.caregiverId=c.id;body.amountToman=String(body.amountToman||"").replace(/\D/g,"");try{await api("/api/staff/financial-credits/wallet-adjustments",{method:"POST",body:JSON.stringify(body)});notify("تراکنش کیف پول ثبت شد.","success");reload()}catch(x:any){notify(x.message,"error")}};
 const settle=async(id:string,decision:string)=>{const reason=prompt("دلیل تصمیم:","")||"";if(reason.trim().length<3)return;const body:any={decision,reason};if(decision==="PAID"){const tracking=prompt("شماره پیگیری پرداخت:","")||"";if(!tracking)return;body.paymentTrackingNumber=tracking}try{await api(`/api/staff/financial-credits/settlements/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify(body)});notify("تصمیم تسویه ثبت شد.","success");reload()}catch(x:any){notify(x.message,"error")}};
 const creditDecision=async(id:string,decision:string)=>{const reason=prompt("دلیل تصمیم:","")||"";if(reason.trim().length<3)return;try{await api(`/api/staff/financial-credits/credit-requests/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({decision,reason})});notify("تصمیم اعتبار ثبت شد.","success");reload()}catch(x:any){notify(x.message,"error")}};
 return <div className="da-stack fv3-profile"><Card className="fv3-profile-head"><div className="fv3-person"><span>{initials(c.fullName)}</span><div><strong>{text(c.fullName,"مراقب")}</strong><small>{text(c.membershipCode)} • {text(c.mobile)} • کد معرفی {text(c.referralCode)}</small></div></div><span className="da-pill">{status(c.cooperationStatus)}</span></Card>
 <section className="da-metrics"><Metric label="مانده خالص" value={money(ws.netToman||0)}/><Metric label="قابل تسویه" value={money(ws.availableToman||0)}/><Metric label="تسویه در جریان" value={money(ws.pendingSettlementToman||0)}/><Metric label="افراد معرفی‌شده" value={fa(rs.totalReferrals||0)}/><Metric label="معرفی موفق" value={fa(rs.completedReferrals||0)}/></section>
 <Card className="fv3-tabs-card"><nav className="fv3-tabs"><button className={tab==="scorecard"?"active":""} onClick={()=>setTab("scorecard")}><CircleDollarSign size={17}/>اعتبارشمارها</button><button className={tab==="loans"?"active":""} onClick={()=>setTab("loans")}><Landmark size={17}/>وام و تسهیلات</button><button className={tab==="referrals"?"active":""} onClick={()=>setTab("referrals")}><UsersRound size={17}/>معرفی‌ها ({fa(rs.totalReferrals||0)})</button><button className={tab==="wallet"?"active":""} onClick={()=>setTab("wallet")}><WalletCards size={17}/>کیف پول</button><button className={tab==="requests"?"active":""} onClick={()=>setTab("requests")}><BadgeCheck size={17}/>درخواست‌ها</button></nav>
 {tab==="scorecard"&&<div className="fv3-panel"><div className="fv3-gauge-grid fv3-gauge-grid-primary"><Gauge icon={Landmark} title="وضعیت وام" percent={loanPercent} center={bestLoan?.eligible?money(bestLoan.amountToman||0):`${fa(loanPercent)}٪`} caption={bestLoan?.title?`${bestLoan.title} • ${stateLabel[String(bestLoan.status)]||status(bestLoan.status)}`:"هنوز سابقه کافی برای سطح وام ثبت نشده است."} badge={bestLoan?.status?stateLabel[String(bestLoan.status)]||status(bestLoan.status):"در حال ساخت سابقه"}/><Gauge icon={CircleDollarSign} title="اعتبار مراقب" percent={creditPercent} center={credit.eligible?"واجد":"در مسیر"} caption={`پیشرفت اعتباری بر پایه سابقه همکاری و ارزیابی FINAL • امتیاز ${profile.evaluation?.latestScore==null?"—":fa(profile.evaluation.latestScore)}`} badge={stateLabel[String(credit.status)]||status(credit.status||bestLoan.status)}/><Gauge icon={UsersRound} title="چرخه معرفی" percent={refPercent} center={`${fa(rs.progressInCycle||0)}/${fa(rs.milestoneSize||10)}`} caption={`${fa(rs.remainingToMilestone||rs.milestoneSize||10)} معرفی قراردادی تا پاداش بعدی`} badge={`${fa(rs.completedReferrals||0)} معرفی موفق`}/></div><LoanCards profile={profile}/></div>}
 {tab==="loans"&&<div className="fv3-panel"><LoanCards profile={profile}/><div className="da-benefit-grid">{[profile.allowance,...loans].filter(Boolean).map((x:any,i:number)=><article key={x.key||i}><strong>{text(x.title,i===0?"کمک‌هزینه ماندگاری":"وام")}</strong><span>مبلغ: {money(x.amountToman||0)}</span><span>سابقه: {fa(x.progressPercent||0)}٪</span><span>حد امتیاز: {fa(x.scoreThreshold||x.evaluation?.threshold||0)}</span><span>وضعیت: {stateLabel[String(x.status)]||status(x.status)}</span></article>)}</div></div>}
 {tab==="referrals"&&<div className="fv3-panel"><div className="fv3-gauge-grid"><Gauge icon={UsersRound} title="پیشرفت پاداش معرفی" percent={refPercent} center={`${fa(rs.progressInCycle||0)}/${fa(rs.milestoneSize||10)}`} caption={`پاداش بعدی: ${money(rs.nextMilestoneRewardToman||0)} • هدف ${fa(rs.nextMilestoneTarget||rs.milestoneSize||10)} معرفی موفق`} badge={`${fa(rs.totalReferrals||0)} معرفی ثبت‌شده`}/></div><div className="da-table-wrap"><table className="da-table"><thead><tr><th>مراقب معرفی‌شده</th><th>وضعیت</th><th>پاداش ثبت‌نام</th><th>پاداش قرارداد</th><th>تاریخ</th></tr></thead><tbody>{(r.cases||[]).map((x:any)=><tr key={x.id}><td><div className="da-person-cell"><span>{initials(x.referredName)}</span><div><strong>{text(x.referredName,"مراقب")}</strong><small>{text(x.referredMembershipCode)}</small></div></div></td><td>{stateLabel[String(x.status)]||status(x.status)}</td><td>{x.registrationRewardTransactionId?money(x.registrationRewardToman):"—"}</td><td>{x.contractRewardTransactionId?money(x.contractRewardToman):"—"}</td><td>{dateFa(x.createdAt)}</td></tr>)}</tbody></table></div></div>}
 {tab==="wallet"&&<div className="fv3-panel">{can(access,"staff.financial_credits","update")&&<form className="da-inline-form fv3-wallet-form" onSubmit={adjust}><select name="kind"><option value="TOPUP">بستانکار</option><option value="DEBIT">بدهکار / برداشت</option></select><input name="amountToman" placeholder="مبلغ تومان" required/><input name="title" placeholder="عنوان"/><input name="reason" placeholder="دلیل" required/><button className="da-btn primary">ثبت تراکنش</button></form>}<div className="da-table-wrap"><table className="da-table"><thead><tr><th>شرح</th><th>جهت</th><th>مبلغ</th><th>تاریخ</th></tr></thead><tbody>{(w.transactions||[]).map((x:any)=><tr key={x.id}><td><strong>{text(x.title)}</strong><small>{text(x.description,"")}</small></td><td>{x.direction==="CREDIT"?"بستانکار":"بدهکار"}</td><td>{money(x.amountToman)}</td><td>{dateFa(x.createdAt)}</td></tr>)}</tbody></table></div></div>}
 {tab==="requests"&&<div className="fv3-panel fv3-requests"><Card><div className="da-card-head"><h3>درخواست‌های تسویه</h3></div><div className="da-table-wrap"><table className="da-table"><thead><tr><th>مبلغ</th><th>وضعیت</th><th>تاریخ</th><th>اقدام</th></tr></thead><tbody>{(w.settlements||[]).map((x:any)=><tr key={x.id}><td>{money(x.amountToman)}</td><td>{stateLabel[String(x.status)]||status(x.status)}</td><td>{dateFa(x.createdAt)}</td><td><div className="da-actions compact">{x.status==="REQUESTED"&&<><button className="da-btn soft" onClick={()=>void settle(x.id,"APPROVED")}>تأیید</button><button className="da-btn danger" onClick={()=>void settle(x.id,"REJECTED")}>رد</button></>}{x.status==="APPROVED"&&<button className="da-btn primary" onClick={()=>void settle(x.id,"PAID")}>ثبت پرداخت</button>}</div></td></tr>)}</tbody></table></div></Card><Card><div className="da-card-head"><h3>درخواست‌های وام و کمک‌هزینه</h3></div><div className="da-table-wrap"><table className="da-table"><thead><tr><th>نوع</th><th>مبلغ</th><th>وضعیت</th><th>اقدام</th></tr></thead><tbody>{(w.creditRequests||[]).map((x:any)=><tr key={x.id}><td>{text(x.eligibilitySnapshot?.benefitTitle||x.eligibilityPath,"تسهیلات")}</td><td>{money(x.requestedAmountToman)}</td><td>{stateLabel[String(x.status)]||status(x.status)}</td><td>{["REQUESTED","UNDER_REVIEW"].includes(x.status)&&<div className="da-actions compact">{x.status==="REQUESTED"&&<button className="da-btn soft" onClick={()=>void creditDecision(x.id,"UNDER_REVIEW")}>بررسی</button>}<button className="da-btn primary" onClick={()=>void creditDecision(x.id,"APPROVED")}>تأیید</button><button className="da-btn danger" onClick={()=>void creditDecision(x.id,"REJECTED")}>رد</button></div>}</td></tr>)}</tbody></table></div></Card></div>}
 </Card></div>}

export function FinancialCreditsPage({access,notify}:{access:any;notify:Notify}){const [rows,setRows]=useState<any[]>([]),[query,setQuery]=useState(""),[profile,setProfile]=useState<any>(null),[selectedId,setSelectedId]=useState(""),[loading,setLoading]=useState(false);const load=async()=>{setLoading(true);try{const p:any=await api(`/api/staff/financial-credits/caregivers?q=${encodeURIComponent(query)}&page=1&pageSize=50`);setRows(p.data?.caregivers||[])}catch(e:any){notify(e.message,"error")}finally{setLoading(false)}};useEffect(()=>{void load()},[]);const open=async(id:string)=>{setSelectedId(id);setProfile(null);try{const p:any=await api(`/api/staff/financial-credits/caregivers/${encodeURIComponent(id)}/profile`);setProfile(p.data||{})}catch(e:any){notify(e.message,"error")}};return <div className="da-stack"><Card><form className="da-toolbar" onSubmit={e=>{e.preventDefault();void load()}}><div className="da-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام، کد، موبایل یا کد ملی"/></div><button className="da-btn soft">جست‌وجو</button></form></Card><div className="da-master-detail"><Card>{loading?<Loading/>:<div className="da-mini-list">{rows.map(c=><button key={c.id} className={selectedId===c.id?"active":""} onClick={()=>void open(c.id)}><span>{initials(c.fullName)}</span><div><strong>{text(c.fullName,"مراقب")}</strong><small>{text(c.membershipCode)} • مانده {money(c.wallet?.balanceToman||0)}</small></div><em>{status(c.latestCreditStatus||c.fileStatus)}</em></button>)}</div>}</Card><div>{profile?<CreditProfile profile={profile} access={access} notify={notify} reload={()=>void open(selectedId)}/>:<Empty title="مراقب را انتخاب کنید" description="اعتبارشمارهای وام، اعتبار، معرفی و کارنامه مالی در تب‌های مجزا نمایش داده می‌شوند."/>}</div></div></div>}
