import React,{FormEvent,useEffect,useState} from "react";
import {Gift,RefreshCw,Search} from "lucide-react";
import {api,Card,dateFa,Empty,fa,money,Notify,text} from "./core";
import "./referral-rewards-admin-v1.css";

type Props={access:any;notify:Notify};
const stateLabel=(x:any)=>{const c=String(x.referrerConfirmationStatus||"").toUpperCase(),s=String(x.status||"").toUpperCase();if(c==="PENDING")return"در انتظار تأیید معرف";if(c==="REJECTED")return"ردشده توسط معرف";if(s==="WAITING_CONTRACT")return"مرحله اول ثبت شد؛ منتظر قرارداد";if(s==="COMPLETED")return"پاداش کامل ثبت شد";return s||"—"};
export function ReferralRewardsAdmin(_props:Props){
 const [data,setData]=useState<any>(null),[query,setQuery]=useState(""),[filter,setFilter]=useState(""),[error,setError]=useState("");
 const load=async()=>{setError("");try{const p:any=await api(`/api/staff/financial-credits/referrals?q=${encodeURIComponent(query)}&status=${encodeURIComponent(filter)}`);setData(p.data||{})}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 if(error)return <Card><div className="rr-state"><strong>دریافت سوابق معرفی انجام نشد</strong><small>{error}</small><button className="da-btn soft" onClick={()=>void load()}><RefreshCw size={16}/>تلاش مجدد</button></div></Card>;
 if(!data)return <Card><div className="rr-state">در حال دریافت سوابق معرفی...</div></Card>;
 const s=data.summary||{},rows=data.cases||[];
 return <div className="da-stack rr-admin"><section className="da-metrics"><article className="da-metric"><small>منتظر تأیید معرف</small><strong>{fa(s.awaitingReferrer||0)}</strong></article><article className="da-metric"><small>منتظر اولین قرارداد</small><strong>{fa(s.waitingContract||0)}</strong></article><article className="da-metric"><small>پاداش مرحله ثبت‌نام</small><strong>{money(s.stage1AmountToman||0)}</strong></article><article className="da-metric"><small>پاداش مرحله قرارداد</small><strong>{money(s.stage2AmountToman||0)}</strong></article></section><Card><form className="rr-filter" onSubmit={(e:FormEvent)=>{e.preventDefault();void load()}}><div className="da-search"><Search size={18}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="معرف یا مراقب معرفی‌شده"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">همه وضعیت‌ها</option><option value="PENDING_REGISTRATION_REVIEW">در انتظار تأیید معرف</option><option value="WAITING_CONTRACT">منتظر اولین قرارداد</option><option value="COMPLETED">تکمیل‌شده</option></select><button className="da-btn soft">اعمال</button></form></Card><Card><div className="da-card-head"><div><h3>پاداش معرفی</h3><p>این تب سابقه تأیید معرف، مرحله ثبت‌نام، اولین قرارداد و تراکنش‌های مرتبط را برای مدیرسامانه نمایش می‌دهد.</p></div><Gift size={20}/></div>{rows.length?<div className="da-table-wrap"><table className="da-table rr-table"><thead><tr><th>معرف</th><th>معرفی‌شده</th><th>تأیید معرف</th><th>حساب</th><th>مرحله ثبت‌نام</th><th>مرحله قرارداد</th><th>وضعیت</th></tr></thead><tbody>{rows.map((x:any)=><tr key={x.id}><td><strong>{text(x.referrerName)}</strong><small>{text(x.referrerMembershipCode)} • {text(x.referrerMobile)}</small></td><td><strong>{text(x.referredName)}</strong><small>{text(x.referredMembershipCode)} • {text(x.referredMobile)}</small></td><td>{String(x.referrerConfirmationStatus).toUpperCase()==="APPROVED"?"تأیید شده":String(x.referrerConfirmationStatus).toUpperCase()==="PENDING"?"در انتظار":"رد شده"}</td><td>{text(x.referredAccountStatus)}</td><td>{x.registrationRewardTransactionId?<><strong>{money(x.registrationRewardToman)}</strong><small>{dateFa(x.registrationPaymentAt)}</small></>:"ثبت نشده"}</td><td>{x.contractRewardTransactionId?<><strong>{money(x.contractRewardToman)}</strong><small>{dateFa(x.contractPaymentAt)}</small></>:x.contractEligible?"در حال ثبت خودکار":"هنوز قرارداد نشده"}</td><td><span className="da-pill">{stateLabel(x)}</span></td></tr>)}</tbody></table></div>:<Empty title="پرونده معرفی وجود ندارد" description="معرفی‌های ثبت‌شده با کد معرف در این فهرست نمایش داده می‌شوند."/>}</Card></div>
}
