import React,{FormEvent,useEffect,useRef,useState} from "react";
import {Mic,RefreshCw,Send,Square} from "lucide-react";
import {api,Card,dateFa,Empty,ErrorState,fa,initials,Loading,Notify,status,text,uploadFile} from "./core";

export function SupportPage({user,notify}:{user:any;notify:Notify}){
 const [threads,setThreads]=useState<any[]>([]),[active,setActive]=useState(""),[messages,setMessages]=useState<any[]>([]),[filter,setFilter]=useState("ALL"),[loading,setLoading]=useState(true),[error,setError]=useState(""),[recording,setRecording]=useState(false);const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]);
 const load=async(keep=true)=>{setLoading(true);setError("");try{const p:any=await api("/api/caregiver/platform/support/threads"),rows=p.data?.threads||[];setThreads(rows);const id=keep&&active&&rows.some((x:any)=>x.id===active)?active:rows[0]?.id||"";setActive(id);if(id){const m:any=await api(`/api/caregiver/platform/support/threads/${encodeURIComponent(id)}/messages`);setMessages(m.data?.messages||[])}else setMessages([])}catch(e:any){setError(e.message)}finally{setLoading(false)}};useEffect(()=>{void load(false)},[]);
 const open=async(id:string)=>{setActive(id);try{const p:any=await api(`/api/caregiver/platform/support/threads/${encodeURIComponent(id)}/messages`);setMessages(p.data?.messages||[])}catch(e:any){notify(e.message,"error")}};
 const send=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const input=e.currentTarget.elements.namedItem("text") as HTMLInputElement,textValue=input.value.trim();if(!textValue||!active)return;try{await api(`/api/caregiver/platform/support/threads/${encodeURIComponent(active)}/messages`,{method:"POST",body:JSON.stringify({text:textValue})});input.value="";await open(active)}catch(x:any){notify(x.message,"error")}};
 const changeStatus=async(next:string)=>{if(!active)return;try{await api(`/api/caregiver/platform/support/threads/${encodeURIComponent(active)}`,{method:"PATCH",body:JSON.stringify({status:next})});notify("وضعیت گفت‌وگو تغییر کرد.","success");await load(true)}catch(x:any){notify(x.message,"error")}};
 const toggleVoice=async()=>{const thread=threads.find(x=>x.id===active);if(!thread)return;if(recording&&recorder.current){recorder.current.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return notify("ضبط صدا در این مرورگر در دسترس نیست.","error");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];const type=MediaRecorder.isTypeSupported("audio/webm;codecs=opus")?"audio/webm;codecs=opus":"audio/webm",r=new MediaRecorder(stream,{mimeType:type});recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{setRecording(false);stream.getTracks().forEach(t=>t.stop());try{const blob=new Blob(chunks.current,{type:r.mimeType||"audio/webm"}),file=new File([blob],`staff-support-${Date.now()}.webm`,{type:blob.type}),stored:any=await uploadFile(file,"support",thread.caregiverId);await api(`/api/caregiver/platform/support/threads/${encodeURIComponent(active)}/messages`,{method:"POST",body:JSON.stringify({storedFileId:stored.id})});notify("پیام صوتی ارسال شد.","success");await open(active)}catch(x:any){notify(x.message,"error")}};r.start();setRecording(true)}catch(e:any){notify(e.message||"دسترسی میکروفون داده نشد.","error")}};
 if(error)return <ErrorState message={error} retry={()=>load(false)}/>;if(loading)return <Loading label="در حال دریافت صف پشتیبانی..."/>;const visible=threads.filter(x=>filter==="ALL"||x.category===filter),thread=threads.find(x=>x.id===active),urgent=threads.filter(x=>x.category==="URGENT_SECURITY"&&["OPEN","PENDING"].includes(x.status)).length;
 return <div className="da-stack"><Card><div className="da-toolbar"><div className="da-tabs"><button className={filter==="ALL"?"active":""} onClick={()=>setFilter("ALL")}>همه</button><button className={filter==="CASE"?"active":""} onClick={()=>setFilter("CASE")}>پرونده</button><button className={filter==="URGENT_SECURITY"?"active":""} onClick={()=>setFilter("URGENT_SECURITY")}>فوری و امنیتی ({fa(urgent)})</button></div><button className="da-btn soft" onClick={()=>void load(true)}><RefreshCw size={16}/>به‌روزرسانی</button></div></Card><div className="da-support-layout"><Card><div className="da-thread-list">{visible.map(t=><button key={t.id} className={`${t.id===active?"active":""} ${t.category==="URGENT_SECURITY"?"urgent":""}`} onClick={()=>void open(t.id)}><div className="sv2-thread-person"><span>{initials(t.caregiverName||t.subject)}</span><div><strong>{text(t.caregiverName||t.subject)}</strong><small>{text(t.membershipCode)} • {status(t.status)}</small></div><em>{t.category==="URGENT_SECURITY"?"فوری":"پرونده"}</em></div><p>{text(t.subject)}</p><small>{dateFa(t.updatedAt)}</small></button>)}</div></Card>{thread?<Card className="da-chat"><div className="da-chat-head"><div className="sv2-chat-person"><span>{initials(thread.caregiverName)}</span><div><h3>{thread.caregiverName} • {thread.subject}</h3><p>{thread.category==="URGENT_SECURITY"?"پشتیبانی فوری و امنیتی":"پشتیبانی پرونده"} • {text(thread.familyName||thread.contractNumber,"بدون قرارداد")}</p></div></div><select value={thread.status} onChange={e=>void changeStatus(e.target.value)}><option value="OPEN">باز</option><option value="PENDING">در انتظار</option><option value="RESOLVED">حل‌شده</option><option value="CLOSED">بسته</option></select></div><div className="da-messages">{messages.length?messages.map(m=><div key={m.id} className={`da-message ${m.senderUserId===user?.id?"mine":""}`}>{m.messageType==="VOICE"&&m.storedFileId?<audio controls preload="none" src={`/api/files/${encodeURIComponent(m.storedFileId)}/download`}/>:<p>{text(m.textContent)}</p>}<small>{text(m.senderName,"کاربر")} • {dateFa(m.createdAt)}</small></div>):<Empty title="هنوز پیامی نیست" description="پاسخ متنی یا صوتی خود را ارسال کنید."/>}</div><form className="da-compose" onSubmit={send}><button type="button" className={recording?"recording":""} onClick={()=>void toggleVoice()}>{recording?<Square size={18}/>:<Mic size={18}/>}</button><input name="text" placeholder="پاسخ خود را بنویسید..."/><button className="send"><Send size={18}/></button></form></Card>:<Empty title="گفت‌وگویی انتخاب نشده" description="از صف سمت راست یک گفت‌وگو را انتخاب کنید."/>}</div></div>
}
