import React,{useEffect,useRef,useState} from "react";
import {TrainingPage as TrainingPageV2} from "./training-v2";
import {Notify} from "./core";

const PRESERVE_CONTENT_SENTINEL="__SALAMAT_PRESERVE_CONTENT__";
const TRAINING_FILE_ACCEPT=".pdf,.doc,.docx,.xls,.xlsx,.txt,.rtf,.md,.srt,.vtt,.jpg,.jpeg,.png,.webp,.mp4,.webm,.mp3,.m4a";
function normalizedUrl(value:unknown){const raw=String(value||"").trim();return /^www\./i.test(raw)?`https://${raw}`:raw}
function isCreateTrainingForm(form:HTMLFormElement){return Array.from(form.querySelectorAll("button")).some(button=>/ثبت در بانک آموزش|ثبت آموزش/.test(String(button.textContent||"")))}
function isEditTrainingForm(form:HTMLFormElement){return Array.from(form.querySelectorAll("button")).some(button=>/ذخیره تغییرات/.test(String(button.textContent||"")))}
function relaxEditForm(form:HTMLFormElement){if(!isEditTrainingForm(form))return;form.querySelectorAll<HTMLElement>("[required]").forEach(node=>node.removeAttribute("required"));}

export function TrainingPage({access,notify}:{access:any;notify:Notify}){
 const shell=useRef<HTMLDivElement>(null),[courses,setCourses]=useState<any[]>([]);const coursesRef=useRef<any[]>([]);coursesRef.current=courses;
 const loadCourses=async()=>{try{const r=await fetch("/api/training/admin",{credentials:"same-origin",cache:"no-store"});if(!r.ok)return;const p:any=await r.json();setCourses(Array.isArray(p?.data?.courses)?p.data.courses:[])}catch{}};
 useEffect(()=>{void loadCourses()},[]);
 useEffect(()=>{const root=shell.current;if(!root)return;const submitCapture=(event:Event)=>{const form=event.target instanceof HTMLFormElement?event.target:null;if(!form||!isEditTrainingForm(form))return;relaxEditForm(form);const content=form.querySelector<HTMLInputElement>('[name="contentUrl"]');const file=form.querySelector<HTMLInputElement>('input[name="file"]')?.files?.[0];if(content&&!content.value.trim()&&!file){content.value=PRESERVE_CONTENT_SENTINEL;queueMicrotask(()=>{if(content.value===PRESERVE_CONTENT_SENTINEL)content.value=""})}};root.addEventListener("submit",submitCapture,true);return()=>root.removeEventListener("submit",submitCapture,true)},[]);
 useEffect(()=>{const nativeFetch=window.fetch.bind(window);const patched:typeof window.fetch=async(input,init)=>{const raw=typeof input==="string"?input:input instanceof URL?input.toString():input.url,url=new URL(raw,location.origin),method=String(init?.method||(input instanceof Request?input.method:"GET")).toUpperCase();if(url.origin===location.origin&&(url.pathname==="/api/training/courses"&&method==="POST"||/^\/api\/training\/courses\/[^/]+$/.test(url.pathname)&&method==="PATCH")&&typeof init?.body==="string"){try{const body=JSON.parse(init.body);if(body.contentUrl===PRESERVE_CONTENT_SENTINEL)delete body.contentUrl;if(!Object.prototype.hasOwnProperty.call(body,"examUrl")){const inputNode=shell.current?.querySelector<HTMLInputElement>('input[data-training-exam-url="1"]');body.examUrl=String(inputNode?.value||"").trim()}init={...init,body:JSON.stringify(body)}}catch{}}const response=await nativeFetch(input as RequestInfo|URL,init);if(response.ok&&url.origin===location.origin&&((url.pathname==="/api/training/courses"&&method==="POST")||(/^\/api\/training\/courses\/[^/]+$/.test(url.pathname)&&["PATCH","DELETE"].includes(method))))setTimeout(()=>void loadCourses(),80);return response};window.fetch=patched;return()=>{if(window.fetch===patched)window.fetch=nativeFetch as typeof window.fetch}},[]);
 useEffect(()=>{const root=shell.current;if(!root)return;const decorate=()=>{const current=coursesRef.current;root.querySelectorAll<HTMLFormElement>("form.da-form").forEach(form=>{
  const createForm=isCreateTrainingForm(form),editForm=isEditTrainingForm(form);if(!createForm&&!editForm)return;if(editForm)relaxEditForm(form);
  const content=form.querySelector<HTMLInputElement>('[name="contentUrl"]');
  if(content&&!form.querySelector('[data-training-file-field="1"]')){const label=document.createElement("label");label.className="wide";label.dataset.trainingFileField="1";const span=document.createElement("span");span.textContent="فایل آموزش (اختیاری)";const input=document.createElement("input");input.type="file";input.name="file";input.accept=TRAINING_FILE_ACCEPT;const note=document.createElement("small");note.textContent="PDF، Word، تصویر، صوت یا ویدئو؛ حداکثر ۱۰۰ مگابایت. در صورت انتخاب فایل، فایل در فضای ذخیره‌سازی آموزش بارگذاری می‌شود.";note.style.cssText="display:block;margin-top:6px;color:#60776d;font-size:11px";label.append(span,input,note);content.closest("label")?.parentElement?.insertBefore(label,content.closest("label"))}
  if(!content||form.querySelector('[data-training-exam-field="1"]'))return;
  const title=String(form.querySelector<HTMLInputElement>('[name="title"]')?.value||"").trim(),contentValue=String(content.value||"").trim();const course=current.find(x=>String(x.contentUrl||"").trim()===contentValue&&contentValue)||current.find(x=>String(x.title||"").trim()===title&&title);const label=document.createElement("label");label.className="wide";label.dataset.trainingExamField="1";const span=document.createElement("span");span.textContent="لینک آزمون (اختیاری)";const input=document.createElement("input");input.type="url";input.required=false;input.placeholder="https://...";input.value=normalizedUrl(course?.examUrl);input.dataset.trainingExamUrl="1";label.append(span,input);const description=Array.from(form.querySelectorAll("label")).find(x=>x.querySelector("textarea[name='description']"));description?.parentElement?.insertBefore(label,description);if(!description)form.querySelector(".da-form-grid")?.appendChild(label);if(editForm)relaxEditForm(form)
 });root.querySelectorAll<HTMLTableRowElement>("table.da-table tbody tr").forEach(row=>{const cell=row.querySelector("td:first-child"),title=String(cell?.querySelector("strong")?.textContent||"").trim();if(!cell||!title||cell.querySelector(".tev-exam-row"))return;const course=current.find(x=>String(x.title||"").trim()===title),line=document.createElement("small");line.className="tev-exam-row";if(course?.examUrl){const a=document.createElement("a");a.href=normalizedUrl(course.examUrl);a.target="_blank";a.rel="noopener noreferrer";a.textContent="لینک آزمون";a.style.cssText="color:#087443;font-weight:900;text-decoration:none";line.appendChild(a)}else{line.textContent="آزمون: ثبت نشده";line.style.color="#9a6a18"}cell.appendChild(line)})};decorate();const observer=new MutationObserver(decorate);observer.observe(root,{childList:true,subtree:true});return()=>observer.disconnect()},[courses]);
 return <div ref={shell}><style>{`[data-training-exam-field="1"] input{direction:ltr}[data-training-file-field="1"] input{direction:rtl;padding:9px;background:#fff}.tev-exam-row{margin-top:5px}`}</style><TrainingPageV2 access={access} notify={notify}/></div>;
}
