import React,{useEffect,useRef,useState} from "react";
import {TrainingPage as TrainingPageV2} from "./training-v2";
import {Notify} from "./core";

function normalizedUrl(value:unknown){const raw=String(value||"").trim();return /^www\./i.test(raw)?`https://${raw}`:raw}
export function TrainingPage({access,notify}:{access:any;notify:Notify}){
 const shell=useRef<HTMLDivElement>(null),[courses,setCourses]=useState<any[]>([]);const coursesRef=useRef<any[]>([]);coursesRef.current=courses;
 const loadCourses=async()=>{try{const r=await fetch("/api/training/admin",{credentials:"same-origin",cache:"no-store"});if(!r.ok)return;const p:any=await r.json();setCourses(Array.isArray(p?.data?.courses)?p.data.courses:[])}catch{}};
 useEffect(()=>{void loadCourses()},[]);
 useEffect(()=>{const nativeFetch=window.fetch.bind(window);const patched:typeof window.fetch=async(input,init)=>{const raw=typeof input==="string"?input:input instanceof URL?input.toString():input.url,url=new URL(raw,location.origin),method=String(init?.method||(input instanceof Request?input.method:"GET")).toUpperCase();if(url.origin===location.origin&&(url.pathname==="/api/training/courses"&&method==="POST"||/^\/api\/training\/courses\/[^/]+$/.test(url.pathname)&&method==="PATCH")&&typeof init?.body==="string"){try{const body=JSON.parse(init.body);if(!Object.prototype.hasOwnProperty.call(body,"examUrl")){const inputNode=shell.current?.querySelector<HTMLInputElement>('input[data-training-exam-url="1"]');body.examUrl=String(inputNode?.value||"").trim();init={...init,body:JSON.stringify(body)}}}catch{}}const response=await nativeFetch(input as RequestInfo|URL,init);if(response.ok&&url.origin===location.origin&&((url.pathname==="/api/training/courses"&&method==="POST")||(/^\/api\/training\/courses\/[^/]+$/.test(url.pathname)&&["PATCH","DELETE"].includes(method))))setTimeout(()=>void loadCourses(),80);return response};window.fetch=patched;return()=>{if(window.fetch===patched)window.fetch=nativeFetch as typeof window.fetch}},[]);
 useEffect(()=>{const root=shell.current;if(!root)return;const decorate=()=>{const current=coursesRef.current;root.querySelectorAll<HTMLFormElement>("form.da-form").forEach(form=>{if(!form.querySelector('[name="categoryGroup"]')||!form.querySelector('[name="contentUrl"]')||form.querySelector('[data-training-exam-field="1"]'))return;const title=String(form.querySelector<HTMLInputElement>('[name="title"]')?.value||"").trim(),content=String(form.querySelector<HTMLInputElement>('[name="contentUrl"]')?.value||"").trim();const course=current.find(x=>String(x.contentUrl||"").trim()===content&&content)||current.find(x=>String(x.title||"").trim()===title&&title);const label=document.createElement("label");label.className="wide";label.dataset.trainingExamField="1";const span=document.createElement("span");span.textContent="لینک آزمون";const input=document.createElement("input");input.type="url";input.required=true;input.placeholder="https://...";input.value=normalizedUrl(course?.examUrl);input.dataset.trainingExamUrl="1";label.append(span,input);const description=Array.from(form.querySelectorAll("label")).find(x=>x.querySelector("textarea[name='description']"));description?.parentElement?.insertBefore(label,description);if(!description)form.querySelector(".da-form-grid")?.appendChild(label)});root.querySelectorAll<HTMLTableRowElement>("table.da-table tbody tr").forEach(row=>{const cell=row.querySelector("td:first-child"),title=String(cell?.querySelector("strong")?.textContent||"").trim();if(!cell||!title||cell.querySelector(".tev-exam-row"))return;const course=current.find(x=>String(x.title||"").trim()===title),line=document.createElement("small");line.className="tev-exam-row";if(course?.examUrl){const a=document.createElement("a");a.href=normalizedUrl(course.examUrl);a.target="_blank";a.rel="noopener noreferrer";a.textContent="لینک آزمون";a.style.cssText="color:#087443;font-weight:900;text-decoration:none";line.appendChild(a)}else{line.textContent="آزمون: ثبت نشده";line.style.color="#9a6a18"}cell.appendChild(line)})};decorate();const observer=new MutationObserver(decorate);observer.observe(root,{childList:true,subtree:true});return()=>observer.disconnect()},[courses]);
 return <div ref={shell}><style>{`[data-training-exam-field="1"] input{direction:ltr}.tev-exam-row{margin-top:5px}`}</style><TrainingPageV2 access={access} notify={notify}/></div>;
}
