import React,{FormEvent,useEffect,useState} from "react";
import {ArrowRight,BookOpen,ChevronLeft,Search,Send,UserRoundCheck} from "lucide-react";
import "./admin.css";

type Notify=(message:string,tone?:"success"|"error"|"info")=>void;
type Mode="list"|"create"|"assign";
const fa=(value:unknown)=>Number(value||0).toLocaleString("fa-IR");
const text=(value:unknown,fallback="—")=>String(value??"").trim()||fallback;
const initials=(name:unknown)=>text(name,"م").split(/\s+/).filter(Boolean).map(x=>x[0]).join("").slice(0,2)||"م";
function can(access:any,action="view"){const module=(access?.allModules||[]).find((m:any)=>m.key==="staff.training")||(access?.modules||[]).find((m:any)=>m.key==="staff.training");return Boolean(module?.actions?.[action])}
async function api<T=any>(path:string,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers||{});if(typeof options.body==="string"&&!headers.has("content-type"))headers.set("content-type","application/json");const response=await fetch(path,{credentials:"same-origin",cache:"no-store",...options,headers});const raw=await response.text();let payload:any={};try{payload=raw?JSON.parse(raw):{}}catch{payload={}}if(!response.ok)throw new Error(payload.message||`خطای ${response.status}`);return payload as T}
function listFromCaregiverPayload(payload:any){const d=payload?.data??payload??{};if(Array.isArray(d))return d;if(Array.isArray(d.items))return d.items;if(Array.isArray(d.caregivers))return d.caregivers;if(Array.isArray(d.rows))return d.rows;return []}
function caregiverIdOf(value:any){return String(value?.id||value?.caregiverId||value?.caregiver_id||value?.profileId||"").trim()}

export function AdminTrainingMobileV2({access,onExit,notify}:{access:any;onExit:()=>void;notify:Notify}){
 const [mode,setMode]=useState<Mode>("list"),[data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[caregivers,setCaregivers]=useState<any[]>([]),[recipientQuery,setRecipientQuery]=useState(""),[recipientLoading,setRecipientLoading]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set());
 const load=async()=>{setError("");try{const p:any=await api("/api/training/admin");setData(p.data||{})}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 const searchRecipients=async(q=recipientQuery)=>{setRecipientLoading(true);try{const params=new URLSearchParams({page:"1",pageSize:"80"});if(q.trim())params.set("q",q.trim());const p:any=await api(`/api/admin/caregivers-page?${params}`);setCaregivers(listFromCaregiverPayload(p))}catch(e:any){notify(e.message,"error");setCaregivers([])}finally{setRecipientLoading(false)}};
 const openAssign=()=>{setSelected(new Set());setRecipientQuery("");setMode("assign");void searchRecipients("")};
 const toggle=(id:string)=>setSelected(prev=>{const next=new Set(prev);if(next.has(id))next.delete(id);else next.add(id);return next});
 const createCourse=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);try{await api("/api/training/courses",{method:"POST",body:JSON.stringify({title:fd.get("title"),category:fd.get("category"),description:fd.get("description"),durationMinutes:Number(fd.get("durationMinutes")||0),credit:Number(fd.get("credit")||0),mandatory:fd.get("mandatory")==="on",contentUrl:fd.get("contentUrl")})});notify("آموزش در بانک سازمان ثبت شد.","success");setMode("list");await load()}catch(e:any){notify(e.message,"error")}finally{setBusy(false)}};
 const assignCourse=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget),caregiverIds=[...selected];if(!caregiverIds.length)return notify("حداقل یک مراقب را انتخاب کنید.","error");if(!fd.get("courseId"))return notify("آموزش را انتخاب کنید.","error");setBusy(true);try{await api("/api/training/assignments",{method:"POST",body:JSON.stringify({courseId:fd.get("courseId"),caregiverIds,dueAt:fd.get("dueAt")||null,assignmentNote:fd.get("assignmentNote")||""})});notify(`آموزش برای ${fa(caregiverIds.length)} مراقب ارسال شد.`,"success");setMode("list");setSelected(new Set());await load()}catch(e:any){notify(e.message,"error")}finally{setBusy(false)}};
 const courses=data?.courses||[],assignments=data?.assignments||[];
 if(mode==="create")return <div className="ma-app"><header className="ma-header"><button className="ma-header-action" onClick={()=>setMode("list")}><ArrowRight size={21}/></button><div className="ma-brand"><div><strong>ثبت آموزش</strong><small>بانک آموزش سلامت اول</small></div></div><span/></header><main className="ma-main"><form className="ma-form ma-card" onSubmit={createCourse}><div className="ma-form-grid"><label><span>عنوان</span><input name="title" required/></label><label><span>دسته‌بندی</span><input name="category"/></label><label><span>مدت به دقیقه</span><input name="durationMinutes" type="number" min="0"/></label><label><span>اعتبار آموزشی</span><input name="credit" type="number" min="0"/></label><label className="wide"><span>نشانی محتوا</span><input name="contentUrl" placeholder="https://... یا /api/files/..."/></label><label className="wide"><span>توضیحات</span><textarea name="description"/></label><label className="wide inline"><input name="mandatory" type="checkbox"/>آموزش الزامی</label></div><button className="ma-save" disabled={busy}>{busy?"در حال ثبت...":"ثبت در بانک آموزش"}</button></form></main></div>;
 if(mode==="assign")return <div className="ma-app"><header className="ma-header"><button className="ma-header-action" onClick={()=>setMode("list")}><ArrowRight size={21}/></button><div className="ma-brand"><div><strong>ارسال آموزش به مراقبین</strong><small>{fa(selected.size)} مراقب انتخاب شده</small></div></div><span/></header><main className="ma-main"><form className="ma-form" onSubmit={assignCourse}><section className="ma-card"><div className="ma-form-grid"><label className="wide"><span>آموزش</span><select name="courseId" required defaultValue=""><option value="">انتخاب آموزش</option>{courses.filter((x:any)=>String(x.status||"").toUpperCase()==="ACTIVE").map((x:any)=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label><label className="wide"><span>مهلت مشاهده</span><input name="dueAt" type="date"/></label><label className="wide"><span>پیام همراه</span><textarea name="assignmentNote" placeholder="توضیح یا پیام برای مراقب"/></label></div></section><section className="ma-card"><div className="ma-filter single"><input value={recipientQuery} onChange={e=>setRecipientQuery(e.target.value)} placeholder="نام، کد، موبایل یا کد ملی" onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void searchRecipients()}}}/><button type="button" onClick={()=>void searchRecipients()}><Search size={16}/> جست‌وجو</button></div><div className="ma-note"><UserRoundCheck size={18}/><span>{fa(selected.size)} مراقب انتخاب شده؛ انتخاب‌ها با جست‌وجوی بعدی حفظ می‌شوند.</span></div>{recipientLoading?<div className="ma-state"><strong>در حال جست‌وجوی مراقبین...</strong></div>:<div className="ma-user-list">{caregivers.map(c=>{const id=caregiverIdOf(c),checked=selected.has(id);return <button type="button" key={id} className={`ma-person ${checked?"selected":""}`} onClick={()=>toggle(id)}><span className="ma-person-avatar">{initials(c.fullName)}</span><span><strong>{text(c.fullName,"مراقب")}</strong><small>{text(c.membershipCode)} • {text(c.mobile)}</small></span><span className={`ma-pill ${checked?"":"soft"}`}>{checked?"انتخاب شد":"انتخاب"}</span></button>})}</div>}</section><button className="ma-save" disabled={busy||!selected.size}><Send size={17}/>{busy?"در حال ارسال...":`ارسال برای ${fa(selected.size)} مراقب`}</button></form></main></div>;
 return <div className="ma-app"><header className="ma-header"><button className="ma-header-action" onClick={onExit}><ArrowRight size={21}/></button><div className="ma-brand"><div><strong>بانک آموزش</strong><small>محتوا، تخصیص و پایش مشاهده</small></div></div><span className="ma-avatar"><BookOpen size={20}/></span></header><main className="ma-main"><div className="ma-stack">{error?<div className="ma-state error"><strong>دریافت اطلاعات انجام نشد</strong><small>{error}</small><button className="ma-btn" onClick={()=>void load()}>تلاش مجدد</button></div>:!data?<div className="ma-state"><strong>در حال دریافت اطلاعات...</strong></div>:<><section className="ma-metrics"><article className="ma-metric"><small>آموزش‌ها</small><strong>{fa(courses.length)}</strong></article><article className="ma-metric"><small>تخصیص‌ها</small><strong>{fa(assignments.length)}</strong></article></section>{can(access,"create")&&<div className="ma-stack"><button className="ma-btn primary wide" onClick={openAssign}><Send size={17}/>ارسال آموزش به مراقب</button><button className="ma-btn wide" onClick={()=>setMode("create")}><BookOpen size={17}/>ثبت آموزش جدید</button></div>}<div className="ma-user-list">{courses.map((course:any)=><article className="ma-person static" key={course.id}><span className="ma-person-avatar"><BookOpen size={20}/></span><span><strong>{text(course.title)}</strong><small>{text(course.category,"آموزش سازمانی")} • {fa(course.durationMinutes)} دقیقه • {fa(course.assignedCount)} تخصیص</small></span><span className="ma-row-end"><span className="ma-pill">{text(course.status)}</span><ChevronLeft size={17}/></span></article>)}</div>{!courses.length&&<div className="ma-state"><strong>هنوز آموزشی ثبت نشده است.</strong></div>}</>}</div></main></div>;
}
