import React,{FormEvent,useEffect,useState} from "react";
import {BadgeCheck,Clock3,Gift,Search,UsersRound,WalletCards,XCircle} from "lucide-react";
import "./admin-financial-referrals-v3.css";

type Notify=(message:string,tone?:"success"|"error"|"info")=>void;
const fa=(v:unknown)=>Number(v||0).toLocaleString("fa-IR"),money=(v:unknown)=>`${Number(v||0).toLocaleString("fa-IR")} تومان`,text=(v:unknown,f="—")=>String(v??"").trim()||f;
const dateFa=(v:unknown)=>{if(!v)return"—";try{return new Intl.DateTimeFormat("fa-IR-u-ca-persian",{dateStyle:"medium"}).format(new Date(String(v)))}catch{return String(v)}};
async function api<T=any>(path:string,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers||{});if(typeof options.body==="string"&&!headers.has("content-type"))headers.set("content-type","application/json");const response=await fetch(path,{credentials:"same-origin",cache:"no-store",...options,headers});const raw=await response.text();let payload:any={};try{payload=raw?JSON.parse(raw):{}}catch{payload={message:raw}}if(!response.ok)throw new Error(payload.message||`خطای ${response.status}`);return payload as T}
function canUpdate(access:any){const m=(access?.allModules||[]).find((x:any)=>x.key==="staff.financial_credits")||(access?.modules||[]).find((x:any)=>x.key==="staff.financial_credits");return Boolean(m?.actions?.update)}
function caseLabel(x:any){const confirmation=String(x.referrerConfirmationStatus||"").toUpperCase(),s=String(x.status||"").toUpperCase();if(confirmation==="PENDING")return"در انتظار تأیید معرف";if(confirmation==="REJECTED")return"ردشده توسط معرف";return ({PENDING_REGISTRATION_REVIEW:"منتظر تأیید پاداش ثبت‌نام",WAITING_CONTRACT:"منتظر اولین قرارداد",COMPLETED:"پاداش کامل پرداخت شد",REGISTRATION_REJECTED:"مرحله ثبت‌نام رد شد",CONTRACT_REJECTED:"مرحله قرارداد رد شد"} as Record<string,string>)[s]||s||"—"}

export function AdminReferralRewardsMobileV4({access,notify}:{access:any;notify:Notify}){
 const [data,setData]=useState<any>(null),[query,setQuery]=useState(""),[filter,setFilter]=useState(""),[busy,setBusy]=useState("");
 const load=async()=>{try{const p:any=await api(`/api/staff/financial-credits/referrals?q=${encodeURIComponent(query)}&status=${encodeURIComponent(filter)}`);setData(p.data||{})}catch(e:any){notify(e.message,"error")}};
 useEffect(()=>{void load()},[]);
 const decide=async(id:string,action:string)=>{const approve=action.startsWith("APPROVE"),note=prompt(approve?"توضیح تأیید (اختیاری):":"علت رد را وارد کنید:",approve?"تأیید پاداش معرفی":"")||"";if(!approve&&note.trim().length<3)return;setBusy(`${id}:${action}`);try{await api(`/api/staff/financial-credits/referrals/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({action,note})});notify(action==="APPROVE_REGISTRATION"?"۲۰۰ هزار تومان پاداش ثبت‌نام واریز شد.":action==="APPROVE_CONTRACT"?"۳۰۰ هزار تومان پاداش اولین قرارداد واریز شد.":"تصمیم پاداش معرفی ثبت شد.","success");await load()}catch(e:any){notify(e.message,"error")}finally{setBusy("")}};
 if(!data)return <div className="ma-state"><span className="ma-spinner"/><strong>در حال دریافت پاداش‌های معرفی...</strong></div>;
 const s=data.summary||{},rows=data.cases||[],mayDecide=canUpdate(access);
 return <div className="ma-stack mafr-page">
  <form className="mafr-search" onSubmit={(e:FormEvent)=>{e.preventDefault();void load()}}><div><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="معرف یا مراقب معرفی‌شده"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">همه وضعیت‌ها</option><option value="PENDING_REGISTRATION_REVIEW">مرحله ثبت‌نام</option><option value="WAITING_CONTRACT">مرحله قرارداد</option><option value="COMPLETED">تکمیل‌شده</option></select><button>جست‌وجو</button></form>
  <section className="mafr-kpis"><article><small>منتظر معرف</small><strong>{fa(s.awaitingReferrer||0)}</strong></article><article><small>منتظر ۲۰۰ هزار</small><strong>{fa(s.awaitingAdminRegistration||0)}</strong></article><article><small>منتظر قرارداد</small><strong>{fa(s.waitingContract||0)}</strong></article><article><small>کل پاداش قطعی</small><strong>{money(s.totalApprovedAmountToman||0)}</strong></article></section>
  <section className="mafr-policy"><Gift size={20}/><div><strong>پاداش معرفی مستقل از وام است</strong><small>۲۰۰ هزار تومان پس از تأیید معرف، فعال‌شدن حساب و تأیید مدیر؛ ۳۰۰ هزار تومان فقط یک‌بار برای اولین ورود به قرارداد.</small></div></section>
  {rows.length?<div className="mafr-list">{rows.map((x:any)=><article key={x.id} className="mafr-case"><header><div><strong>{text(x.referrerName,"معرف")}</strong><small>{text(x.referrerMembershipCode)} • {text(x.referrerMobile)}</small></div><span>{caseLabel(x)}</span></header><div className="mafr-person"><UsersRound size={18}/><div><strong>{text(x.referredName,"مراقب معرفی‌شده")}</strong><small>{text(x.referredMembershipCode)} • {text(x.referredMobile)}</small></div></div><div className="mafr-grid"><div><small>تأیید معرف</small><strong>{String(x.referrerConfirmationStatus).toUpperCase()==="APPROVED"?"تأیید شده":String(x.referrerConfirmationStatus).toUpperCase()==="PENDING"?"در انتظار":"رد شده"}</strong></div><div><small>حساب معرفی‌شده</small><strong>{text(x.referredAccountStatus)}</strong></div><div><small>پاداش ثبت‌نام</small><strong>{x.registrationRewardTransactionId?money(x.registrationRewardToman):"پرداخت نشده"}</strong>{x.registrationPaymentAt&&<small>{dateFa(x.registrationPaymentAt)}</small>}</div><div><small>پاداش اولین قرارداد</small><strong>{x.contractRewardTransactionId?money(x.contractRewardToman):x.contractEligible?"واجد واریز":"هنوز قرارداد نشده"}</strong></div></div>{mayDecide&&<footer>{String(x.referrerConfirmationStatus).toUpperCase()==="APPROVED"&&x.status==="PENDING_REGISTRATION_REVIEW"&&!x.registrationRewardTransactionId&&<><button className="approve" disabled={Boolean(busy)} onClick={()=>void decide(x.id,"APPROVE_REGISTRATION")}><BadgeCheck size={15}/>تأیید و واریز ۲۰۰</button><button className="reject" disabled={Boolean(busy)} onClick={()=>void decide(x.id,"REJECT_REGISTRATION")}><XCircle size={15}/>رد</button></>}{x.status==="WAITING_CONTRACT"&&x.contractEligible&&!x.contractRewardTransactionId&&<button className="approve wide" disabled={Boolean(busy)} onClick={()=>void decide(x.id,"APPROVE_CONTRACT")}><WalletCards size={15}/>واریز ۳۰۰ هزار</button>}{String(x.referrerConfirmationStatus).toUpperCase()==="PENDING"&&<span className="mafr-wait"><Clock3 size={14}/>ابتدا معرف باید تأیید کند.</span>}</footer>}</article>)}</div>:<div className="ma-state"><strong>پرونده معرفی وجود ندارد</strong><small>معرفی‌های ثبت‌شده اینجا نمایش داده می‌شوند.</small></div>}
 </div>
}
