import React,{useState} from "react";
import {ArrowRight,BookOpen,ClipboardCheck} from "lucide-react";
import {AdminEvaluationsMobileV4} from "./admin-evaluations-v4";
import {AdminTrainingExamEvaluationMobile} from "./admin-training-exam-evaluation-v1";

type Notify=(message:string,tone?:"success"|"error"|"info")=>void;
export function AdminEvaluationsMobileV5({user,onExit}:{user:any;onExit:()=>void}){
 const [section,setSection]=useState<"professional"|"training">("professional"),[notice,setNotice]=useState<{message:string;tone:string}|null>(null);const notify:Notify=(message,tone="info")=>{setNotice({message,tone});window.setTimeout(()=>setNotice(null),3200)};
 if(section==="professional")return <div className="mae-v5-shell"><style>{`.mae-v5-switch{position:sticky;top:0;z-index:20;display:flex;gap:7px;padding:9px 12px;background:#f5f9f7;border-bottom:1px solid #dce7e1}.mae-v5-switch button{flex:1;border:1px solid #d8e5df;background:#fff;border-radius:12px;padding:9px 7px;font:inherit;font-size:11px;font-weight:900;color:#466057;display:flex;align-items:center;justify-content:center;gap:6px}.mae-v5-switch button.active{background:#087443;border-color:#087443;color:#fff}`}</style><div className="mae-v5-switch"><button className="active"><ClipboardCheck size={16}/>ارزیابی حرفه‌ای</button><button onClick={()=>setSection("training")}><BookOpen size={16}/>ارزیابی آموزش</button></div><AdminEvaluationsMobileV4 user={user} onExit={onExit}/></div>;
 return <div className="ma-app"><style>{`.mae-v5-switch{display:flex;gap:7px;padding:10px 12px;background:#f5f9f7}.mae-v5-switch button{flex:1;border:1px solid #d8e5df;background:#fff;border-radius:12px;padding:9px 7px;font:inherit;font-size:11px;font-weight:900;color:#466057;display:flex;align-items:center;justify-content:center;gap:6px}.mae-v5-switch button.active{background:#087443;border-color:#087443;color:#fff}`}</style><header className="ma-header"><button className="ma-header-action" onClick={onExit}><ArrowRight size={21}/></button><div className="ma-brand"><div><strong>ارزیابی آموزش</strong><small>نتایج آزمون دوره‌های آموزشی</small></div></div><span className="ma-avatar"><BookOpen size={20}/></span></header><div className="mae-v5-switch"><button onClick={()=>setSection("professional")}><ClipboardCheck size={16}/>ارزیابی حرفه‌ای</button><button className="active"><BookOpen size={16}/>ارزیابی آموزش</button></div><main className="ma-main"><AdminTrainingExamEvaluationMobile notify={notify}/></main>{notice&&<div className={`ma-toast ${notice.tone}`}>{notice.message}</div>}</div>;
}
