import React,{useEffect,useState} from "react";
import {CheckCircle2,Clock3,RefreshCw,XCircle} from "lucide-react";

type Notify=(message:string,tone?:"success"|"error"|"info")=>void;
const fa=(value:unknown)=>Number(value||0).toLocaleString("fa-IR");
const money=(value:unknown)=>`${Number(value||0).toLocaleString("fa-IR")} تومان`;
const text=(value:unknown,fallback="—")=>String(value??"").trim()||fallback;
const stateLabel:Record<string,string>={REQUESTED:"در انتظار بررسی",UNDER_REVIEW:"در حال بررسی",REJECTED:"رد شده",COMPLETED:"تکمیل شده"};
async function api(path:string,options:RequestInit={}){const headers=new Headers(options.headers||{});if(typeof options.body==="string"&&!headers.has("content-type"))headers.set("content-type","application/json");const response=await fetch(path,{credentials:"same-origin",cache:"no-store",...options,headers});const raw=await response.text();let payload:any={};try{payload=raw?JSON.parse(raw):{}}catch{payload={message:raw}}if(!response.ok)throw new Error(payload.message||`خطای ${response.status}`);return payload}

export function AdminReferralMilestoneReviewV1({notify}:{notify:Notify}){const [data,setData]=useState<any>(null),[busy,setBusy]=useState("");const load=async()=>{try{const response=await api("/api/staff/financial-credits/referrals/milestones");setData(response.data||{})}catch(e:any){notify(e.message||"دریافت درخواست‌های پله معرفی انجام نشد.","error")}};useEffect(()=>{void load()},[]);const act=async(id:string,action:"UNDER_REVIEW"|"REJECT"|"APPROVE")=>{setBusy(`${id}:${action}`);try{await api(`/api/staff/financial-credits/referrals/milestones/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({action})});notify("وضعیت درخواست ثبت شد.","success");await load()}catch(e:any){notify(e.message||"ثبت تصمیم انجام نشد.","error")}finally{setBusy("")}};if(!data)return <section className="mafr-policy"><Clock3 size={18}/><div><strong>درخواست‌های پله معرفی</strong><small>در حال دریافت...</small></div></section>;const rows=data.requests||[],s=data.summary||{};return <section className="ma-stack"><section className="mafr-kpis"><article><small>درخواست پله‌ها</small><strong>{fa(s.total||0)}</strong></article><article><small>در انتظار بررسی</small><strong>{fa(Number(s.requested||0)+Number(s.underReview||0))}</strong></article></section><section className="mafr-policy"><RefreshCw size={18}/><div><strong>درخواست‌های پله معرفی</strong><small>بررسی و تصمیم مدیر در همین تب انجام می‌شود و سابقه تغییرات نگهداری می‌شود.</small></div></section>{rows.map((item:any)=><article key={item.id} className="mafr-case"><header><div><strong>{text(item.caregiverName)}</strong><small>{text(item.membershipCode)} • {text(item.mobile)}</small></div><span>{stateLabel[String(item.status)]||text(item.status)}</span></header><div className="mafr-grid"><div><small>پله</small><strong>{text(item.title||item.milestoneKey)}</strong></div><div><small>مبلغ</small><strong>{money(item.amountToman||0)}</strong></div></div>{String(item.status)!=="COMPLETED"&&<footer><button disabled={Boolean(busy)} onClick={()=>void act(item.id,"UNDER_REVIEW")}><Clock3 size={14}/>بررسی</button><button disabled={Boolean(busy)} onClick={()=>void act(item.id,"REJECT")}><XCircle size={14}/>رد</button><button disabled={Boolean(busy)} onClick={()=>void act(item.id,"APPROVE")}><CheckCircle2 size={14}/>تأیید</button></footer>}</article>)}</section>}
