import React,{FormEvent,useEffect,useMemo,useState} from "react";
import {ArrowRight,BookOpen,ChevronLeft,Pencil,Search,Send,Trash2,UserRoundCheck} from "lucide-react";
import "./admin.css";
import {TRAINING_CLINICAL_AUDIENCE_OPTIONS,TRAINING_CLINICAL_STAGE_OPTIONS,TRAINING_DELIVERY_OPTIONS,TRAINING_GENERAL_STAGE_OPTIONS,TRAINING_GROUP_OPTIONS,TRAINING_NATURE_OPTIONS,TRAINING_TAXONOMY_LEAVES,trainingDeliveryLabel,trainingNatureLabel,trainingTaxonomyKey,trainingTaxonomyOf} from "../shared/training-taxonomy-v2";

type Notify=(message:string,tone?:"success"|"error"|"info")=>void;
type Mode="list"|"create"|"edit"|"assign";
const FILTER_TABS=[...TRAINING_TAXONOMY_LEAVES,{key:"LEGACY",label:"دسته‌بندی‌نشده",pathLabel:"دسته‌بندی قدیمی / نیازمند بازطبقه‌بندی"}] as const;
const CATEGORY_TABS_CSS=`.atv2-category-tabs{display:flex;gap:7px;overflow-x:auto;padding:2px 0 8px;scrollbar-width:none}.atv2-category-tabs::-webkit-scrollbar{display:none}.atv2-category-tabs button{flex:0 0 auto;border:1px solid #dce7e1;background:#fff;border-radius:999px;padding:8px 11px;font:inherit;font-size:11px;font-weight:800;color:#496359;white-space:nowrap}.atv2-category-tabs button.active{background:#087443;color:#fff;border-color:#087443}.atv2-category-empty{padding:10px 12px;border:1px dashed #d8e6df;border-radius:14px;color:#6d8178;font-size:12px}.atv2-month{display:flex;align-items:center;border:1px solid #d9e4de;border-radius:12px;overflow:hidden;background:#fff}.atv2-month input{border:0!important;border-radius:0!important;flex:1;min-width:0}.atv2-month b{padding:0 12px;color:#087443;font-size:12px}.atv2-meta{display:flex;gap:5px;flex-wrap:wrap;margin-top:4px}.atv2-meta i{font-style:normal;background:#eff6f2;border-radius:999px;padding:3px 7px;font-size:10px;color:#456156}.atv2-taxonomy-note{grid-column:1/-1;background:#f3f9f6;border:1px solid #dbe9e2;border-radius:12px;padding:10px 12px;font-size:11px;color:#4d685d}`;
const fa=(value:unknown)=>Number(value||0).toLocaleString("fa-IR");
const text=(value:unknown,fallback="—")=>String(value??"").trim()||fallback;
const initials=(name:unknown)=>text(name,"م").split(/\s+/).filter(Boolean).map(x=>x[0]).join("").slice(0,2)||"م";
function can(access:any,action="view"){const module=(access?.allModules||[]).find((m:any)=>m.key==="staff.training")||(access?.modules||[]).find((m:any)=>m.key==="staff.training");return Boolean(module?.actions?.[action])}
async function api<T=any>(path:string,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers||{});if(typeof options.body==="string"&&!headers.has("content-type"))headers.set("content-type","application/json");const response=await fetch(path,{credentials:"same-origin",cache:"no-store",...options,headers});const raw=await response.text();let payload:any={};try{payload=raw?JSON.parse(raw):{}}catch{payload={}}if(!response.ok)throw new Error(payload.message||`خطای ${response.status}`);return payload as T}
function listFromCaregiverPayload(payload:any){const d=payload?.data??payload??{};if(Array.isArray(d))return d;if(Array.isArray(d.items))return d.items;if(Array.isArray(d.caregivers))return d.caregivers;if(Array.isArray(d.rows))return d.rows;return []}
function caregiverIdOf(value:any){return String(value?.id||value?.caregiverId||value?.caregiver_id||value?.profileId||"").trim()}
function metadataFromForm(fd:FormData){return {categoryGroup:String(fd.get("categoryGroup")||""),categoryAudience:String(fd.get("categoryAudience")||""),categoryStage:String(fd.get("categoryStage")||""),deliveryMode:String(fd.get("deliveryMode")||""),learningNature:String(fd.get("learningNature")||""),validityMonths:Number(fd.get("validityMonths")||0)}}
function TaxonomyFields({initial}:{initial?:any}){const taxonomy=trainingTaxonomyOf(initial||{}),[group,setGroup]=useState<string>(taxonomy.group||"CLINICAL"),[audience,setAudience]=useState<string>(taxonomy.audience||"ELDERLY"),[stage,setStage]=useState<string>(taxonomy.stage||(taxonomy.group==="GENERAL"?"ONBOARDING":"PRE_CONTRACT"));const stages=group==="GENERAL"?TRAINING_GENERAL_STAGE_OPTIONS:TRAINING_CLINICAL_STAGE_OPTIONS;const changeGroup=(next:string)=>{setGroup(next);setStage(next==="GENERAL"?"ONBOARDING":"PRE_CONTRACT")};return <><label><span>گروه آموزش</span><select name="categoryGroup" value={group} onChange={e=>changeGroup(e.target.value)} required>{TRAINING_GROUP_OPTIONS.map(x=><option value={x.key} key={x.key}>{x.label}</option>)}</select></label>{group==="CLINICAL"?<label><span>گروه هدف</span><select name="categoryAudience" value={audience} onChange={e=>setAudience(e.target.value)} required>{TRAINING_CLINICAL_AUDIENCE_OPTIONS.map(x=><option value={x.key} key={x.key}>{x.label}</option>)}</select></label>:<input type="hidden" name="categoryAudience" value=""/>}<label><span>مرحله آموزش</span><select name="categoryStage" value={stage} onChange={e=>setStage(e.target.value)} required>{stages.map(x=><option value={x.key} key={x.key}>{x.label}</option>)}</select></label></>}
function MetadataFields({initial}:{initial?:any}){return <><label><span>نوع آموزش</span><select name="deliveryMode" required defaultValue={String(initial?.deliveryMode||"")}><option value="" disabled>انتخاب نوع آموزش</option>{TRAINING_DELIVERY_OPTIONS.map(x=><option value={x.key} key={x.key}>{x.label}</option>)}</select></label><label><span>ماهیت آموزش</span><select name="learningNature" required defaultValue={String(initial?.learningNature||"")}><option value="" disabled>انتخاب ماهیت آموزش</option>{TRAINING_NATURE_OPTIONS.map(x=><option value={x.key} key={x.key}>{x.label}</option>)}</select></label><label><span>اعتبار آموزش</span><div className="atv2-month"><input name="validityMonths" type="number" min="0" step="1" defaultValue={Number(initial?.validityMonths??initial?.credit??0)}/><b>ماه</b></div></label></>}

export function AdminTrainingMobileV2({access,onExit,notify}:{access:any;onExit:()=>void;notify:Notify}){
 const [mode,setMode]=useState<Mode>("list"),[data,setData]=useState<any>(null),[error,setError]=useState(""),[busy,setBusy]=useState(false),[caregivers,setCaregivers]=useState<any[]>([]),[recipientQuery,setRecipientQuery]=useState(""),[recipientLoading,setRecipientLoading]=useState(false),[selected,setSelected]=useState<Set<string>>(new Set()),[categoryFilter,setCategoryFilter]=useState<string>("ALL"),[assignCategory,setAssignCategory]=useState<string>(TRAINING_TAXONOMY_LEAVES[0].key),[assignCourseId,setAssignCourseId]=useState(""),[editingCourse,setEditingCourse]=useState<any>(null);
 const load=async()=>{setError("");try{const p:any=await api("/api/training/admin");setData(p.data||{})}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load()},[]);
 const searchRecipients=async(q=recipientQuery)=>{setRecipientLoading(true);try{const params=new URLSearchParams({page:"1",pageSize:"80"});if(q.trim())params.set("q",q.trim());const p:any=await api(`/api/admin/caregivers-page?${params}`);setCaregivers(listFromCaregiverPayload(p))}catch(e:any){notify(e.message,"error");setCaregivers([])}finally{setRecipientLoading(false)}};
 const courses=data?.courses||[],assignments=data?.assignments||[];
 const counts=useMemo(()=>Object.fromEntries(FILTER_TABS.map(category=>[category.key,courses.filter((x:any)=>trainingTaxonomyKey(x)===category.key).length])),[courses]);
 const visibleTabs=useMemo(()=>FILTER_TABS.filter(tab=>tab.key!=="LEGACY"||Number(counts.LEGACY||0)>0),[counts]);
 const visibleCourses=categoryFilter==="ALL"?courses:courses.filter((x:any)=>trainingTaxonomyKey(x)===categoryFilter);
 const assignCourses=courses.filter((x:any)=>String(x.status||"").toUpperCase()==="ACTIVE"&&trainingTaxonomyKey(x)===assignCategory);
 const openAssign=()=>{setSelected(new Set());setRecipientQuery("");setAssignCourseId("");setAssignCategory(categoryFilter!=="ALL"&&visibleTabs.some(x=>x.key===categoryFilter)?categoryFilter:TRAINING_TAXONOMY_LEAVES[0].key);setMode("assign");void searchRecipients("")};
 const openEdit=(course:any)=>{setEditingCourse(course);setMode("edit")};
 const toggle=(id:string)=>setSelected(prev=>{const next=new Set(prev);if(next.has(id))next.delete(id);else next.add(id);return next});
 const createCourse=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget),contentUrl=String(fd.get("contentUrl")||"").trim(),meta=metadataFromForm(fd);if(!contentUrl)return notify("نشانی محتوای آموزش الزامی است.","error");setBusy(true);try{await api("/api/training/courses",{method:"POST",body:JSON.stringify({title:fd.get("title"),description:fd.get("description"),durationMinutes:Number(fd.get("durationMinutes")||0),mandatory:fd.get("mandatory")==="on",contentUrl,...meta})});notify("آموزش با دسته‌بندی جدید در بانک سازمان ثبت شد.","success");setMode("list");setCategoryFilter(trainingTaxonomyKey(meta));await load()}catch(e:any){notify(e.message,"error")}finally{setBusy(false)}};
 const editCourse=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();if(!editingCourse?.id)return;const fd=new FormData(e.currentTarget),contentUrl=String(fd.get("contentUrl")||"").trim(),meta=metadataFromForm(fd);if(!contentUrl)return notify("محتوای آموزش نمی‌تواند خالی باشد.","error");setBusy(true);try{await api(`/api/training/courses/${encodeURIComponent(editingCourse.id)}`,{method:"PATCH",body:JSON.stringify({title:fd.get("title"),description:fd.get("description"),durationMinutes:Number(fd.get("durationMinutes")||0),mandatory:fd.get("mandatory")==="on",contentUrl,...meta})});notify("محتوای آموزشی و دسته‌بندی آن ویرایش شد.","success");setCategoryFilter(trainingTaxonomyKey(meta));setEditingCourse(null);setMode("list");await load()}catch(e:any){notify(e.message,"error")}finally{setBusy(false)}};
 const removeCourse=async(course:any)=>{if(!course?.id)return;const assigned=Number(course.assignedCount||0);const message=`آموزش «${text(course.title)}» حذف شود؟\n${assigned?`این آموزش برای ${fa(assigned)} مراقب تخصیص داده شده است. `:""}از بانک و پنل فعال مراقبین حذف می‌شود، اما سوابق تخصیص و مشاهده برای گزارش‌ها باقی می‌ماند.`;if(!window.confirm(message))return;setBusy(true);try{await api(`/api/training/courses/${encodeURIComponent(course.id)}`,{method:"DELETE"});notify("آموزش از بانک فعال حذف شد.","success");if(editingCourse?.id===course.id)setEditingCourse(null);await load()}catch(e:any){notify(e.message,"error")}finally{setBusy(false)}};
 const assignCourse=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget),caregiverIds=[...selected];if(!caregiverIds.length)return notify("حداقل یک مراقب را انتخاب کنید.","error");if(!assignCourseId)return notify("آموزش را از دسته انتخاب‌شده انتخاب کنید.","error");setBusy(true);try{await api("/api/training/assignments",{method:"POST",body:JSON.stringify({courseId:assignCourseId,caregiverIds,dueAt:fd.get("dueAt")||null,assignmentNote:fd.get("assignmentNote")||""})});notify(`آموزش برای ${fa(caregiverIds.length)} مراقب ارسال شد و در اعلان‌های آن‌ها قرار گرفت.`,"success");setMode("list");setSelected(new Set());setAssignCourseId("");await load()}catch(e:any){notify(e.message,"error")}finally{setBusy(false)}};
 if(mode==="create")return <div className="ma-app"><style>{CATEGORY_TABS_CSS}</style><header className="ma-header"><button className="ma-header-action" onClick={()=>setMode("list")}><ArrowRight size={21}/></button><div className="ma-brand"><div><strong>ثبت آموزش</strong><small>بانک آموزش سلامت اول</small></div></div><span/></header><main className="ma-main"><form className="ma-form ma-card" onSubmit={createCourse}><div className="ma-form-grid"><label><span>عنوان</span><input name="title" required/></label><TaxonomyFields/><div className="atv2-taxonomy-note">بالینی: سالمند، بیمار یا کودک ← پیش از قرارداد/بازآموزی<br/>عمومی: بدو استخدام/بازآموزی</div><MetadataFields/><label><span>مدت به دقیقه</span><input name="durationMinutes" type="number" min="0"/></label><label className="wide"><span>نشانی محتوا</span><input name="contentUrl" required placeholder="https://... یا /api/files/..."/></label><label className="wide"><span>توضیحات</span><textarea name="description"/></label><label className="wide inline"><input name="mandatory" type="checkbox"/>آموزش الزامی</label></div><button className="ma-save" disabled={busy}>{busy?"در حال ثبت...":"ثبت در بانک آموزش"}</button></form></main></div>;
 if(mode==="edit"&&editingCourse)return <div className="ma-app"><style>{CATEGORY_TABS_CSS}</style><header className="ma-header"><button className="ma-header-action" onClick={()=>{setEditingCourse(null);setMode("list")}}><ArrowRight size={21}/></button><div className="ma-brand"><div><strong>ویرایش آموزش</strong><small>{text(editingCourse.title)}</small></div></div><span/></header><main className="ma-main"><form className="ma-form ma-card" onSubmit={editCourse}><div className="ma-form-grid">{trainingTaxonomyOf(editingCourse).legacy&&<div className="atv2-taxonomy-note">این آموزش با دسته‌بندی قدیمی ثبت شده؛ با ذخیره در ساختار جدید بازطبقه‌بندی می‌شود.</div>}<label><span>عنوان</span><input name="title" required defaultValue={text(editingCourse.title,"")}/></label><TaxonomyFields initial={editingCourse}/><MetadataFields initial={editingCourse}/><label><span>مدت به دقیقه</span><input name="durationMinutes" type="number" min="0" defaultValue={Number(editingCourse.durationMinutes||0)}/></label><label className="wide"><span>نشانی محتوا</span><input name="contentUrl" required defaultValue={text(editingCourse.contentUrl,"")} placeholder="https://... یا /api/files/..."/></label><label className="wide"><span>توضیحات</span><textarea name="description" defaultValue={text(editingCourse.description,"")}/></label><label className="wide inline"><input name="mandatory" type="checkbox" defaultChecked={Boolean(editingCourse.mandatory)}/>آموزش الزامی</label></div><button className="ma-save" disabled={busy}>{busy?"در حال ذخیره...":"ذخیره تغییرات"}</button></form></main></div>;
 if(mode==="assign")return <div className="ma-app"><style>{CATEGORY_TABS_CSS}</style><header className="ma-header"><button className="ma-header-action" onClick={()=>setMode("list")}><ArrowRight size={21}/></button><div className="ma-brand"><div><strong>ارسال آموزش به مراقبین</strong><small>{fa(selected.size)} مراقب انتخاب شده</small></div></div><span/></header><main className="ma-main"><form className="ma-form" onSubmit={assignCourse}><section className="ma-card"><div className="ma-card-head"><div><strong>دسته‌بندی آموزش</strong><small>شاخه آموزش را انتخاب کنید؛ فقط دوره‌های همان شاخه نمایش داده می‌شوند.</small></div></div><div className="atv2-category-tabs">{visibleTabs.map(category=><button type="button" key={category.key} className={assignCategory===category.key?"active":""} onClick={()=>{setAssignCategory(category.key);setAssignCourseId("")}}>{category.label} • {fa(counts[category.key]||0)}</button>)}</div><div className="ma-form-grid"><label className="wide"><span>آموزش انتخابی</span><select name="courseId" required value={assignCourseId} onChange={e=>setAssignCourseId(e.target.value)} disabled={!assignCourses.length}><option value="">انتخاب آموزش</option>{assignCourses.map((x:any)=><option value={x.id} key={x.id}>{x.title}</option>)}</select></label>{!assignCourses.length&&<div className="wide atv2-category-empty">در این دسته هنوز آموزش فعالی برای ارسال ثبت نشده است.</div>}<label className="wide"><span>مهلت مشاهده</span><input name="dueAt" type="date"/></label><label className="wide"><span>پیام همراه</span><textarea name="assignmentNote" placeholder="توضیح یا پیام برای مراقب"/></label></div></section><section className="ma-card"><div className="ma-filter single"><input value={recipientQuery} onChange={e=>setRecipientQuery(e.target.value)} placeholder="نام، کد، موبایل یا کد ملی" onKeyDown={e=>{if(e.key==="Enter"){e.preventDefault();void searchRecipients()}}}/><button type="button" onClick={()=>void searchRecipients()}><Search size={16}/> جست‌وجو</button></div><div className="ma-note"><UserRoundCheck size={18}/><span>{fa(selected.size)} مراقب انتخاب شده؛ انتخاب‌ها با جست‌وجوی بعدی حفظ می‌شوند.</span></div>{recipientLoading?<div className="ma-state"><strong>در حال جست‌وجوی مراقبین...</strong></div>:<div className="ma-user-list">{caregivers.map(c=>{const id=caregiverIdOf(c),checked=selected.has(id);return <button type="button" key={id} className={`ma-person ${checked?"selected":""}`} onClick={()=>toggle(id)}><span className="ma-person-avatar">{initials(c.fullName)}</span><span><strong>{text(c.fullName,"مراقب")}</strong><small>{text(c.membershipCode)} • {text(c.mobile)}</small></span><span className={`ma-pill ${checked?"":"soft"}`}>{checked?"انتخاب شد":"انتخاب"}</span></button>})}</div>}</section><button className="ma-save" disabled={busy||!selected.size||!assignCourseId}><Send size={17}/>{busy?"در حال ارسال...":`ارسال برای ${fa(selected.size)} مراقب`}</button></form></main></div>;
 return <div className="ma-app"><style>{CATEGORY_TABS_CSS}</style><header className="ma-header"><button className="ma-header-action" onClick={onExit}><ArrowRight size={21}/></button><div className="ma-brand"><div><strong>بانک آموزش</strong><small>محتوا، دسته‌بندی، تخصیص و پایش مشاهده</small></div></div><span className="ma-avatar"><BookOpen size={20}/></span></header><main className="ma-main"><div className="ma-stack">{error?<div className="ma-state error"><strong>دریافت اطلاعات انجام نشد</strong><small>{error}</small><button className="ma-btn" onClick={()=>void load()}>تلاش مجدد</button></div>:!data?<div className="ma-state"><strong>در حال دریافت اطلاعات...</strong></div>:<><section className="ma-metrics"><article className="ma-metric"><small>آموزش‌ها</small><strong>{fa(courses.length)}</strong></article><article className="ma-metric"><small>تخصیص‌ها</small><strong>{fa(assignments.length)}</strong></article></section>{can(access,"create")&&<div className="ma-stack"><button className="ma-btn primary wide" onClick={openAssign}><Send size={17}/>ارسال آموزش به مراقب</button><button className="ma-btn wide" onClick={()=>setMode("create")}><BookOpen size={17}/>ثبت آموزش جدید</button></div>}<div className="atv2-category-tabs"><button type="button" className={categoryFilter==="ALL"?"active":""} onClick={()=>setCategoryFilter("ALL")}>همه • {fa(courses.length)}</button>{visibleTabs.map(category=><button type="button" key={category.key} className={categoryFilter===category.key?"active":""} onClick={()=>setCategoryFilter(category.key)}>{category.label} • {fa(counts[category.key]||0)}</button>)}</div><div className="ma-user-list">{visibleCourses.map((course:any)=>{const tax=trainingTaxonomyOf(course);return <article className="ma-person static atv3-course-row" key={course.id}><span className="ma-person-avatar"><BookOpen size={20}/></span><span><strong>{text(course.title)}</strong><small>{tax.legacy?`نیازمند بازطبقه‌بندی • ${text(course.category)}`:tax.label} • {fa(course.validityMonths??course.credit??0)} ماه</small><span className="atv2-meta"><i>{trainingDeliveryLabel(course.deliveryMode)}</i><i>{trainingNatureLabel(course.learningNature)}</i></span></span>{(can(access,"update")||can(access,"delete"))&&<span className="atv3-course-actions">{can(access,"update")&&<button type="button" className="atv3-course-action" onClick={()=>openEdit(course)} disabled={busy}><Pencil size={15}/>ویرایش</button>}{can(access,"delete")&&<button type="button" className="atv3-course-action danger" onClick={()=>void removeCourse(course)} disabled={busy}><Trash2 size={15}/>حذف</button>}</span>}<span className="ma-row-end"><span className="ma-pill">{text(course.status)}</span><ChevronLeft size={17}/></span></article>})}</div>{!visibleCourses.length&&<div className="ma-state"><strong>در این دسته هنوز آموزشی ثبت نشده است.</strong></div>}</>}</div></main></div>;
}