import React,{FormEvent,useEffect,useMemo,useState} from "react";
import {BadgeCheck,ChevronLeft,ClipboardCheck,FilePlus2,History,Home,Search,ShieldCheck,X} from "lucide-react";
import "./admin-evaluations-v2.css";

type Notify=(message:string,tone?:"success"|"error"|"info")=>void;
const text=(value:unknown,fallback="—")=>String(value??"").trim()||fallback;
const fa=(value:unknown)=>Number(value||0).toLocaleString("fa-IR");
const statusFa:Record<string,string>={FINAL:"نهایی",DRAFT:"پیش‌نویس",ACTIVE:"فعال",PENDING:"در انتظار"};
const status=(value:unknown)=>statusFa[String(value||"").toUpperCase()]||text(value);
const dateFa=(value:unknown)=>{if(!value)return"—";try{return new Intl.DateTimeFormat("fa-IR-u-ca-persian",{dateStyle:"medium"}).format(new Date(String(value)))}catch{return String(value)}};
const initials=(name:unknown)=>text(name,"م").split(/\s+/).filter(Boolean).map(x=>x[0]).join("").slice(0,2)||"م";
async function api<T=any>(path:string,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers||{});if(typeof options.body==="string"&&!headers.has("content-type"))headers.set("content-type","application/json");const response=await fetch(path,{credentials:"same-origin",cache:"no-store",...options,headers});const raw=await response.text();let payload:any={};try{payload=raw?JSON.parse(raw):{}}catch{payload={detail:raw}}if(!response.ok)throw new Error(payload.message||`خطای ${response.status}`);return payload as T}
function can(access:any,action:"view"|"create"|"update"){const module=(access?.allModules||[]).find((m:any)=>m.key==="staff.evaluations")||(access?.modules||[]).find((m:any)=>m.key==="staff.evaluations");return Boolean(module?.actions?.[action])}
function Spinner({label="در حال دریافت اطلاعات..."}:{label?:string}){return <div className="mae-state"><span className="mae-spinner"/><strong>{label}</strong></div>}
function ErrorBox({message,retry}:{message:string;retry?:()=>void}){return <div className="mae-state error"><strong>دریافت اطلاعات انجام نشد</strong><small>{message}</small>{retry&&<button onClick={retry}>تلاش مجدد</button>}</div>}
function ScoreLegend(){return <section className="mae-logic"><div><ShieldCheck size={18}/><strong>منطق امتیازدهی</strong></div><p>هر معیار از ۱ تا ۵ امتیاز می‌گیرد: ۱ ضعیف، ۲ نیازمند بهبود، ۳ قابل قبول، ۴ خوب و ۵ ممتاز.</p><p>امتیاز هر شاخص از میانگین معیارهای همان شاخص × ۲۰ محاسبه می‌شود و امتیاز نهایی، میانگین هشت شاخص کامل است.</p></section>}

function EvaluationWorkspace({caregiver,access,notify,onBack}:{caregiver:any;access:any;notify:Notify;onBack:()=>void}){
 const caregiverId=String(caregiver?.id||caregiver?.caregiverId||"");
 const [data,setData]=useState<any>(null),[evaluationId,setEvaluationId]=useState(""),[draft,setDraft]=useState<Record<string,{score:number|null;note:string}>>({}),[selectedIndicator,setSelectedIndicator]=useState(""),[busy,setBusy]=useState(false),[periodModal,setPeriodModal]=useState(false),[error,setError]=useState("");
 const load=async(id=evaluationId)=>{setError("");try{const q=new URLSearchParams({caregiverId});if(id)q.set("evaluationId",id);const p:any=await api(`/api/evaluations?${q}`),d=p.data||{};setData(d);const nextId=d.evaluation?.id||id||"";setEvaluationId(nextId);const next:any={};for(const ind of d.evaluation?.indicators||[])for(const cr of ind.criteria||[])next[cr.code]={score:cr.score??null,note:cr.note||""};setDraft(next);setSelectedIndicator(current=>(d.evaluation?.indicators||[]).some((x:any)=>x.code===current)?current:"")}catch(e:any){setError(e.message)}};
 useEffect(()=>{if(caregiverId)void load("")},[caregiverId]);
 const selectPeriod=async(id:string)=>{setEvaluationId(id);setSelectedIndicator("");await load(id);window.scrollTo({top:0,behavior:"smooth"})};
 const saveIndicator=async(ind:any)=>{if(!data?.evaluation)return;const scores=(ind.criteria||[]).map((c:any)=>({criterionCode:c.code,score:Number(draft[c.code]?.score),note:String(draft[c.code]?.note||"").trim()})).filter((x:any)=>Number.isInteger(x.score)&&x.score>=1&&x.score<=5);if(!scores.length)return notify("حداقل یک معیار را امتیازدهی کنید.","error");setBusy(true);try{await api(`/api/evaluations/${encodeURIComponent(data.evaluation.id)}/indicators/${encodeURIComponent(ind.code)}`,{method:"PUT",body:JSON.stringify({scores})});notify(`شاخص ${ind.code} ذخیره شد.`,"success");await load(data.evaluation.id)}catch(e:any){notify(e.message,"error")}finally{setBusy(false)}};
 const finalize=async()=>{const ev=data?.evaluation;if(!ev)return;for(const ind of ev.indicators||[])for(const cr of ind.criteria||[]){const score=Number(draft[cr.code]?.score);if(!Number.isInteger(score)||score<1||score>5)return notify(`معیار ${cr.code} هنوز امتیاز ندارد.`,"error")}if(!confirm("تمام معیارها ذخیره و این دوره نهایی شود؟"))return;setBusy(true);try{for(const ind of ev.indicators||[]){const scores=(ind.criteria||[]).map((c:any)=>({criterionCode:c.code,score:Number(draft[c.code]?.score),note:String(draft[c.code]?.note||"").trim()}));await api(`/api/evaluations/${encodeURIComponent(ev.id)}/indicators/${encodeURIComponent(ind.code)}`,{method:"PUT",body:JSON.stringify({scores})})}await api(`/api/evaluations/${encodeURIComponent(ev.id)}/finalize`,{method:"POST"});notify("ارزیابی نهایی شد و کارنامه رسمی ثبت شد.","success");await load(ev.id)}catch(e:any){notify(e.message,"error")}finally{setBusy(false)}};
 const createPeriod=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const fd=new FormData(e.currentTarget);setBusy(true);try{const p:any=await api("/api/evaluations",{method:"POST",body:JSON.stringify({caregiverId,title:fd.get("title"),startDate:fd.get("startDate"),endDate:fd.get("endDate")})});setPeriodModal(false);notify("دوره ارزیابی جدید ایجاد شد.","success");await load(p.data?.evaluation?.id||"")}catch(x:any){notify(x.message,"error")}finally{setBusy(false)}};
 if(error)return <><button className="mae-back" onClick={onBack}><ChevronLeft size={18}/>بازگشت به مراقبین</button><ErrorBox message={error} retry={()=>load(evaluationId)}/></>;
 if(!data)return <Spinner label="در حال بازکردن کارنامه‌های مراقب..."/>;
 const ev=data.evaluation,periods=data.periods||[],active=ev?.indicators?.find((x:any)=>x.code===selectedIndicator)||null;
 return <div className="mae-workspace">
  <button className="mae-back" onClick={onBack}><ChevronLeft size={18}/>بازگشت به فهرست مراقبین</button>
  <section className="mae-person-head"><div className="mae-avatar">{initials(caregiver.fullName)}</div><div><small>پرونده ارزیابی و پروانه</small><h2>{text(caregiver.fullName,"مراقب")}</h2><p>{text(caregiver.membershipCode)} • {text(caregiver.mobile)}</p></div>{can(access,"create")&&<button className="mae-new-period" onClick={()=>setPeriodModal(true)}><FilePlus2 size={18}/>دوره جدید</button>}</section>
  <section className="mae-history"><header><div><History size={18}/><strong>سابقه کارنامه‌ها</strong></div><small>{fa(periods.length)} دوره ثبت‌شده</small></header><div className="mae-period-strip">{periods.map((p:any)=><button key={p.id} className={p.id===evaluationId?"active":""} onClick={()=>void selectPeriod(p.id)}><div><strong>{text(p.title,"دوره ارزیابی")}</strong><span className={`mae-status ${String(p.status).toLowerCase()}`}>{status(p.status)}</span></div><b>{p.finalScore==null?"—":fa(p.finalScore)}</b><small>{dateFa(p.startDate)} تا {dateFa(p.endDate)}</small></button>)}</div></section>
  {ev?<>
   <section className="mae-summary"><article><small>وضعیت دوره</small><strong>{status(ev.status)}</strong></article><article><small>امتیاز فعلی</small><strong>{fa(ev.finalScore??ev.liveOverallScore??0)}</strong></article><article><small>شاخص کامل</small><strong>{fa(ev.completedIndicators||0)} / {fa(ev.indicators?.length||8)}</strong></article><article><small>معیار امتیازدار</small><strong>{fa(ev.scoredCriteria||0)} / {fa(ev.totalCriteria||0)}</strong></article></section>
   <ScoreLegend/>
   <section className="mae-section"><header><div><ClipboardCheck size={19}/><div><strong>شاخص‌های ارزیابی</strong><small>برای بازکردن معیارها روی شاخص بزنید.</small></div></div></header><div className="mae-indicator-grid">{(ev.indicators||[]).map((ind:any)=><button key={ind.code} className={`mae-indicator ${selectedIndicator===ind.code?"active":""} ${ind.complete?"complete":""}`} onClick={()=>setSelectedIndicator(ind.code)}><div className="mae-indicator-top"><span>{ind.code}</span>{ind.complete&&<BadgeCheck size={17}/>}</div><strong>{text(ind.title,"شاخص ارزیابی")}</strong><small>{text(ind.sources,"منبع ارزیابی ثبت نشده")}</small><footer><span>{fa(ind.scoredCount||0)} / {fa(ind.criteriaCount||0)} معیار</span><b>{ind.score??ind.liveScore==null?"—":fa(ind.score??ind.liveScore)}</b></footer></button>)}</div></section>
   {active?<section className="mae-section mae-criteria-section"><header><div><ClipboardCheck size={19}/><div><strong>{active.code} • {text(active.title)}</strong><small>{text(active.sources)}</small></div></div><span className="mae-score-badge">{active.score??active.liveScore==null?"—":fa(active.score??active.liveScore)}</span></header><div className="mae-criteria-list">{(active.criteria||[]).map((cr:any)=><article key={cr.code} className="mae-criterion"><div className="mae-criterion-title"><span>{cr.code}</span><strong>{text(cr.title,"معیار ارزیابی")}</strong></div><div className="mae-score-scale">{[1,2,3,4,5].map(n=><label key={n} className={Number(draft[cr.code]?.score)===n?"selected":""}><input type="radio" name={`score-${cr.code}`} checked={Number(draft[cr.code]?.score)===n} onChange={()=>setDraft(prev=>({...prev,[cr.code]:{...(prev[cr.code]||{note:""}),score:n}}))} disabled={ev.status==="FINAL"||!can(access,"update")}/><span>{fa(n)}</span><small>{["ضعیف","نیازمند بهبود","قابل قبول","خوب","ممتاز"][n-1]}</small></label>)}</div><textarea value={draft[cr.code]?.note||""} onChange={e=>setDraft(prev=>({...prev,[cr.code]:{...(prev[cr.code]||{score:null}),note:e.target.value}}))} placeholder="یادداشت ارزیاب برای این معیار" disabled={ev.status==="FINAL"||!can(access,"update")}/></article>)}</div>{ev.status!=="FINAL"&&can(access,"update")&&<button className="mae-save" disabled={busy} onClick={()=>void saveIndicator(active)}>ذخیره شاخص {active.code}</button>}</section>:<div className="mae-select-hint">یک کارت شاخص را انتخاب کنید تا معیارها و امتیازدهی آن باز شود.</div>}
   {ev.status!=="FINAL"&&can(access,"update")&&<button className="mae-finalize" disabled={busy} onClick={()=>void finalize()}><BadgeCheck size={19}/>نهایی‌سازی و صدور کارنامه</button>}
  </>:<div className="mae-select-hint">برای این مراقب دوره ارزیابی وجود ندارد؛ یک دوره جدید ایجاد کنید.</div>}
  {periodModal&&<div className="mae-modal-backdrop" onClick={()=>setPeriodModal(false)}><section className="mae-modal" onClick={e=>e.stopPropagation()}><button className="mae-close" onClick={()=>setPeriodModal(false)}><X size={20}/></button><h3>ایجاد دوره ارزیابی جدید</h3><p>دوره جدید به سابقه کارنامه‌های همین مراقب اضافه می‌شود.</p><form onSubmit={createPeriod}><label><span>عنوان دوره</span><input name="title" required placeholder="مثلاً ارزیابی تابستان ۱۴۰۵"/></label><div><label><span>تاریخ شروع</span><input name="startDate" type="date" required/></label><label><span>تاریخ پایان</span><input name="endDate" type="date" required/></label></div><button disabled={busy}>ایجاد دوره ارزیابی</button></form></section></div>}
 </div>
}

export function AdminEvaluationsMobileV2({user,onExit}:{user:any;onExit:()=>void}){
 const [access,setAccess]=useState<any>(null),[rows,setRows]=useState<any[]>([]),[pagination,setPagination]=useState<any>({}),[page,setPage]=useState(1),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[selected,setSelected]=useState<any>(null),[notice,setNotice]=useState<{message:string;tone:string}|null>(null);
 const notify:Notify=(message,tone="info")=>{setNotice({message,tone});window.setTimeout(()=>setNotice(null),3200)};
 const loadAccess=async()=>{try{const p:any=await api("/api/access/me");setAccess(p.data)}catch(e:any){setError(e.message)}};
 const load=async(next=page,q=query)=>{setLoading(true);setError("");try{const params=new URLSearchParams({page:String(next),pageSize:"25"});if(q.trim())params.set("q",q.trim());const p:any=await api(`/api/admin/caregivers-page?${params}`),d=p.data||{};setRows(Array.isArray(d.items)?d.items:[]);setPagination(d.pagination||{});setPage(next)}catch(e:any){setRows([]);setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{void Promise.all([loadAccess(),load(1,"")])},[]);
 const totalPages=Number(pagination.totalPages||pagination.pages||1),total=Number(pagination.total||rows.length);
 return <div className="ma-app mae-app"><header className="ma-header mae-header"><button className="ma-menu" onClick={onExit}><Home size={21}/></button><div className="ma-brand"><img src="/logo-salamat-aval.svg" alt="سلامت اول"/><div><strong>ارزیابی و پروانه</strong><small>پنل مدیر سامانه</small></div></div><div className="ma-avatar">{initials(user?.fullName||"مدیر")}</div></header><main className="ma-main mae-main">{selected?<EvaluationWorkspace caregiver={selected} access={access} notify={notify} onBack={()=>setSelected(null)}/>:<div className="mae-directory"><section className="mae-title"><span><ClipboardCheck size={21}/></span><div><h1>ارزیابی و پروانه مراقبین</h1><p>مراقب را جست‌وجو کنید و برای دیدن سوابق کارنامه روی پرونده بزنید.</p></div></section><form className="mae-search" onSubmit={e=>{e.preventDefault();void load(1,query)}}><Search size={19}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام، شماره پرونده، موبایل یا کد ملی"/><button>جست‌وجو</button></form>{error?<ErrorBox message={error} retry={()=>load(page,query)}/>:loading?<Spinner label="در حال دریافت فهرست مراقبین..."/>:<><div className="mae-caregiver-list">{rows.map((c:any)=><button key={c.id} onClick={()=>setSelected(c)}><span className="mae-avatar small">{initials(c.fullName)}</span><div><strong>{text(c.fullName,"مراقب")}</strong><small>{text(c.membershipCode)} • {text(c.mobile)}</small></div><span className="mae-row-level">{text(c.professionalLevel,"کارنامه")}</span><ChevronLeft size={18}/></button>)}</div><div className="mae-pager"><button disabled={page<=1} onClick={()=>void load(page-1,query)}>قبلی</button><span>{fa(total)} مراقب • صفحه {fa(page)} از {fa(totalPages)}</span><button disabled={page>=totalPages} onClick={()=>void load(page+1,query)}>بعدی</button></div></>}</div>}</main>{notice&&<div className={`ma-toast ${notice.tone}`}>{notice.message}</div>}</div>
}
