import React,{useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {BookOpen,ClipboardCheck,UserCheck} from "lucide-react";
import {AdminCaregiversMobileV5} from "./admin-caregivers-v5";
import {TrainingExamResultsMobile} from "./training-exam-results-v1";
import {InitialEvaluationReportV2} from "../shared/initial-evaluation-v2";

type Notify=(message:string,tone?:"success"|"error"|"info")=>void;
export function AdminCaregiversMobileV6({access,onExit,notify}:{access:any;onExit:()=>void;notify:Notify}){
 const shell=useRef<HTMLDivElement>(null),[caregiverId,setCaregiverId]=useState(""),[host,setHost]=useState<HTMLElement|null>(null),[tab,setTab]=useState<"record"|"training"|"initial">("record"),[initialAllowed,setInitialAllowed]=useState(false);
 useEffect(()=>{fetch("/api/staff/initial-evaluations/access",{credentials:"same-origin",cache:"no-store"}).then(r=>r.ok?r.json():null).then(p=>setInitialAllowed(Boolean(p?.data?.allowed))).catch(()=>setInitialAllowed(false))},[]);
 useEffect(()=>{const nativeFetch=window.fetch.bind(window);const patched:typeof window.fetch=async(input,init)=>{const raw=typeof input==="string"?input:input instanceof URL?input.toString():input.url,url=new URL(raw,location.origin);const response=await nativeFetch(input as RequestInfo|URL,init);if(response.ok&&url.origin===location.origin&&url.pathname==="/api/admin/caregiver-profile"){const id=String(url.searchParams.get("id")||"").trim();if(id){setCaregiverId(id);setTab("record")}}return response};window.fetch=patched;return()=>{if(window.fetch===patched)window.fetch=nativeFetch as typeof window.fetch}},[]);
 useEffect(()=>{const root=shell.current;if(!root)return;let current:HTMLElement|null=null;const sync=()=>{const stack=root.querySelector<HTMLElement>(".ma-caregiver-record-v4 .ma-main > .ma-stack");if(!stack){if(current?.isConnected)current.remove();current=null;setHost(null);return}if(current?.isConnected)return;const node=document.createElement("div");node.className="acv6-training-host";const profile=stack.querySelector(".ma-profile-head");profile?.insertAdjacentElement("afterend",node);if(!profile)stack.prepend(node);current=node;setHost(node)};sync();const observer=new MutationObserver(sync);observer.observe(root,{subtree:true,childList:true});return()=>{observer.disconnect();if(current?.isConnected)current.remove()}},[caregiverId]);
 const detailActive=tab!=="record";
 return <div ref={shell} className={detailActive?"acv6-shell detail-active":"acv6-shell"}><style>{`.acv6-tabs{display:flex;gap:6px;margin:2px 0 12px;padding:6px;border:1px solid #d9e8e0;border-radius:16px;background:linear-gradient(135deg,#f3faf6,#edf6f1);box-shadow:0 7px 20px rgba(18,78,49,.07);overflow-x:auto;scrollbar-width:none}.acv6-tabs::-webkit-scrollbar{display:none}.acv6-tabs button{flex:1 0 92px;min-width:0;min-height:48px;border:1px solid transparent;background:rgba(255,255,255,.9);border-radius:12px;padding:7px 5px;font:inherit;font-size:8.3px;font-weight:900;color:#486158;display:flex;flex-direction:column;align-items:center;justify-content:center;gap:4px;box-shadow:0 2px 7px rgba(18,78,49,.05);transition:transform .15s ease,box-shadow .15s ease,background .15s ease}.acv6-tabs button svg{width:16px;height:16px;color:#087443}.acv6-tabs button:active{transform:scale(.97)}.acv6-tabs button.active{background:linear-gradient(135deg,#087443,#15935a);border-color:#087443;color:#fff;box-shadow:0 7px 16px rgba(8,116,67,.22)}.acv6-tabs button.active svg{color:#fff}.acv6-shell.detail-active .ma-caregiver-record-v4 .ma-main>.ma-stack>.ma-record-facts,.acv6-shell.detail-active .ma-caregiver-record-v4 .ma-main>.ma-stack>.ma-note,.acv6-shell.detail-active .ma-caregiver-record-v4 .ma-main>.ma-stack>.caregiver-self-scorecard{display:none!important}`}</style><AdminCaregiversMobileV5 access={access} onExit={onExit} notify={notify}/>{host&&caregiverId&&createPortal(<><nav className="acv6-tabs"><button type="button" className={tab==="record"?"active":""} onClick={()=>setTab("record")}><ClipboardCheck size={16}/>پرونده و ارزیابی فنی</button><button type="button" className={tab==="training"?"active":""} onClick={()=>setTab("training")}><BookOpen size={16}/>نتایج آزمون آموزش</button>{initialAllowed&&<button type="button" className={tab==="initial"?"active":""} onClick={()=>setTab("initial")}><UserCheck size={16}/>ارزیابی بدوی</button>}</nav>{tab==="training"&&<TrainingExamResultsMobile caregiverId={caregiverId}/>} {tab==="initial"&&initialAllowed&&<InitialEvaluationReportV2 caregiverId={caregiverId}/>}</>,host)}</div>;
}
