import React,{FormEvent,useEffect,useState} from "react";
import {Clock3,Gift,Search,UsersRound} from "lucide-react";
import "./admin-financial-referrals-v3.css";

type Notify=(message:string,tone?:"success"|"error"|"info")=>void;
const fa=(v:unknown)=>Number(v||0).toLocaleString("fa-IR"),money=(v:unknown)=>`${Number(v||0).toLocaleString("fa-IR")} تومان`,text=(v:unknown,f="—")=>String(v??"").trim()||f;
const dateFa=(v:unknown)=>{if(!v)return"—";try{return new Intl.DateTimeFormat("fa-IR-u-ca-persian",{dateStyle:"medium"}).format(new Date(String(v)))}catch{return String(v)}};
async function api<T=any>(path:string):Promise<T>{const response=await fetch(path,{credentials:"same-origin",cache:"no-store"});const raw=await response.text();let payload:any={};try{payload=raw?JSON.parse(raw):{}}catch{payload={message:raw}}if(!response.ok)throw new Error(payload.message||`خطای ${response.status}`);return payload as T}
function caseLabel(x:any){const confirmation=String(x.referrerConfirmationStatus||"").toUpperCase(),s=String(x.status||"").toUpperCase();if(confirmation==="PENDING")return"در انتظار تأیید معرف";if(confirmation==="REJECTED")return"ردشده توسط معرف";if(s==="WAITING_CONTRACT")return"مرحله ثبت‌نام تکمیل؛ منتظر قرارداد";if(s==="COMPLETED")return"تکمیل‌شده";return s||"—"}

export function AdminReferralRewardsMobileV4({notify}:{access:any;notify:Notify}){
 const [data,setData]=useState<any>(null),[query,setQuery]=useState(""),[filter,setFilter]=useState("");
 const load=async()=>{try{const p:any=await api(`/api/staff/financial-credits/referrals?q=${encodeURIComponent(query)}&status=${encodeURIComponent(filter)}`);setData(p.data||{})}catch(e:any){notify(e.message,"error")}};
 useEffect(()=>{void load()},[]);
 if(!data)return <div className="ma-state"><span className="ma-spinner"/><strong>در حال دریافت سوابق معرفی...</strong></div>;
 const s=data.summary||{},rows=data.cases||[];
 return <div className="ma-stack mafr-page"><form className="mafr-search" onSubmit={(e:FormEvent)=>{e.preventDefault();void load()}}><div><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="معرف یا مراقب معرفی‌شده"/></div><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="">همه وضعیت‌ها</option><option value="PENDING_REGISTRATION_REVIEW">در انتظار تأیید معرف</option><option value="WAITING_CONTRACT">منتظر اولین قرارداد</option><option value="COMPLETED">تکمیل‌شده</option></select><button>جست‌وجو</button></form><section className="mafr-kpis"><article><small>منتظر معرف</small><strong>{fa(s.awaitingReferrer||0)}</strong></article><article><small>منتظر قرارداد</small><strong>{fa(s.waitingContract||0)}</strong></article><article><small>مرحله ثبت‌نام</small><strong>{money(s.stage1AmountToman||0)}</strong></article><article><small>مرحله قرارداد</small><strong>{money(s.stage2AmountToman||0)}</strong></article></section><section className="mafr-policy"><Gift size={20}/><div><strong>سوابق پاداش معرفی</strong><small>تصمیم تأیید یا رد توسط خود مراقب معرف ثبت می‌شود و مدیرسامانه در این صفحه سابقه مراحل و تراکنش‌های مربوط را مشاهده می‌کند.</small></div></section>{rows.length?<div className="mafr-list">{rows.map((x:any)=><article key={x.id} className="mafr-case"><header><div><strong>{text(x.referrerName,"معرف")}</strong><small>{text(x.referrerMembershipCode)} • {text(x.referrerMobile)}</small></div><span>{caseLabel(x)}</span></header><div className="mafr-person"><UsersRound size={18}/><div><strong>{text(x.referredName,"مراقب معرفی‌شده")}</strong><small>{text(x.referredMembershipCode)} • {text(x.referredMobile)}</small></div></div><div className="mafr-grid"><div><small>تأیید معرف</small><strong>{String(x.referrerConfirmationStatus).toUpperCase()==="APPROVED"?"تأیید شده":String(x.referrerConfirmationStatus).toUpperCase()==="PENDING"?"در انتظار":"رد شده"}</strong></div><div><small>وضعیت حساب</small><strong>{text(x.referredAccountStatus)}</strong></div><div><small>مرحله ثبت‌نام</small><strong>{x.registrationRewardTransactionId?money(x.registrationRewardToman):"ثبت نشده"}</strong>{x.registrationPaymentAt&&<small>{dateFa(x.registrationPaymentAt)}</small>}</div><div><small>مرحله قرارداد</small><strong>{x.contractRewardTransactionId?money(x.contractRewardToman):x.contractEligible?"در حال ثبت":"هنوز قرارداد نشده"}</strong>{x.contractPaymentAt&&<small>{dateFa(x.contractPaymentAt)}</small>}</div></div>{String(x.referrerConfirmationStatus).toUpperCase()==="PENDING"&&<footer><span className="mafr-wait"><Clock3 size={14}/>منتظر تصمیم خود معرف است.</span></footer>}</article>)}</div>:<div className="ma-state"><strong>پرونده معرفی وجود ندارد</strong><small>معرفی‌های ثبت‌شده با کد معرف اینجا نمایش داده می‌شوند.</small></div>}</div>
}
