import React,{FormEvent,useEffect,useState} from "react";
import {ArrowDownAZ,ArrowUpAZ,Gift,WalletCards} from "lucide-react";
import {AdminReferralLoanRequestsMobileV1} from "./admin-referral-loan-requests-v1";
import "./admin-financial-referrals-v3.css";

type Notify=(message:string,tone?:"success"|"error"|"info")=>void;
const fa=(v:unknown)=>Number(v||0).toLocaleString("fa-IR"),money=(v:unknown)=>`${Number(v||0).toLocaleString("fa-IR")} تومان`,text=(v:unknown,f="—")=>String(v??"").trim()||f;
const dateFa=(v:unknown)=>{if(!v)return"—";try{return new Intl.DateTimeFormat("fa-IR-u-ca-persian",{dateStyle:"medium"}).format(new Date(String(v)))}catch{return String(v)}};
async function api<T=any>(path:string):Promise<T>{const response=await fetch(path,{credentials:"same-origin",cache:"no-store"});const raw=await response.text();let payload:any={};try{payload=raw?JSON.parse(raw):{}}catch{payload={message:raw}}if(!response.ok)throw new Error(payload.message||`خطای ${response.status}`);return payload as T}

function RewardLedgerMobile({notify}:{notify:Notify}){
 const [data,setData]=useState<any>(null),[referrerId,setReferrerId]=useState(""),[from,setFrom]=useState(""),[to,setTo]=useState(""),[sort,setSort]=useState<"desc"|"asc">("desc"),[page,setPage]=useState(1);
 const load=async(nextPage=page)=>{try{const params=new URLSearchParams({page:String(nextPage),pageSize:"30",sort});if(referrerId)params.set("referrerId",referrerId);if(from)params.set("from",from);if(to)params.set("to",to);const p:any=await api(`/api/staff/financial-credits/referrals/reward-ledger?${params}`);setData(p.data||{})}catch(e:any){notify(e.message,"error")}};
 useEffect(()=>{void load(page)},[page]);
 const apply=(e:FormEvent)=>{e.preventDefault();if(page!==1)setPage(1);else void load(1)};
 if(!data)return <div className="ma-state"><span className="ma-spinner"/><strong>در حال دریافت ریز پاداش‌ها...</strong></div>;
 const rows=data.rows||[],s=data.summary||{},pagination=data.pagination||{},referrers=data.referrers||[];
 return <div className="ma-stack mafr-page"><form className="mafr-ledger-filter" onSubmit={apply}><select value={referrerId} onChange={e=>setReferrerId(e.target.value)}><option value="">همه معرف‌ها</option>{referrers.map((r:any)=><option key={r.caregiverId} value={r.caregiverId}>{text(r.fullName)} — {text(r.membershipCode)}</option>)}</select><select value={sort} onChange={e=>setSort(e.target.value as "desc"|"asc")}><option value="desc">آخرین به اولین</option><option value="asc">اولین به آخرین</option></select><input type="date" value={from} onChange={e=>setFrom(e.target.value)} title="از تاریخ"/><input type="date" value={to} onChange={e=>setTo(e.target.value)} title="تا تاریخ"/><button>اعمال فیلتر</button></form><section className="mafr-kpis"><article><small>تعداد واریزها</small><strong>{fa(s.totalRows||0)}</strong></article><article><small>جمع پاداش</small><strong>{money(s.totalAmountToman||0)}</strong></article></section><section className="mafr-policy"><Gift size={20}/><div><strong>سوابق ریز پاداش‌های معرفی</strong><small>هر واریز ۲۰۰ هزار تومانی ثبت‌نام و ۳۰۰ هزار تومانی ورود به قرارداد، از تراکنش واقعی کیف پول به‌صورت یک سطر مستقل نمایش داده می‌شود.</small></div>{sort==="desc"?<ArrowDownAZ size={18}/>:<ArrowUpAZ size={18}/>}</section>{rows.length?<div className="mafr-list">{rows.map((x:any)=><article className="mafr-case" key={x.transactionId}><header><div><strong>{text(x.referrerName,"معرف")}</strong><small>{text(x.referrerMembershipCode)} • {text(x.referrerMobile)}</small></div><span>{text(x.rewardTypeLabel)}</span></header><div className="mafr-person"><Gift size={18}/><div><strong>{text(x.referredName,"مراقب ثبت‌نام‌شده")}</strong><small>{text(x.referredMembershipCode)} • {text(x.referredMobile)}</small></div></div><div className="mafr-grid"><div><small>مبلغ پاداش</small><strong>{money(x.amountToman)}</strong></div><div><small>تاریخ ثبت‌نام</small><strong>{dateFa(x.registeredAt)}</strong></div><div><small>واریز به کیف پول</small><strong>{dateFa(x.creditedAt)}</strong></div><div><small>شناسه تراکنش</small><strong>{text(x.transactionId)}</strong></div></div></article>)}</div>:<div className="ma-state"><strong>پاداشی با این فیلتر پیدا نشد</strong></div>}<div className="mafr-pager"><button type="button" disabled={Number(pagination.page||1)<=1} onClick={()=>setPage(p=>Math.max(1,p-1))}>قبلی</button><span>{fa(pagination.page||1)} / {fa(pagination.totalPages||1)}</span><button type="button" disabled={Number(pagination.page||1)>=Number(pagination.totalPages||1)} onClick={()=>setPage(p=>p+1)}>بعدی</button></div></div>;
}

export function AdminReferralRewardsMobileV4({notify}:{access:any;notify:Notify}){
 const [tab,setTab]=useState<"rewards"|"loans">("rewards");
 return <div className="ma-stack"><style>{`.mafr-referral-subtabs{display:grid;grid-template-columns:1fr 1fr;gap:6px;padding:5px;border:1px solid #dfeae4;border-radius:14px;background:#fff}.mafr-referral-subtabs button{min-height:40px;border:0;border-radius:10px;background:transparent;color:#5c7066;font:inherit;font-size:8px;font-weight:900;display:flex;align-items:center;justify-content:center;gap:5px}.mafr-referral-subtabs button.active{background:#e7f6ed;color:#087443}.mafr-ledger-filter{display:grid;grid-template-columns:1fr 1fr;gap:7px;padding:8px;border:1px solid #dfeae4;border-radius:15px;background:#fff}.mafr-ledger-filter input,.mafr-ledger-filter select{min-width:0;width:100%;height:38px;border:1px solid #d9e5df;border-radius:10px;padding:0 7px;background:#fff;font:inherit;font-size:8px}.mafr-ledger-filter button{grid-column:1/-1;height:38px;border:0;border-radius:10px;background:#087443;color:#fff;font:inherit;font-size:8px;font-weight:900}.mafr-pager{display:flex;align-items:center;justify-content:center;gap:9px;padding:8px}.mafr-pager button{border:1px solid #d9e5df;border-radius:9px;background:#fff;color:#087443;padding:7px 12px;font:inherit;font-size:8px;font-weight:900}.mafr-pager button:disabled{opacity:.4}.mafr-pager span{font-size:8px;color:#65776e}`}</style><nav className="mafr-referral-subtabs"><button type="button" className={tab==="rewards"?"active":""} onClick={()=>setTab("rewards")}><Gift size={15}/>ریز پاداش‌ها</button><button type="button" className={tab==="loans"?"active":""} onClick={()=>setTab("loans")}><WalletCards size={15}/>درخواست‌های وام</button></nav>{tab==="rewards"?<RewardLedgerMobile notify={notify}/>:<AdminReferralLoanRequestsMobileV1 notify={notify}/>}</div>;
}
