import React,{FormEvent,useEffect,useState} from "react";
import {ArrowRight,ChevronLeft,ClipboardCheck,Plus,Search} from "lucide-react";
import {EvaluationAnalysis,GoldStars} from "../desktop-react/evaluation-insights-v1";
import "./admin.css";
import "../desktop-react/caregiver-activity-scorecard.css";

type Notify=(message:string,tone?:"success"|"error"|"info")=>void;
const text=(value:unknown,fallback="—")=>String(value??"").trim()||fallback;
const fa=(value:unknown)=>Number(value||0).toLocaleString("fa-IR");
const statusFa:Record<string,string>={ACTIVE:"فعال",APPROVED:"فعال",PENDING:"در انتظار",SUSPENDED:"تعلیق",INACTIVE:"غیرفعال",FINAL:"نهایی",DRAFT:"در حال ارزیابی"};
const status=(value:unknown)=>statusFa[String(value||"").toUpperCase()]||text(value);
const dateFa=(value:unknown)=>{if(!value)return"—";try{return new Intl.DateTimeFormat("fa-IR-u-ca-persian",{dateStyle:"medium"}).format(new Date(String(value)))}catch{return String(value)}};
const initials=(name:unknown)=>text(name,"م").split(/\s+/).filter(Boolean).map(x=>x[0]).join("").slice(0,2)||"م";
async function api<T=any>(path:string,options:RequestInit={}):Promise<T>{const headers=new Headers(options.headers||{});if(typeof options.body==="string"&&!headers.has("content-type"))headers.set("content-type","application/json");const response=await fetch(path,{credentials:"same-origin",cache:"no-store",...options,headers});const raw=await response.text();let payload:any={};try{payload=raw?JSON.parse(raw):{}}catch{payload={detail:raw}}if(!response.ok)throw new Error(payload.message||`خطای ${response.status}`);return payload as T}
function Loading({label="در حال دریافت اطلاعات..."}:{label?:string}){return <div className="ma-state"><span className="ma-spinner"/><strong>{label}</strong></div>}
function ErrorBox({message,retry}:{message:string;retry?:()=>void}){return <div className="ma-state error"><strong>دریافت اطلاعات انجام نشد</strong><small>{message}</small>{retry&&<button className="ma-btn primary" onClick={retry}>تلاش مجدد</button>}</div>}
function Empty({title,description}:{title:string;description:string}){return <div className="ma-state"><strong>{title}</strong><small>{description}</small></div>}
function BackHeader({title,onBack}:{title:string;onBack:()=>void}){return <header className="mae-mobile-head"><button onClick={onBack}><ArrowRight size={20}/></button><strong>{title}</strong><span/></header>}

function EvaluationScorecard({scorecard}:{scorecard:any}){
 const summary=scorecard?.summary||{},rank=scorecard?.rank||{},analysis=scorecard?.analysis||null,indicators=Array.isArray(scorecard?.indicators)?scorecard.indicators:[],history=Array.isArray(scorecard?.history)?scorecard.history:[];
 return <div className="cs-card-stack ma-caregiver-scorecard">
  <section className="ma-card"><div className="cs-section-head"><div><span className="cs-icon"><ClipboardCheck size={18}/></span><div><h3>کارنامه ارزیابی</h3><p>{text(summary.notice,"آخرین اطلاعات نظام ارزیابی")}</p></div></div><strong>{summary.official?"رسمی":"غیرنهایی"}</strong></div><div className="ma-detail-grid compact"><div><span>امتیاز حرفه‌ای</span><strong>{summary.score==null?"—":`${fa(summary.score)} از ۱۰۰`}</strong></div><div><span>رده حرفه‌ای</span><strong>{text(rank.title,"در انتظار ارزیابی")}</strong></div></div><GoldStars stars={rank.stars}/></section>
  {analysis&&<section className="ma-card"><EvaluationAnalysis analysis={analysis}/></section>}
  <section className="ma-card"><div className="cs-section-head"><div><span className="cs-icon"><ClipboardCheck size={18}/></span><div><h3>شاخص‌های کارنامه</h3><p>{fa(summary.scoredCriteria||0)} از {fa(summary.totalCriteria||0)} معیار امتیاز دارد.</p></div></div></div><div className="cs-indicator-grid">{indicators.map((ind:any)=><article key={ind.code} className={ind.complete?"complete":""}><div><span>{ind.code}</span><strong>{text(ind.title,"شاخص")}</strong></div><span className="cs-score">{ind.score??ind.liveScore==null?"—":fa(ind.score??ind.liveScore)}</span><small>{fa(ind.scoredCount||0)} از {fa(ind.criteriaCount||0)} معیار</small></article>)}</div></section>
  {history.length>0&&<section className="ma-card"><div className="cs-section-head"><div><span className="cs-icon"><ClipboardCheck size={18}/></span><div><h3>تاریخچه کارنامه</h3><p>دوره‌های ارزیابی ثبت‌شده</p></div></div></div><div className="ma-mini-list static">{history.slice(0,8).map((row:any)=><div key={row.id}><strong>{text(row.title,"دوره ارزیابی")}</strong><small>{status(row.status)} • امتیاز {row.finalScore==null?"—":fa(row.finalScore)} • {dateFa(row.finalizedAt||row.updatedAt)}</small></div>)}</div></section>}
 </div>
}

export function AdminCaregiversMobileV3({access,onExit,notify}:{access:any;onExit:()=>void;notify:Notify}){
 const [rows,setRows]=useState<any[]>([]),[pagination,setPagination]=useState<any>({}),[page,setPage]=useState(1),[query,setQuery]=useState(""),[loading,setLoading]=useState(true),[error,setError]=useState(""),[detail,setDetail]=useState<any>(null),[create,setCreate]=useState(false);
 const canCreate=Boolean((access?.allModules||access?.modules||[]).find((m:any)=>m.key==="staff.caregivers")?.actions?.create);
 const load=async(next=page,q=query)=>{setLoading(true);setError("");try{const params=new URLSearchParams({page:String(next),pageSize:"25"});if(q.trim())params.set("q",q.trim());const p:any=await api(`/api/admin/caregivers-page?${params}`),d=p.data||{};setRows(Array.isArray(d.items)?d.items:[]);setPagination(d.pagination||{});setPage(next)}catch(e:any){setRows([]);setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{void load(1,"")},[]);
 const open=async(item:any)=>{setDetail({loading:true,item});try{const [record,profile,scorecard]=await Promise.allSettled([api<any>(`/api/admin/caregiver-record?id=${encodeURIComponent(item.id)}`),api<any>(`/api/admin/caregiver-profile?id=${encodeURIComponent(item.id)}`),api<any>(`/api/admin/caregiver-scorecard-v2?caregiverId=${encodeURIComponent(item.id)}`)]);setDetail({item,record:record.status==="fulfilled"?record.value.data:null,profile:profile.status==="fulfilled"?profile.value.data:null,scorecard:scorecard.status==="fulfilled"?scorecard.value.data:null,scoreError:scorecard.status==="rejected"?scorecard.reason?.message:""})}catch(e:any){setDetail({item,error:e.message})}};
 const submitCreate=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const body=Object.fromEntries(new FormData(e.currentTarget).entries());try{await api("/api/caregivers",{method:"POST",body:JSON.stringify({...body,serviceGroup:body.primaryType,bio:body.workHistory})});notify("پرونده مراقب ایجاد شد.","success");setCreate(false);await load(1,"")}catch(x:any){notify(x.message,"error")}};
 if(create)return <div className="ma-app"><BackHeader title="ایجاد پرونده مراقب" onBack={()=>setCreate(false)}/><main className="ma-main"><form className="ma-form" onSubmit={submitCreate}><div className="ma-form-grid"><label><span>نام و نام خانوادگی</span><input name="fullName" required/></label><label><span>شماره همراه</span><input name="mobile" inputMode="tel" required/></label><label><span>کد ملی</span><input name="nationalId" inputMode="numeric"/></label><label><span>گروه خدمتی</span><input name="primaryType" defaultValue="مراقبت سالمند"/></label><label><span>شهر</span><input name="city"/></label><label><span>وضعیت پرونده</span><input name="fileStatus" defaultValue="CP-03 نیازمند تکمیل مدارک"/></label><label className="wide"><span>نشانی</span><textarea name="address"/></label><label className="wide"><span>سوابق</span><textarea name="workHistory"/></label></div><button className="ma-save">ثبت پرونده</button></form></main></div>;
 if(detail)return <div className="ma-app"><BackHeader title="پرونده و کارنامه مراقب" onBack={()=>setDetail(null)}/><main className="ma-main">{detail.loading?<Loading label="در حال ساخت کارنامه مراقب..."/>:detail.error?<ErrorBox message={detail.error}/>:<div className="ma-stack"><section className="ma-profile-head"><span className="ma-person-avatar large">{detail.scorecard?.caregiver?.avatarUrl?<img src={detail.scorecard.caregiver.avatarUrl} alt=""/>:initials(detail.item.fullName)}</span><div><h2>{text(detail.profile?.fullName||detail.item.fullName,"مراقب")}</h2><p>{text(detail.profile?.membershipCode||detail.item.membershipCode||detail.item.id)} • {text(detail.profile?.mobile||detail.item.mobile)}</p></div></section><section className="ma-card"><div className="ma-detail-grid">{[["کد ملی",detail.profile?.nationalId||detail.record?.nationalId],["گروه خدمتی",detail.profile?.primaryType||detail.record?.primaryType||detail.item.primaryType],["وضعیت پرونده",detail.profile?.fileStatus||detail.record?.fileStatus||detail.item.fileStatus],["سطح حرفه‌ای",detail.scorecard?.rank?.title||detail.record?.professionalLevel||detail.item.professionalLevel],["منطقه فعالیت",detail.profile?.activityRegion||detail.record?.activityRegion],["وضعیت همکاری",detail.record?.cooperationStatus]].map(([key,value])=><div key={String(key)}><span>{key}</span><strong>{text(value)}</strong></div>)}</div></section>{detail.scorecard?<EvaluationScorecard scorecard={detail.scorecard}/>:<ErrorBox message={detail.scoreError||"کارنامه ارزیابی این مراقب دریافت نشد."}/>}</div>}</main></div>;
 const totalPages=Number(pagination.totalPages||pagination.pages||1),total=Number(pagination.total||rows.length);
 return <div className="ma-app"><BackHeader title="پرونده مراقبین" onBack={onExit}/><main className="ma-main"><div className="ma-mobile-toolbar"><form onSubmit={e=>{e.preventDefault();void load(1,query)}}><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="نام، موبایل، کد ملی یا پرونده"/></form>{canCreate&&<button onClick={()=>setCreate(true)}><Plus size={19}/></button>}</div>{error?<ErrorBox message={error} retry={()=>load(page,query)}/>:loading?<Loading/>:<><div className="ma-user-list">{rows.map((item:any)=><button className="ma-person" key={item.id} onClick={()=>void open(item)}><span className="ma-person-avatar">{item.avatarUrl?<img src={item.avatarUrl} alt=""/>:initials(item.fullName)}</span><span><strong>{text(item.fullName)}</strong><small>{text(item.membershipCode||item.id)} • {text(item.mobile)}</small></span><span className="ma-row-end"><small>{text(item.professionalLevel||item.primaryType,"کارنامه")}</small><ChevronLeft size={18}/></span></button>)}</div><div className="ma-pager"><button disabled={page<=1} onClick={()=>void load(page-1,query)}>قبلی</button><span>{fa(total)} پرونده • {fa(page)} از {fa(totalPages)}</span><button disabled={page>=totalPages} onClick={()=>void load(page+1,query)}>بعدی</button></div></>}</main></div>
}
