import React,{useEffect,useRef,useState} from "react";
import {createPortal} from "react-dom";
import {AdminCaregiversMobileV5} from "./admin-caregivers-v5";
import {TrainingExamResultsMobile} from "./training-exam-results-v1";
import {InitialEvaluationReportV2} from "../shared/initial-evaluation-v2";

type Notify=(message:string,tone?:"success"|"error"|"info")=>void;
export function AdminCaregiversMobileV6({access,onExit,notify}:{access:any;onExit:()=>void;notify:Notify}){
 const shell=useRef<HTMLDivElement>(null),[caregiverId,setCaregiverId]=useState(""),[host,setHost]=useState<HTMLElement|null>(null),[tab,setTab]=useState<"record"|"training"|"initial">("record"),[initialAllowed,setInitialAllowed]=useState(false);
 useEffect(()=>{fetch("/api/staff/initial-evaluations/access",{credentials:"same-origin",cache:"no-store"}).then(r=>r.ok?r.json():null).then(p=>setInitialAllowed(Boolean(p?.data?.allowed))).catch(()=>setInitialAllowed(false))},[]);
 useEffect(()=>{const nativeFetch=window.fetch.bind(window);const patched:typeof window.fetch=async(input,init)=>{const raw=typeof input==="string"?input:input instanceof URL?input.toString():input.url,url=new URL(raw,location.origin);const response=await nativeFetch(input as RequestInfo|URL,init);if(response.ok&&url.origin===location.origin&&url.pathname==="/api/admin/caregiver-profile"){const id=String(url.searchParams.get("id")||"").trim();if(id){setCaregiverId(id);setTab("record")}}return response};window.fetch=patched;return()=>{if(window.fetch===patched)window.fetch=nativeFetch as typeof window.fetch}},[]);
 useEffect(()=>{const root=shell.current;if(!root)return;let current:HTMLElement|null=null;const sync=()=>{const stack=root.querySelector<HTMLElement>(".ma-caregiver-record-v4 .ma-main > .ma-stack");if(!stack){if(current?.isConnected)current.remove();current=null;setHost(null);return}if(current?.isConnected)return;const node=document.createElement("div");node.className="acv6-training-host";const profile=stack.querySelector(".ma-profile-head");profile?.insertAdjacentElement("afterend",node);if(!profile)stack.prepend(node);current=node;setHost(node)};sync();const observer=new MutationObserver(sync);observer.observe(root,{subtree:true,childList:true});return()=>{observer.disconnect();if(current?.isConnected)current.remove()}},[caregiverId]);
 const detailActive=tab!=="record";
 return <div ref={shell} className={detailActive?"acv6-shell detail-active":"acv6-shell"}><style>{`.acv6-tabs{display:flex;gap:5px;margin:0 0 10px}.acv6-tabs button{flex:1;min-width:0;border:1px solid #d9e6df;background:#fff;border-radius:11px;padding:8px 4px;font:inherit;font-size:9px;font-weight:900;color:#486158}.acv6-tabs button.active{background:#087443;border-color:#087443;color:#fff}.acv6-shell.detail-active .ma-caregiver-record-v4 .ma-main>.ma-stack>.ma-record-facts,.acv6-shell.detail-active .ma-caregiver-record-v4 .ma-main>.ma-stack>.ma-note,.acv6-shell.detail-active .ma-caregiver-record-v4 .ma-main>.ma-stack>.caregiver-self-scorecard{display:none!important}`}</style><AdminCaregiversMobileV5 access={access} onExit={onExit} notify={notify}/>{host&&caregiverId&&createPortal(<><nav className="acv6-tabs"><button type="button" className={tab==="record"?"active":""} onClick={()=>setTab("record")}>پرونده و ارزیابی فنی</button><button type="button" className={tab==="training"?"active":""} onClick={()=>setTab("training")}>آزمون آموزش</button>{initialAllowed&&<button type="button" className={tab==="initial"?"active":""} onClick={()=>setTab("initial")}>ارزیابی بدوی</button>}</nav>{tab==="training"&&<TrainingExamResultsMobile caregiverId={caregiverId}/>} {tab==="initial"&&initialAllowed&&<InitialEvaluationReportV2 caregiverId={caregiverId}/>}</>,host)}</div>;
}
