import React,{useEffect,useMemo,useState} from "react";
import {BadgeCheck,CheckCircle2,Clock3,Gift,Landmark,ShieldCheck,TrendingUp,UsersRound,XCircle} from "lucide-react";
import {api,Card,dateFa,Empty,ErrorState,fa,Loading,money,status,text} from "./caregiver-core-v2";
import "./caregiver-benefits-v3.css";
import "./caregiver-loan-pies-v1.css";

type BenefitTab="loans"|"rewards"|"referrals"|"requests";
const LOAN_KEYS=new Set(["POINT_LOAN_200","POINT_LOAN_400","POINT_LOAN_600","POINT_LOAN_800"]);
const pct=(v:unknown)=>Math.max(0,Math.min(100,Number(v||0)));
const rewardStatus:Record<string,string>={WAITING_FRANCHISE:"منتظر ثبت فرانشیز",PENDING_APPROVAL:"در انتظار تأیید مدیر",PAID:"پرداخت شده",REJECTED:"رد شده"};
const requestStatus:Record<string,string>={REQUESTED:"در انتظار بررسی",UNDER_REVIEW:"در حال بررسی",APPROVED:"تأیید شده",REJECTED:"رد شده",CANCELLED:"لغو شده"};
const referralStatus:Record<string,string>={WAITING_REFERRER_CONFIRMATION:"منتظر تأیید شما",PENDING_REGISTRATION_REVIEW:"منتظر بررسی مدیر",WAITING_CONTRACT:"منتظر اولین قرارداد",COMPLETED:"تکمیل شده",REFERRER_REJECTED:"رد شده توسط شما",REGISTRATION_REJECTED:"رد مرحله ثبت‌نام"};

function LoanProgressChart({points}:{points:number}){
 const milestones=[{points:200,label:"۱۰ میلیون تومان"},{points:400,label:"۲۵ میلیون تومان"},{points:600,label:"۵۰ میلیون تومان"},{points:800,label:"۷۰ میلیون تومان"}];
 return <section className="cb3-loan-pie-card"><header><div><strong>امتیازشمار پله‌های وام</strong><small>هر دایره درصد تکمیل همان پله را بر اساس امتیاز قرارداد نشان می‌دهد.</small></div><b>{fa(points)} امتیاز فعلی</b></header><div className="cb3-loan-pie-grid">{milestones.map((m,index)=>{const progress=pct(points/m.points*100),done=points>=m.points,current=Math.max(0,Math.min(points,m.points)),remaining=Math.max(0,m.points-points);return <article key={m.points} className={`cb3-loan-pie-step ${done?"done":""}`}><div className="cb3-loan-pie" style={{background:`conic-gradient(#087443 ${progress}%,#e6ece8 ${progress}% 100%)`}}><div className="cb3-loan-pie-core">{done?<CheckCircle2 size={18}/>:<strong>{fa(progress)}٪</strong>}<small>{fa(current)} / {fa(m.points)}</small></div></div><div className="cb3-loan-pie-meta"><span>پله {fa(index+1)}</span><strong>{fa(m.points)} امتیاز</strong><small>{m.label}</small><em>{done?"تکمیل شده":`${fa(remaining)} امتیاز تا این پله`}</em></div></article>})}</div></section>
}

function Gate({ok,title,value,caption}:{ok:boolean;title:string;value:string;caption:string}){return <article className={`cb3-gate ${ok?"ok":"wait"}`}>{ok?<CheckCircle2 size={21}/>:<Clock3 size={21}/>}<div><strong>{title}</strong><span>{value}</span><small>{caption}</small></div></article>}

function LoansTab({profile,reload,setTab}:{profile:any;reload:()=>Promise<void>;setTab:(tab:BenefitTab)=>void}){
 const [busy,setBusy]=useState(""),[message,setMessage]=useState("");const policy=profile.loanPolicy||{},points=Number(policy.totalPoints??profile.contractPoints?.totalPoints??0),evaluation=policy.evaluation||{},average=evaluation.averageScore==null?null:Number(evaluation.averageScore),threshold=Number(policy.minimumEvaluationScore||60),tiers=Array.isArray(policy.tiers)?policy.tiers:(profile.loans||[]),requests=profile.wallet?.creditRequests||[],open=requests.find((x:any)=>["REQUESTED","UNDER_REVIEW","APPROVED"].includes(String(x.status||"")));
 const request=async(tier:any)=>{setBusy(tier.key);setMessage("");try{await api("/api/caregiver/platform/credit-requests",{method:"POST",body:JSON.stringify({benefitKey:tier.key,note:`درخواست ${tier.title} بر اساس امتیاز قرارداد و ارزیابی`})});setMessage("درخواست وام ثبت شد و برای بررسی مدیر سامانه ارسال شد.");await reload();setTab("requests")}catch(e:any){setMessage(e.message||"ثبت درخواست وام انجام نشد.")}finally{setBusy("")}};
 return <div className="cb3-panel"><LoanProgressChart points={points}/><div className="cb3-gates"><Gate ok={points>=200} title="شرط امتیاز قرارداد" value={`${fa(points)} امتیاز`} caption="پله اول از ۲۰۰ امتیاز آغاز می‌شود."/><Gate ok={average!==null&&average>=threshold} title="شرط ارزیابی" value={average===null?"بدون ارزیابی نهایی":`${fa(average)} از ۱۰۰`} caption={`میانگین شاخص‌های آخرین ارزیابی نهایی نباید از ${fa(threshold)} کمتر باشد.`}/></div><Card className="cb3-policy-note"><ShieldCheck size={20}/><div><strong>قانون واحد درخواست و تأیید</strong><p>برای فعال‌شدن هر پله، هم امتیاز قرارداد آن پله باید تأمین شود و هم میانگین شاخص‌های آخرین ارزیابی نهایی حداقل ۶۰ باشد. مدیر سامانه هنگام تأیید دوباره همین دو شرط را کنترل می‌کند.</p></div></Card><div className="cb3-tier-grid">{tiers.map((tier:any)=>{const req=requests.find((x:any)=>String(x.eligibilityPath)===String(tier.key)&&["REQUESTED","UNDER_REVIEW","APPROVED"].includes(String(x.status))),pointsOk=Boolean(tier.requirements?.points?.passed??points>=Number(tier.targetPoints||0)),evalOk=Boolean(tier.requirements?.evaluation?.passed??(average!==null&&average>=threshold));return <article key={tier.key} className={`cb3-tier ${tier.eligible?"eligible":""}`}><header><Landmark size={21}/><div><strong>{text(tier.title)}</strong><small>{money(tier.amountToman)}</small></div>{tier.eligible?<span>واجد شرایط</span>:<span className="muted">در مسیر</span>}</header><div className="cb3-tier-checks"><span className={pointsOk?"ok":""}>{pointsOk?<CheckCircle2 size={15}/>:<Clock3 size={15}/>} {fa(points)} / {fa(tier.targetPoints)} امتیاز</span><span className={evalOk?"ok":""}>{evalOk?<CheckCircle2 size={15}/>:<Clock3 size={15}/>} ارزیابی {average===null?"—":fa(average)} / {fa(threshold)}</span></div><button disabled={!tier.eligible||Boolean(open)||Boolean(busy)} onClick={()=>void request(tier)}>{busy===tier.key?"در حال ثبت...":req?requestStatus[String(req.status)]||status(req.status):open?"یک درخواست باز دارید":tier.eligible?"درخواست این وام":"شرایط کامل نشده"}</button></article>})}</div>{message&&<div className="cb3-message">{message}</div>}</div>
}

function RewardsTab({profile}:{profile:any}){const rr=profile.retentionRewards||{},policy=rr.policy||{},first=rr.firstContract||null,rewards=rr.rewards||[],continuity=rr.continuity||{},firstRule=policy.firstContractRetention||{minimumDays:60,rewardToman:1_000_000};return <div className="cb3-panel"><section className="cb3-reward-hero"><Gift size={28}/><div><strong>پاداش ماندگاری در شبکه</strong><p>این بخش مستقل از وام است و مبلغ پاداش به کیف پول شما واریز می‌شود.</p></div></section><div className="cb3-reward-grid"><article><header><span>۱</span><div><strong>پاداش اولین قرارداد</strong><small>{money(firstRule.rewardToman||1_000_000)}</small></div></header>{first?<><div className="cb3-progress"><span style={{width:`${pct(Number(first.serviceDays||0)/Number(first.minimumDays||60)*100)}%`}}/></div><p>{fa(first.serviceDays||0)} روز از حداقل {fa(first.minimumDays||60)} روز در اولین قرارداد</p><small>قرارداد: {text(first.contractNumber)} • {status(first.status)}</small>{first.reward&&<b className={`cb3-reward-state ${String(first.reward.status).toLowerCase()}`}>{rewardStatus[String(first.reward.status)]||status(first.reward.status)}</b>}</>:<p>هنوز اولین قرارداد در سامانه ثبت نشده است.</p>}</article><article><header><span>۲</span><div><strong>پاداش تداوم قراردادها</strong><small>از ورود به قرارداد چهارم</small></div></header><div className="cb3-rate-row"><b>قرارداد ۴</b><span>۸٪ فرانشیز قرارداد ۱</span></div><div className="cb3-rate-row"><b>قرارداد ۵</b><span>۱۱٪ فرانشیز قرارداد ۲</span></div><div className="cb3-rate-row"><b>قرارداد ۶ به بعد</b><span>۱۵٪ فرانشیز قرارداد سه پله قبل</span></div><p>برای هر پله باید سه قرارداد بلافاصله قبل از آن با موفقیت تکمیل شده باشند.</p><small>{fa(continuity.workedCount||0)} قرارداد فعال/تکمیل‌شده در سابقه فعلی</small></article></div><Card><div className="mr-card-head"><div><h3>سوابق پاداش ماندگاری</h3><p>پرونده‌های واجد شرایط، در انتظار تأیید و پرداخت‌شده</p></div></div>{rewards.length?<div className="cb3-reward-list">{rewards.map((item:any)=><article key={item.id}><div><strong>{item.rewardType==="FIRST_CONTRACT_RETENTION"?"ماندگاری اولین قرارداد":`پاداش ورود به قرارداد ${fa(item.targetContractSequence)}`}</strong><small>{item.rewardType==="FIRST_CONTRACT_RETENTION"?`${fa(item.serviceDays)} روز ماندگاری`:`${fa(item.rateBasisPoints/100)}٪ فرانشیز قرارداد ${fa(item.sourceContractSequence)}`}</small></div><div><b>{item.rewardToman?money(item.rewardToman):"منتظر فرانشیز"}</b><span>{rewardStatus[String(item.status)]||status(item.status)}</span></div></article>)}</div>:<Empty title="هنوز پاداشی وارد صف نشده" description="با رسیدن به شرط دو ماه در قرارداد اول یا تداوم سه قرارداد متوالی، پاداش در این بخش ظاهر می‌شود."/>}</Card></div>}

function ReferralsTab({profile,reload}:{profile:any;reload:()=>Promise<void>}){const [busy,setBusy]=useState(""),[message,setMessage]=useState("");const referrals=profile.referrals||{},summary=referrals.summary||{},cases=referrals.cases||[],code=profile.caregiver?.referralCode;const decide=async(id:string,action:"CONFIRM"|"REJECT")=>{setBusy(`${id}:${action}`);setMessage("");try{await api(`/api/caregiver/platform/referrals/${encodeURIComponent(id)}`,{method:"PATCH",body:JSON.stringify({action})});setMessage(action==="CONFIRM"?"معرفی تأیید شد. پس از فعال‌شدن حساب فرد معرفی‌شده، پاداش ثبت‌نام برای تأیید مدیر سامانه وارد صف می‌شود.":"معرفی رد شد.");await reload()}catch(e:any){setMessage(e.message||"ثبت تصمیم انجام نشد.")}finally{setBusy("")}};return <div className="cb3-panel"><Card><div className="mr-card-head"><div><h3>کد معرفی من</h3><p>پاداش معرفی از وام و پاداش ماندگاری مستقل است.</p></div><span className="mr-pill">{text(code)}</span></div><div className="cb3-ref-kpis"><div><span>کل معرفی‌ها</span><strong>{fa(summary.totalReferrals||0)}</strong></div><div><span>منتظر تأیید شما</span><strong>{fa(summary.awaitingMyConfirmation||0)}</strong></div><div><span>پاداش قطعی</span><strong>{money(summary.confirmedRewardToman||0)}</strong></div></div></Card>{message&&<div className="cb3-message">{message}</div>}<Card><div className="mr-card-head"><h3>تاریخچه معرفی‌ها</h3></div>{cases.length?<div className="cb3-ref-list">{cases.map((item:any)=>{const effective=item.effectiveStatus||item.status,pending=String(item.referrerConfirmationStatus||"").toUpperCase()==="PENDING";return <article key={item.id}><div><strong>{text(item.referredName,"مراقب معرفی‌شده")}</strong><small>{text(item.referredMembershipCode)} • {dateFa(item.createdAt)}</small><span>{referralStatus[String(effective)]||status(effective)}</span></div><div className="cb3-ref-money"><small>ثبت‌نام: {item.registrationRewardTransactionId?money(item.registrationRewardToman):"—"}</small><small>اولین قرارداد: {item.contractRewardTransactionId?money(item.contractRewardToman):"—"}</small></div>{pending&&<footer><button disabled={Boolean(busy)} onClick={()=>void decide(item.id,"CONFIRM")}><BadgeCheck size={15}/>تأیید می‌کنم</button><button className="danger" disabled={Boolean(busy)} onClick={()=>void decide(item.id,"REJECT")}><XCircle size={15}/>رد</button></footer>}</article>})}</div>:<Empty title="هنوز معرفی ثبت نشده" description="وقتی فردی با کد شما ثبت‌نام کند، پرونده معرفی در اینجا نمایش داده می‌شود."/>}</Card></div>}

function RequestsTab({profile}:{profile:any}){const requests=profile.wallet?.creditRequests||[];return <div className="cb3-panel"><Card><div className="mr-card-head"><div><h3>درخواست‌های وام</h3><p>تأیید مدیر نیز با امتیاز قرارداد و حداقل ارزیابی ۶۰ کنترل می‌شود.</p></div></div>{requests.length?<div className="cb3-request-list">{requests.map((item:any)=>{const current=LOAN_KEYS.has(String(item.eligibilityPath));return <article key={item.id}><Landmark size={18}/><div><strong>{text(item.eligibilitySnapshot?.benefitTitle||item.eligibilityPath,"درخواست وام")}</strong><small>{money(item.requestedAmountToman)} • {dateFa(item.createdAt)}</small>{!current&&<em>درخواست مربوط به سیاست قبلی؛ برای تأیید نیازمند درخواست جدید است.</em>}{item.decisionNote&&<p>دلیل تصمیم: {text(item.decisionNote)}</p>}</div><span>{requestStatus[String(item.status)]||status(item.status)}</span></article>})}</div>:<Empty title="درخواست وامی ثبت نشده" description="وقتی هر دو شرط امتیاز و ارزیابی کامل شود، از تب وام می‌توانید درخواست ثبت کنید."/>}</Card></div>}

export function BenefitsPage(){const [profile,setProfile]=useState<any>(null),[tab,setTab]=useState<BenefitTab>("loans"),[error,setError]=useState("");const load=async()=>{setError("");try{const p:any=await api("/api/caregiver/platform/financial-profile");setProfile(p.data);if(Number(p.data?.referrals?.summary?.awaitingMyConfirmation||0)>0)setTab("referrals")}catch(e:any){setError(e.message)}};useEffect(()=>{void load()},[]);const counts=useMemo(()=>({referrals:Number(profile?.referrals?.summary?.awaitingMyConfirmation||0),rewards:Number(profile?.retentionRewards?.summary?.pendingApproval||0)+Number(profile?.retentionRewards?.summary?.waitingFranchise||0),requests:(profile?.wallet?.creditRequests||[]).filter((x:any)=>["REQUESTED","UNDER_REVIEW"].includes(String(x.status))).length}),[profile]);if(error)return <ErrorState message={error} retry={load}/>;if(!profile)return <Loading label="در حال دریافت مزایا..."/>;return <div className="mr-stack cb3-benefits"><Card className="cb3-head"><div><span>مزایای مالی سلامت اول</span><h2>وام و پاداش، با دو منطق مستقل</h2><p>وام فقط با امتیاز قرارداد و میانگین ارزیابی محاسبه می‌شود؛ پاداش ماندگاری مسیر جداگانه دارد.</p></div><TrendingUp size={34}/></Card><Card className="cb3-tabs-card"><nav className="cb3-tabs"><button className={tab==="loans"?"active":""} onClick={()=>setTab("loans")}><Landmark size={17}/>وام و تسهیلات</button><button className={tab==="rewards"?"active":""} onClick={()=>setTab("rewards")}><Gift size={17}/>پاداش‌ها{counts.rewards>0&&<b>{fa(counts.rewards)}</b>}</button><button className={tab==="referrals"?"active":""} onClick={()=>setTab("referrals")}><UsersRound size={17}/>معرفی‌ها{counts.referrals>0&&<b>{fa(counts.referrals)}</b>}</button><button className={tab==="requests"?"active":""} onClick={()=>setTab("requests")}><BadgeCheck size={17}/>درخواست‌ها{counts.requests>0&&<b>{fa(counts.requests)}</b>}</button></nav>{tab==="loans"&&<LoansTab profile={profile} reload={load} setTab={setTab}/>} {tab==="rewards"&&<RewardsTab profile={profile}/>} {tab==="referrals"&&<ReferralsTab profile={profile} reload={load}/>} {tab==="requests"&&<RequestsTab profile={profile}/>}</Card></div>}