import React,{useEffect,useMemo,useRef,useState} from "react";
import {BadgeCheck,ChevronLeft,ExternalLink} from "lucide-react";
import {api,Card,Empty,ErrorState,fa,Loading,Notify,pct,status,text} from "./caregiver-core-v2";

export const TRAINING_CATEGORIES=[
 {key:"club",label:"باشگاه مراقبین سلامت اول",aliases:["باشگاه مراقبین سلامت اول","باشگاه مراقبین","باشگاه","عمومی","آموزش سازمانی"]},
 {key:"pre_dispatch",label:"پیش از اعزام",aliases:["پیش از اعزام","پیش‌از اعزام","مصاحبه","اعزام آزمایشی"]},
 {key:"during_dispatch",label:"آموزش‌های حین اعزام",aliases:["آموزش‌های حین اعزام","آموزش های حین اعزام","حین اعزام"]},
 {key:"in_contract_refresh",label:"بازآموزی‌های در قرارداد",aliases:["بازآموزی‌های در قرارداد","بازآموزی های در قرارداد","بازآموزی در قرارداد","بازآموزی"]},
 {key:"specialized",label:"آموزش‌های تخصصی",aliases:["آموزش‌های تخصصی","آموزش های تخصصی","تخصصی"]},
] as const;

type CategoryKey=(typeof TRAINING_CATEGORIES)[number]["key"];
const normalize=(value:unknown)=>String(value??"").trim().replace(/ي/g,"ی").replace(/ك/g,"ک").replace(/\s+/g," ");
export function trainingCategoryOf(value:unknown):CategoryKey{
 const raw=normalize(value);
 const exact=TRAINING_CATEGORIES.find(c=>c.aliases.some(alias=>normalize(alias)===raw));
 if(exact)return exact.key;
 if(/اعزام/.test(raw)&&!/پیش/.test(raw))return "during_dispatch";
 if(/قرارداد|بازآموز/.test(raw))return "in_contract_refresh";
 if(/تخصص/.test(raw))return "specialized";
 return "club";
}
function isNewAssignment(item:any){const assigned=Date.parse(String(item?.assignedAt||"")),opened=Date.parse(String(item?.lastOpenedAt||""));return Number.isFinite(assigned)&&(!Number.isFinite(opened)||assigned>opened)}

function mediaKind(url:string){let path="";try{path=new URL(url,location.origin).pathname.toLowerCase()}catch{}if(/\.(mp4|webm|mov|m4v)$/.test(path))return"video";if(/\.(mp3|m4a|wav|ogg|aac)$/.test(path))return"audio";if(/\.(pdf)$/.test(path))return"document";return"link"}
function contentUrlOf(item:any){const raw=String(item?.contentUrl||item?.url||item?.link||"").trim();return /^www\./i.test(raw)?`https://${raw}`:raw}
function isExternalUrl(url:string){return /^https?:\/\//i.test(url)}
function isStoredTrainingFile(url:string){return /^\/api\/files\/[^/]+\/download(?:\?.*)?$/i.test(url)}
function viewerUrlOf(item:any,url:string){return isStoredTrainingFile(url)?`/api/training/enrollments/${encodeURIComponent(item.enrollmentId)}/content`:url}
function openExternalNow(url:string){const tab=window.open("about:blank","_blank");if(tab){try{tab.opener=null;tab.location.href=url;return true}catch{try{tab.close()}catch{}}}try{const a=document.createElement("a");a.href=url;a.target="_blank";a.rel="noopener noreferrer";a.style.display="none";document.body.appendChild(a);a.click();a.remove();return true}catch{return false}}

export function TrainingPage({notify}:{notify:Notify}){
 const [data,setData]=useState<any>(null),[error,setError]=useState(""),[course,setCourse]=useState<any>(null),[session,setSession]=useState<any>(null),[viewed,setViewed]=useState(0),[activeTab,setActiveTab]=useState<CategoryKey>("club");
 const timer=useRef<number|undefined>(undefined);
 const load=async()=>{if(timer.current)clearInterval(timer.current);setCourse(null);setSession(null);setError("");try{const p:any=await api("/api/training/my");setData(p.data)}catch(e:any){setError(e.message)}};
 useEffect(()=>{void load();return()=>{if(timer.current)clearInterval(timer.current)}},[]);
 const closeSession=async()=>{if(timer.current){clearInterval(timer.current);timer.current=undefined}if(session?.id)try{await api(`/api/training/sessions/${encodeURIComponent(session.id)}/close`,{method:"POST",body:"{}"})}catch{}setSession(null)};
 useEffect(()=>{const onHide=()=>{if(session?.id)navigator.sendBeacon?.(`/api/training/sessions/${encodeURIComponent(session.id)}/close`,new Blob(["{}"],{type:"application/json"}))};window.addEventListener("pagehide",onHide);return()=>window.removeEventListener("pagehide",onHide)},[session]);
 const assignments=data?.assignments||[],summary=data?.summary||{};
 const counts=useMemo(()=>Object.fromEntries(TRAINING_CATEGORIES.map(c=>[c.key,assignments.filter((item:any)=>trainingCategoryOf(item.category)===c.key).length])) as Record<CategoryKey,number>,[assignments]);
 const newCounts=useMemo(()=>Object.fromEntries(TRAINING_CATEGORIES.map(c=>[c.key,assignments.filter((item:any)=>trainingCategoryOf(item.category)===c.key&&isNewAssignment(item)).length])) as Record<CategoryKey,number>,[assignments]);
 useEffect(()=>{if(!assignments.length)return;const hasActive=assignments.some((item:any)=>trainingCategoryOf(item.category)===activeTab);if(!hasActive)setActiveTab(trainingCategoryOf(assignments[0].category))},[data]);
 const visible=assignments.filter((item:any)=>trainingCategoryOf(item.category)===activeTab);
 const activeCategory=TRAINING_CATEGORIES.find(c=>c.key===activeTab)||TRAINING_CATEGORIES[0];
 if(error)return <ErrorState message={error} retry={load}/>;if(!data)return <Loading label="در حال دریافت آموزش‌های شما..."/>;
 const openCourse=async(item:any)=>{const url=contentUrlOf(item);if(!url){notify("برای این آموزش هنوز فایل یا لینک محتوا ثبت نشده است.","error");return}const external=isExternalUrl(url);if(external){const opened=openExternalNow(url);if(!opened){notify("مرورگر اجازه بازکردن تب آموزش را نداد. Pop-up را برای این سایت فعال کنید.","error");return}notify("آموزش در تب جدید باز شد.","success");try{await closeSession();const key=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;const p:any=await api(`/api/training/enrollments/${encodeURIComponent(item.enrollmentId)}/open`,{method:"POST",body:JSON.stringify({clientSessionKey:key})});const id=p.data?.sessionId;if(id)await api(`/api/training/sessions/${encodeURIComponent(id)}/close`,{method:"POST",body:"{}"}).catch(()=>{});await load()}catch{notify("لینک آموزش باز شد؛ ثبت مشاهده این بار انجام نشد.","info")}return}try{await closeSession();const key=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;const p:any=await api(`/api/training/enrollments/${encodeURIComponent(item.enrollmentId)}/open`,{method:"POST",body:JSON.stringify({clientSessionKey:key})});const id=p.data?.sessionId;if(!id)throw new Error("نشست آموزش ایجاد نشد.");const assignment={...item,...(p.data?.assignment||{})};const source=contentUrlOf(assignment)||url;setCourse({...assignment,viewerUrl:viewerUrlOf(assignment,source),sourceUrl:source});setSession({id});setViewed(Number(assignment.totalViewSeconds||0));timer.current=window.setInterval(async()=>{if(document.visibilityState!=="visible"||!document.hasFocus())return;try{const r:any=await api(`/api/training/sessions/${encodeURIComponent(id)}/heartbeat`,{method:"POST",body:"{}"});setViewed(Number(assignment.totalViewSeconds||0)+Number(r.data?.durationSeconds||0))}catch{}},15000)}catch(e:any){notify(e.message||"بازکردن آموزش انجام نشد.","error")}};
 const complete=async()=>{if(!course)return;try{await api(`/api/training/enrollments/${encodeURIComponent(course.enrollmentId)}/complete`,{method:"POST",body:"{}"});notify("آموزش تکمیل شد و در پرونده ثبت شد.","success");await load()}catch(e:any){notify(e.message,"error")}};
 if(course){const source=String(course.sourceUrl||contentUrlOf(course)||""),url=String(course.viewerUrl||viewerUrlOf(course,source)||""),kind=isStoredTrainingFile(source)?"document":mediaKind(source);return <div className="mr-stack"><button type="button" className="mr-back-inline" onClick={()=>void load()}><ChevronLeft size={18}/>بازگشت به آموزش‌ها</button><Card><div className="mr-card-head"><div><span className="mr-pill">{activeCategory.label}</span><h3>{text(course.title)}</h3><p>{text(course.description," ")}</p></div><span className="mr-pill">{fa(Math.floor(viewed/60))} دقیقه مشاهده</span></div><div className="mr-course-viewer">{kind==="video"?<video controls playsInline preload="metadata" src={url}/>:kind==="audio"?<audio controls src={url}/>:url?<iframe title={course.title||"آموزش"} src={url} allow="autoplay; fullscreen"/>:<Empty title="محتوا آماده نیست" description="برای این آموزش هنوز فایل یا لینک محتوا ثبت نشده است."/>}</div><button type="button" className="mr-save" onClick={complete}><BadgeCheck size={18}/>تأیید تکمیل آموزش</button></Card></div>}
 return <div className="mr-stack"><style>{`
 .ctv1-tabs{display:flex;gap:8px;overflow-x:auto;padding:2px 1px 7px;scrollbar-width:none;position:sticky;top:0;z-index:4;background:rgba(247,250,248,.94);backdrop-filter:blur(10px)}
 .ctv1-tabs::-webkit-scrollbar{display:none}.ctv1-tab{position:relative;flex:0 0 auto;border:1px solid #d9e6df;background:#fff;border-radius:999px;padding:9px 12px;font:inherit;font-size:12px;font-weight:800;color:#34564a;display:flex;align-items:center;gap:7px;white-space:nowrap}.ctv1-tab b{min-width:22px;height:22px;padding:0 5px;border-radius:999px;background:#eef4f1;display:grid;place-items:center;font-size:11px}.ctv1-tab.active{background:#0a7547;color:#fff;border-color:#0a7547;box-shadow:0 7px 18px rgba(10,117,71,.18)}.ctv1-tab.active b{background:rgba(255,255,255,.18)}
 .ctv1-new-dot{position:absolute;top:3px;right:5px;width:8px;height:8px;border-radius:50%;background:#e11d2e;box-shadow:0 0 0 2px #fff}.ctv1-tab.active .ctv1-new-dot{box-shadow:0 0 0 2px #0a7547}
 .ctv1-section-title{display:flex;align-items:end;justify-content:space-between;gap:12px}.ctv1-section-title h3{margin:0;font-size:16px}.ctv1-section-title small{color:#708078}.ctv1-empty{padding:8px 0}
 `}</style><section className="mr-metrics"><article className="mr-metric"><small>کل آموزش‌ها</small><strong>{fa(summary.assigned||assignments.length)}</strong></article><article className="mr-metric"><small>بازشده</small><strong>{fa(summary.opened||0)}</strong></article><article className="mr-metric"><small>تکمیل‌شده</small><strong>{fa(summary.completed||0)}</strong></article><article className="mr-metric"><small>زمان مشاهده</small><strong>{fa(Math.floor(Number(summary.totalViewSeconds||0)/60))} دقیقه</strong></article></section><nav className="ctv1-tabs" aria-label="دسته‌بندی آموزش‌ها">{TRAINING_CATEGORIES.map(category=><button type="button" key={category.key} className={`ctv1-tab ${activeTab===category.key?"active":""}`} onClick={()=>setActiveTab(category.key)}>{newCounts[category.key]>0&&<span className="ctv1-new-dot" aria-label={`${fa(newCounts[category.key])} آموزش جدید`}/>}<span>{category.label}</span><b>{fa(counts[category.key]||0)}</b></button>)}</nav><div className="ctv1-section-title"><h3>{activeCategory.label}</h3><small>{fa(visible.length)} آموزش</small></div><div className="mr-course-grid">{visible.length?visible.map((item:any)=>{const url=contentUrlOf(item),external=isExternalUrl(url);return <Card key={item.enrollmentId} className="mr-course-card"><div className="mr-card-head"><div><span className="mr-pill">{activeCategory.label}</span><h3>{text(item.title)}</h3></div><span className="mr-pill subtle">{status(item.status)}</span></div><p>{text(item.description,"توضیحی ثبت نشده است.")}</p><div className="mr-course-meta"><span>{fa(item.durationMinutes||0)} دقیقه</span><span>{fa(item.openCount||0)} بار مشاهده</span></div><div className="mr-progress"><i style={{width:`${pct(item.progress)}%`}}/></div><button type="button" className="mr-btn mr-primary" onClick={()=>void openCourse(item)} disabled={!url}>دیدن آموزش {external&&<ExternalLink size={16}/>}</button>{!url&&<small className="mr-course-empty-note">محتوای این آموزش هنوز ثبت نشده است.</small>}</Card>}):<div className="ctv1-empty"><Empty title={`هنوز آموزشی در «${activeCategory.label}» ندارید`} description="پس از تخصیص آموزش توسط واحد آموزش، دوره در همین تب نمایش داده می‌شود."/></div>}</div></div>
}
