import React,{useEffect,useRef,useState} from "react";
import {BadgeCheck,ChevronLeft,ExternalLink} from "lucide-react";
import {api,Card,Empty,ErrorState,fa,Loading,Notify,pct,status,text} from "./caregiver-core-v2";

function mediaKind(url:string){let path="";try{path=new URL(url,location.origin).pathname.toLowerCase()}catch{}if(/\.(mp4|webm|mov|m4v)$/.test(path))return"video";if(/\.(mp3|m4a|wav|ogg|aac)$/.test(path))return"audio";if(/\.(pdf)$/.test(path))return"document";return"link"}
function contentUrlOf(item:any){const raw=String(item?.contentUrl||item?.url||item?.link||"").trim();return /^www\./i.test(raw)?`https://${raw}`:raw}
function isExternalUrl(url:string){return /^https?:\/\//i.test(url)}
function isStoredTrainingFile(url:string){return /^\/api\/files\/[^/]+\/download(?:\?.*)?$/i.test(url)}
function viewerUrlOf(item:any,url:string){return isStoredTrainingFile(url)?`/api/training/enrollments/${encodeURIComponent(item.enrollmentId)}/content`:url}
function openExternalNow(url:string){const tab=window.open(url,"_blank","noopener,noreferrer");if(tab)return true;try{const a=document.createElement("a");a.href=url;a.target="_blank";a.rel="noopener noreferrer";a.style.display="none";document.body.appendChild(a);a.click();a.remove();return true}catch{return false}}

export function TrainingPage({notify}:{notify:Notify}){const [data,setData]=useState<any>(null),[error,setError]=useState(""),[course,setCourse]=useState<any>(null),[session,setSession]=useState<any>(null),[viewed,setViewed]=useState(0);const timer=useRef<number|undefined>(undefined);const load=async()=>{if(timer.current)clearInterval(timer.current);setCourse(null);setSession(null);setError("");try{const p:any=await api("/api/training/my");setData(p.data)}catch(e:any){setError(e.message)}};useEffect(()=>{void load();return()=>{if(timer.current)clearInterval(timer.current)}},[]);
 const closeSession=async()=>{if(timer.current){clearInterval(timer.current);timer.current=undefined}if(session?.id)try{await api(`/api/training/sessions/${encodeURIComponent(session.id)}/close`,{method:"POST",body:"{}"})}catch{}setSession(null)};
 useEffect(()=>{const onHide=()=>{if(session?.id)navigator.sendBeacon?.(`/api/training/sessions/${encodeURIComponent(session.id)}/close`,new Blob(["{}"],{type:"application/json"}))};window.addEventListener("pagehide",onHide);return()=>window.removeEventListener("pagehide",onHide)},[session]);
 if(error)return <ErrorState message={error} retry={load}/>;if(!data)return <Loading label="در حال دریافت آموزش‌های شما..."/>;const assignments=data.assignments||[],summary=data.summary||{};
 const openCourse=async(item:any)=>{const url=contentUrlOf(item);if(!url){notify("برای این آموزش هنوز فایل یا لینک محتوا ثبت نشده است.","error");return}const external=isExternalUrl(url);if(external){const opened=openExternalNow(url);if(!opened){notify("مرورگر اجازه بازکردن تب آموزش را نداد. Pop-up را برای این سایت فعال کنید.","error");return}notify("آموزش در تب جدید باز شد.","success");try{await closeSession();const key=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;const p:any=await api(`/api/training/enrollments/${encodeURIComponent(item.enrollmentId)}/open`,{method:"POST",body:JSON.stringify({clientSessionKey:key})});const id=p.data?.sessionId;if(id)await api(`/api/training/sessions/${encodeURIComponent(id)}/close`,{method:"POST",body:"{}"}).catch(()=>{})}catch{notify("لینک آموزش باز شد؛ ثبت مشاهده این بار انجام نشد.","info")}return}try{await closeSession();const key=crypto.randomUUID?.()||`${Date.now()}-${Math.random()}`;const p:any=await api(`/api/training/enrollments/${encodeURIComponent(item.enrollmentId)}/open`,{method:"POST",body:JSON.stringify({clientSessionKey:key})});const id=p.data?.sessionId;if(!id)throw new Error("نشست آموزش ایجاد نشد.");const assignment={...item,...(p.data?.assignment||{})};const source=contentUrlOf(assignment)||url;setCourse({...assignment,viewerUrl:viewerUrlOf(assignment,source),sourceUrl:source});setSession({id});setViewed(Number(assignment.totalViewSeconds||0));timer.current=window.setInterval(async()=>{if(document.visibilityState!=="visible"||!document.hasFocus())return;try{const r:any=await api(`/api/training/sessions/${encodeURIComponent(id)}/heartbeat`,{method:"POST",body:"{}"});setViewed(Number(assignment.totalViewSeconds||0)+Number(r.data?.durationSeconds||0))}catch{}},15000)}catch(e:any){notify(e.message||"بازکردن آموزش انجام نشد.","error")}};
 const complete=async()=>{if(!course)return;try{await api(`/api/training/enrollments/${encodeURIComponent(course.enrollmentId)}/complete`,{method:"POST",body:"{}"});notify("آموزش تکمیل شد و در پرونده ثبت شد.","success");await load()}catch(e:any){notify(e.message,"error")}};
 if(course){const source=String(course.sourceUrl||contentUrlOf(course)||""),url=String(course.viewerUrl||viewerUrlOf(course,source)||""),kind=isStoredTrainingFile(source)?"document":mediaKind(source);return <div className="mr-stack"><button className="mr-back-inline" onClick={()=>void load()}><ChevronLeft size={18}/>بازگشت به آموزش‌ها</button><Card><div className="mr-card-head"><div><h3>{text(course.title)}</h3><p>{text(course.description," ")}</p></div><span className="mr-pill">{fa(Math.floor(viewed/60))} دقیقه مشاهده</span></div><div className="mr-course-viewer">{kind==="video"?<video controls playsInline preload="metadata" src={url}/>:kind==="audio"?<audio controls src={url}/>:url?<iframe title={course.title||"آموزش"} src={url} allow="autoplay; fullscreen"/>:<Empty title="محتوا آماده نیست" description="برای این آموزش هنوز فایل یا لینک محتوا ثبت نشده است."/>}</div><button className="mr-save" onClick={complete}><BadgeCheck size={18}/>تأیید تکمیل آموزش</button></Card></div>}
 return <div className="mr-stack"><section className="mr-metrics"><article className="mr-metric"><small>کل آموزش‌ها</small><strong>{fa(summary.assigned||assignments.length)}</strong></article><article className="mr-metric"><small>بازشده</small><strong>{fa(summary.opened||0)}</strong></article><article className="mr-metric"><small>تکمیل‌شده</small><strong>{fa(summary.completed||0)}</strong></article><article className="mr-metric"><small>زمان مشاهده</small><strong>{fa(Math.floor(Number(summary.totalViewSeconds||0)/60))} دقیقه</strong></article></section><div className="mr-course-grid">{assignments.length?assignments.map((item:any)=>{const url=contentUrlOf(item),external=isExternalUrl(url);return <Card key={item.enrollmentId} className="mr-course-card"><div className="mr-card-head"><div><span className="mr-pill">{text(item.category,"آموزش سازمانی")}</span><h3>{text(item.title)}</h3></div><span className="mr-pill subtle">{status(item.status)}</span></div><p>{text(item.description,"توضیحی ثبت نشده است.")}</p><div className="mr-course-meta"><span>{fa(item.durationMinutes||0)} دقیقه</span><span>{fa(item.openCount||0)} بار مشاهده</span></div><div className="mr-progress"><i style={{width:`${pct(item.progress)}%`}}/></div><button className="mr-btn mr-primary" onClick={()=>void openCourse(item)} disabled={!url}>دیدن آموزش {external&&<ExternalLink size={16}/>}</button>{!url&&<small className="mr-course-empty-note">محتوای این آموزش هنوز ثبت نشده است.</small>}</Card>}):<Empty title="آموزشی تخصیص داده نشده" description="پس از تخصیص توسط واحد آموزش، دوره‌ها در همین بخش نمایش داده می‌شوند."/>}</div></div>}
