import React,{FormEvent,useEffect,useRef,useState} from "react";
import {MessageCircle,Mic,Plus,RefreshCw,Send,Square,X} from "lucide-react";
import {api,dateTimeFa,Empty,ErrorState,Loading,Notify,status,text,uploadFile} from "./caregiver-core-v2";

export function SupportPage({user,profile,notify}:{user:any;profile?:any;notify:Notify}){
 const [threads,setThreads]=useState<any[]>([]),[active,setActive]=useState(""),[messages,setMessages]=useState<any[]>([]),[loading,setLoading]=useState(true),[error,setError]=useState(""),[newThread,setNewThread]=useState(false),[recording,setRecording]=useState(false);const recorder=useRef<MediaRecorder|null>(null),chunks=useRef<Blob[]>([]);
 const open=async(id:string)=>{setActive(id);const p:any=await api(`/api/caregiver/platform/support/threads/${encodeURIComponent(id)}/messages`);setMessages(p.data?.messages||[])};
 const load=async(keep=true)=>{setLoading(true);setError("");try{const p:any=await api("/api/caregiver/platform/support/threads"),rows=p.data?.threads||[];setThreads(rows);const id=keep&&active&&rows.some((x:any)=>x.id===active)?active:rows[0]?.id||"";setActive(id);if(id){const m:any=await api(`/api/caregiver/platform/support/threads/${encodeURIComponent(id)}/messages`);setMessages(m.data?.messages||[])}else setMessages([])}catch(e:any){setError(e.message)}finally{setLoading(false)}};
 useEffect(()=>{void load(false);return()=>{try{if(recorder.current?.state!=="inactive")recorder.current?.stop()}catch{}}},[]);
 const send=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const input=e.currentTarget.elements.namedItem("text") as HTMLInputElement,value=input.value.trim();if(!value||!active)return;try{await api(`/api/caregiver/platform/support/threads/${encodeURIComponent(active)}/messages`,{method:"POST",body:JSON.stringify({text:value})});input.value="";await open(active)}catch(x:any){notify(x.message,"error")}};
 const create=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const body:any=Object.fromEntries(new FormData(e.currentTarget).entries());try{const p:any=await api("/api/caregiver/platform/support/threads",{method:"POST",body:JSON.stringify(body)});setNewThread(false);notify("گفت‌وگو ایجاد شد.","success");await load(false);if(p.data?.id)await open(p.data.id)}catch(x:any){notify(x.message,"error")}};
 const toggleVoice=async()=>{if(!active)return;if(recording&&recorder.current){recorder.current.stop();return}if(!navigator.mediaDevices?.getUserMedia||!window.MediaRecorder)return notify("ضبط صدا در این مرورگر در دسترس نیست.","error");try{const stream=await navigator.mediaDevices.getUserMedia({audio:true});chunks.current=[];let mime="";for(const candidate of ["audio/webm;codecs=opus","audio/mp4","audio/webm"]){if(MediaRecorder.isTypeSupported(candidate)){mime=candidate;break}}const r=mime?new MediaRecorder(stream,{mimeType:mime}):new MediaRecorder(stream);recorder.current=r;r.ondataavailable=e=>{if(e.data.size)chunks.current.push(e.data)};r.onstop=async()=>{setRecording(false);stream.getTracks().forEach(t=>t.stop());try{const type=r.mimeType||mime||"audio/webm",ext=type.includes("mp4")?"m4a":"webm",blob=new Blob(chunks.current,{type}),file=new File([blob],`caregiver-support-${Date.now()}.${ext}`,{type}),stored:any=await uploadFile(file,"support",profile?.id||user?.caregiverId);await api(`/api/caregiver/platform/support/threads/${encodeURIComponent(active)}/messages`,{method:"POST",body:JSON.stringify({storedFileId:stored.id})});notify("پیام صوتی ارسال شد.","success");await open(active)}catch(x:any){notify(x.message,"error")}};r.start();setRecording(true)}catch(e:any){notify(e.message||"دسترسی میکروفون داده نشد.","error")}};
 if(error)return <ErrorState message={error} retry={()=>load(false)}/>;if(loading)return <Loading label="در حال دریافت گفت‌وگوها..."/>;const thread=threads.find(x=>x.id===active);
 return <div className="cv2-support"><div className="cv2-support-tools"><div><h2>پشتیبانی پرونده</h2><p>گفت‌وگوی مستقیم متنی و صوتی با سلامت اول</p></div><div><button className="mr-btn" onClick={()=>void load(true)}><RefreshCw size={16}/>به‌روزرسانی</button><button className="mr-btn mr-primary" onClick={()=>setNewThread(true)}><Plus size={16}/>گفت‌وگوی جدید</button></div></div><div className="cv2-support-layout"><aside className="cv2-thread-pane"><header><MessageCircle size={18}/><strong>گفت‌وگوهای من</strong></header><div className="cv2-thread-list">{threads.length?threads.map(t=><button key={t.id} className={t.id===active?"active":""} onClick={()=>void open(t.id)}><strong>{text(t.subject,"پشتیبانی پرونده")}</strong><small>{status(t.status)} • {dateTimeFa(t.updatedAt)}</small></button>):<Empty title="گفت‌وگویی ندارید" description="برای شروع، گفت‌وگوی جدید بسازید."/>}</div></aside><section className="cv2-chat-pane">{thread?<><header><div><h3>{text(thread.subject)}</h3><p>{status(thread.status)}</p></div></header><div className="cv2-messages">{messages.length?messages.map(m=><article key={m.id} className={`cv2-message ${m.senderUserId===user?.id?"mine":""}`}>{m.messageType==="VOICE"&&m.storedFileId?<><audio controls preload="none" src={`/api/files/${encodeURIComponent(m.storedFileId)}/download`}/><span>پیام صوتی</span></>:<p>{text(m.textContent," ")}</p>}<small>{text(m.senderName,"کاربر")} • {dateTimeFa(m.createdAt)}</small></article>):<Empty title="هنوز پیامی نیست" description="پیام متنی یا صوتی خود را ارسال کنید."/>}</div><form className="cv2-compose" onSubmit={send}><button type="button" className={recording?"recording":""} onClick={()=>void toggleVoice()} title={recording?"پایان ضبط":"ارسال وویس"}>{recording?<Square size={19}/>:<Mic size={19}/>}</button><input name="text" placeholder="پیام خود را بنویسید..." autoComplete="off"/><button className="send"><Send size={19}/></button></form>{recording&&<div className="cv2-recording"><span/>در حال ضبط وویس؛ برای ارسال دوباره روی دکمه میکروفون بزنید.</div>}</>:<Empty title="گفت‌وگویی انتخاب نشده" description="از فهرست سمت راست یک گفت‌وگو را انتخاب کنید."/>}</section></div>{newThread&&<div className="mr-modal-backdrop"><section className="mr-modal"><button className="mr-modal-close" onClick={()=>setNewThread(false)}><X size={20}/></button><form onSubmit={create}><h2>گفت‌وگوی جدید</h2><label><span>موضوع</span><input name="subject" required placeholder="موضوع درخواست"/></label><label><span>پیام</span><textarea name="message" required placeholder="شرح درخواست"/></label><button className="mr-save">شروع گفت‌وگو</button></form></section></div>}</div>
}
