import React,{useEffect,useMemo,useState} from "react";
import {Activity,Award,BadgeCheck,BookOpen,BrainCircuit,BriefcaseBusiness,ClipboardCheck,Landmark,ShieldCheck,Star,WalletCards} from "lucide-react";
import {EvaluationAnalysis,GoldStars} from "../desktop-react/evaluation-insights-v1";
import {api,Card,dateFa,Empty,ErrorState,fa,initials,Loading,money,status,text} from "./caregiver-core-v2";
import {CaregiverScorecardView} from "./caregiver-scorecard-v2";
import "../desktop-react/caregiver-activity-scorecard.css";
import "./caregiver-scorecard-mobile-v3.css";

type TabKey="technical"|"analysis"|"credit"|"activity";
const clamp=(value:unknown)=>Math.max(0,Math.min(100,Number(value||0)));
const gradeMap:Record<string,{code:string;title:string}>={LOAN_70M_CUMULATIVE:{code:"A+",title:"اعتبار ممتاز"},LOAN_24M:{code:"A",title:"اعتبار بسیار خوب"},LOAN_12M:{code:"B",title:"اعتبار خوب"},LOAN_6M:{code:"C",title:"اعتبار متوسط"},LOAN_3M:{code:"D",title:"اعتبار پایه"}};
function scoreProgress(item:any){const metric=Number(item?.evaluation?.metric),threshold=Number(item?.scoreThreshold||item?.evaluation?.threshold||0);return Number.isFinite(metric)&&threshold>0?clamp(metric/threshold*100):clamp(item?.progressPercent)}
function combinedProgress(item:any){if(!item)return 0;return Math.min(clamp(item.progressPercent),scoreProgress(item))}
function creditRank(financial:any){const loans=Array.isArray(financial?.loans)?financial.loans:[];const eligible=[...loans].filter((x:any)=>x?.eligible).sort((a:any,b:any)=>Number(b.amountToman||0)-Number(a.amountToman||0));const top=eligible[0]||null,limit=Number(top?.amountToman||0),grade=top?gradeMap[String(top.key)]||{code:"A",title:"واجد اعتبار"}:{code:"E",title:"در حال ساخت اعتبار"};const next=[...loans].filter((x:any)=>!x?.eligible&&Number(x.amountToman||0)>limit).sort((a:any,b:any)=>Number(a.amountToman||0)-Number(b.amountToman||0))[0]||(!top?[...loans].sort((a:any,b:any)=>Number(a.amountToman||0)-Number(b.amountToman||0))[0]:null);return{top,limit,grade,next,loans}}
function Progress({value}:{value:unknown}){const n=clamp(value);return <div className="cst3-progress"><span style={{width:`${n}%`}}/></div>}
function useDesktop(){const [desktop,setDesktop]=useState(()=>typeof matchMedia!=="undefined"&&matchMedia("(min-width:900px)").matches);useEffect(()=>{const mq=matchMedia("(min-width:900px)"),change=()=>setDesktop(mq.matches);mq.addEventListener("change",change);return()=>mq.removeEventListener("change",change)},[]);return desktop}

function TechnicalTab({scorecard,financial,profile}:{scorecard:any;financial:any;profile:any}){const summary=scorecard?.summary||{},rank=scorecard?.rank||{},license=scorecard?.license||{},indicators=Array.isArray(scorecard?.indicators)?scorecard.indicators:[],score=summary.score;return <div className="cst3-panel">
 <section className="cst3-technical-hero"><div><small>امتیاز حرفه‌ای</small><strong>{score==null?"—":fa(score)}<em>/ ۱۰۰</em></strong><span>{text(rank.title,"در انتظار ارزیابی")}{rank.code?` • ${rank.code}`:""}</span><GoldStars stars={rank.stars}/></div><div className="cst3-license"><ShieldCheck size={20}/><small>پروانه حرفه‌ای</small><strong>{text(license.status,"ثبت نشده")}</strong><span>{text(license.number,"شماره پروانه ایجاد نشده")}</span></div></section>
 <Card className="cst3-card"><div className="cst3-head"><span><Star size={17}/></span><div><strong>کارنامه فنی</strong><small>{text(summary.notice,"آخرین وضعیت نظام ارزیابی و رتبه حرفه‌ای")}</small></div><b>{summary.official?"نهایی":"غیرنهایی"}</b></div><div className="cst3-overview"><article><span>شاخص‌های تکمیل‌شده</span><strong>{fa(summary.completedIndicators||0)} / {fa(summary.totalIndicators||0)}</strong><Progress value={Number(summary.totalIndicators)?Number(summary.completedIndicators||0)/Number(summary.totalIndicators)*100:0}/></article><article><span>معیارهای امتیازدهی‌شده</span><strong>{fa(summary.scoredCriteria||0)} / {fa(summary.totalCriteria||0)}</strong><Progress value={Number(summary.totalCriteria)?Number(summary.scoredCriteria||0)/Number(summary.totalCriteria)*100:0}/></article></div><div className="cst3-indicators">{indicators.map((ind:any)=><article key={ind.code} className={ind.complete?"complete":""}><header><span>{text(ind.code)}</span><strong>{text(ind.title,"شاخص")}</strong></header><b>{ind.score==null&&ind.liveScore==null?"—":fa(ind.score??ind.liveScore)}</b><Progress value={ind.score??ind.liveScore}/><small>{fa(ind.scoredCount||0)} از {fa(ind.criteriaCount||0)} معیار ثبت شده</small></article>)}</div></Card>
 </div>}

function AnalysisTab({analysis,rank}:{analysis:any;rank:any}){return <div className="cst3-panel"><Card className="cst3-card"><div className="cst3-head"><span><BrainCircuit size={18}/></span><div><strong>تحلیل فنی</strong><small>تحلیل نقاط قوت و زمینه‌های قابل بهبود بر اساس معیارهای همین کارنامه.</small></div></div>{analysis?<><div className="cst3-analysis-rank"><div><small>رتبه حرفه‌ای فعلی</small><strong>{text(rank?.title,"در انتظار ارزیابی")}</strong></div><GoldStars stars={rank?.stars}/></div><EvaluationAnalysis analysis={analysis}/></>:<Empty title="تحلیل فنی هنوز آماده نیست" description="پس از ثبت معیارهای کافی و نهایی‌شدن ارزیابی، تحلیل نقاط قوت و ضعف در این تب نمایش داده می‌شود."/>}</Card></div>}

function CreditTab({financial}:{financial:any}){const credit=useMemo(()=>creditRank(financial),[financial]),wallet=financial?.wallet?.summary||{},referrals=financial?.referrals?.summary||{},candidate=credit.next||credit.top||credit.loans[0]||null,progress=credit.top&&!credit.next?100:combinedProgress(candidate),openRequests=(financial?.wallet?.creditRequests||[]).filter((x:any)=>["REQUESTED","UNDER_REVIEW","APPROVED"].includes(String(x.status||"").toUpperCase())).length;return <div className="cst3-panel">
 <section className="cst3-credit-hero"><div className="cst3-credit-ring" style={{"--cst3-p":`${progress}%`} as React.CSSProperties}><div><small>رتبه اعتباری</small><strong>{credit.grade.code}</strong><span>{credit.grade.title}</span></div></div><div className="cst3-credit-copy"><small>سقف تسهیلات فعلی</small><strong>{credit.limit?money(credit.limit):"هنوز فعال نشده"}</strong><span>{credit.next?`${fa(progress)}٪ تا ${text(credit.next.title,"سطح بعدی")}`:credit.top?"بالاترین سطح فعال شما":"در حال ساخت سابقه اعتباری"}</span></div></section>
 <section className="cst3-facts"><article><WalletCards size={18}/><span>مانده کیف پول</span><strong>{money(wallet.balanceToman||0)}</strong></article><article><BadgeCheck size={18}/><span>قابل تسویه</span><strong>{money(wallet.availableToman||0)}</strong></article><article><Landmark size={18}/><span>درخواست اعتبار باز</span><strong>{fa(openRequests)}</strong></article><article><Award size={18}/><span>معرفی موفق</span><strong>{fa(referrals.completedReferrals||0)}</strong></article></section>
 <Card className="cst3-card"><div className="cst3-head"><span><Landmark size={18}/></span><div><strong>رتبه‌بندی اعتباری</strong><small>سطوح تسهیلات بر اساس سابقه همکاری و امتیاز ارزیابی.</small></div><b>{credit.grade.code}</b></div><div className="cst3-loans">{credit.loans.length?credit.loans.map((loan:any)=><article key={loan.key} className={loan.eligible?"eligible":""}><header><div><strong>{text(loan.title,"تسهیلات")}</strong><small>{money(loan.amountToman||0)}</small></div><span>{loan.eligible?"واجد شرایط":status(loan.status)}</span></header><Progress value={loan.progressPercent}/><footer><span>سابقه {fa(loan.progressPercent||0)}٪</span><span>امتیاز {loan.evaluation?.metric==null?"—":fa(loan.evaluation.metric)} / {fa(loan.evaluation?.threshold||loan.scoreThreshold||0)}</span></footer></article>):<Empty title="سطح اعتباری ثبت نشده" description="اطلاعات رتبه اعتباری پس از شکل‌گیری سابقه همکاری نمایش داده می‌شود."/>}</div></Card>
 </div>}

function ActivityTab({scorecard}:{scorecard:any}){const records=scorecard?.records||{},history=Array.isArray(scorecard?.history)?scorecard.history:[];return <div className="cst3-panel"><section className="cst3-activity-grid"><article><BriefcaseBusiness size={20}/><strong>{fa(records.contractsCount||0)}</strong><span>قرارداد ثبت‌شده</span></article><article><BookOpen size={20}/><strong>{fa(records.trainingCount||0)}</strong><span>آموزش تخصیص‌یافته</span></article><article><BadgeCheck size={20}/><strong>{fa(records.completedTrainingCount||0)}</strong><span>آموزش تکمیل‌شده</span></article><article><Award size={20}/><strong>{fa(history.length)}</strong><span>دوره ارزیابی</span></article></section><Card className="cst3-card"><div className="cst3-head"><span><Activity size={18}/></span><div><strong>خلاصه فعالیت حرفه‌ای</strong><small>آخرین سوابق ثبت‌شده از قرارداد، آموزش و ارزیابی.</small></div></div>{history.length?<div className="cst3-history">{history.slice(0,8).map((row:any)=><article key={row.id}><div><strong>{text(row.title,"دوره ارزیابی")}</strong><small>{dateFa(row.finalizedAt||row.updatedAt)}</small></div><span>{status(row.status)}</span><b>{row.finalScore==null?"—":fa(row.finalScore)}</b></article>)}</div>:<Empty title="هنوز سابقه ارزیابی ثبت نشده" description="دوره‌های ارزیابی پس از ثبت در این قسمت نمایش داده می‌شوند."/>}</Card></div>}

export function CaregiverScorecardMobileV3({profile}:{profile?:any}){const desktop=useDesktop(),[scorecard,setScorecard]=useState<any>(null),[financial,setFinancial]=useState<any>(null),[error,setError]=useState(""),[tab,setTab]=useState<TabKey>("technical");const load=async()=>{setError("");try{const [s,f]:any=await Promise.all([api("/api/caregiver/platform/scorecard-v2"),api("/api/caregiver/platform/financial-profile")]);setScorecard(s.data);setFinancial(f.data)}catch(e:any){setError(e.message)}};useEffect(()=>{void load()},[]);if(error)return <ErrorState message={error} retry={load}/>;if(!scorecard||!financial)return <Loading label="در حال ساخت کارنامه فعالیت..."/>;if(desktop)return <CaregiverScorecardView scorecard={scorecard} financial={financial} profile={profile||financial.caregiver}/>;const person=profile||financial?.caregiver||scorecard?.caregiver||{},tabs:Array<{key:TabKey;label:string;icon:any}>=[{key:"technical",label:"کارنامه فنی",icon:ClipboardCheck},{key:"analysis",label:"تحلیل فنی",icon:BrainCircuit},{key:"credit",label:"رتبه اعتباری",icon:Landmark},{key:"activity",label:"خلاصه فعالیت",icon:BriefcaseBusiness}];return <div className="cst3-shell"><section className="cst3-person"><div className="cst3-avatar">{scorecard?.caregiver?.avatarUrl?<img src={scorecard.caregiver.avatarUrl} alt={text(person.fullName,"مراقب")}/>:initials(person.fullName)}</div><div><small>کارنامه فعالیت مراقب</small><strong>{text(person.fullName,"مراقب")}</strong><span>{text(person.membershipCode||scorecard?.caregiver?.membershipCode)} • {text(person.specialty||person.primaryType||scorecard?.caregiver?.serviceGroup)}</span></div><b className={scorecard?.summary?.official?"official":"pending"}>{scorecard?.summary?.official?"رسمی":"در ارزیابی"}</b></section><nav className="cst3-tabs" aria-label="بخش‌های کارنامه">{tabs.map(item=>{const Icon=item.icon;return <button key={item.key} className={tab===item.key?"active":""} onClick={()=>setTab(item.key)}><Icon size={16}/><span>{item.label}</span></button>})}</nav>{tab==="technical"&&<TechnicalTab scorecard={scorecard} financial={financial} profile={person}/>} {tab==="analysis"&&<AnalysisTab analysis={scorecard.analysis} rank={scorecard.rank}/>} {tab==="credit"&&<CreditTab financial={financial}/>} {tab==="activity"&&<ActivityTab scorecard={scorecard}/>}</div>}
