import React,{useEffect,useMemo,useState} from "react";
import {Activity,Award,BadgeCheck,BookOpen,BriefcaseBusiness,CircleDollarSign,Landmark,ShieldCheck,Star,WalletCards} from "lucide-react";
import {EvaluationAnalysis,GoldStars} from "../desktop-react/evaluation-insights-v1";
import {api,Card,dateFa,ErrorState,fa,initials,Loading,Metric,money,status,text} from "./caregiver-core-v2";
import "../desktop-react/caregiver-activity-scorecard.css";
import "./caregiver-desktop-finance-v3.css";

const clamp=(value:unknown)=>Math.max(0,Math.min(100,Number(value||0)));
const gradeMap:Record<string,{code:string;title:string}>={LOAN_70M_CUMULATIVE:{code:"A+",title:"اعتبار ممتاز"},LOAN_24M:{code:"A",title:"اعتبار بسیار خوب"},LOAN_12M:{code:"B",title:"اعتبار خوب"},LOAN_6M:{code:"C",title:"اعتبار متوسط"},LOAN_3M:{code:"D",title:"اعتبار پایه"}};
function scoreProgress(item:any){const metric=Number(item?.evaluation?.metric),threshold=Number(item?.scoreThreshold||item?.evaluation?.threshold||0);return Number.isFinite(metric)&&threshold>0?clamp(metric/threshold*100):clamp(item?.progressPercent)}
function combinedProgress(item:any){if(!item)return 0;return Math.min(clamp(item.progressPercent),scoreProgress(item))}
function creditRank(financial:any){const loans=Array.isArray(financial?.loans)?financial.loans:[];const eligible=[...loans].filter((x:any)=>x?.eligible).sort((a:any,b:any)=>Number(b.amountToman||0)-Number(a.amountToman||0));const top=eligible[0]||null,limit=Number(top?.amountToman||0),grade=top?gradeMap[String(top.key)]||{code:"A",title:"واجد اعتبار"}:{code:"E",title:"در حال ساخت اعتبار"};const next=[...loans].filter((x:any)=>!x?.eligible&&Number(x.amountToman||0)>limit).sort((a:any,b:any)=>Number(a.amountToman||0)-Number(b.amountToman||0))[0]||(!top?[...loans].sort((a:any,b:any)=>Number(a.amountToman||0)-Number(b.amountToman||0))[0]:null);return{top,limit,grade,next,loans}}
function Score({value}:{value:unknown}){const n=Number(value);return <span className="cs-score">{Number.isFinite(n)?fa(n):"—"}</span>}
function Progress({value}:{value:unknown}){const n=clamp(value);return <div className="cs-progress"><span style={{width:`${n}%`}}/></div>}

function HomeFinancialPie({financial,credit}:{financial:any;credit:ReturnType<typeof creditRank>}){const wallet=financial?.wallet?.summary||{},referrals=financial?.referrals?.summary||{};const candidate=credit.next||credit.top||credit.loans[0]||null;const progress=credit.top&&!credit.next?100:combinedProgress(candidate);const gradeStep:{[key:string]:number}={E:0,D:1,C:2,B:3,A:4,"A+":5};const active=gradeStep[credit.grade.code]??0;return <Card className="cv3-home-finance"><div className="cs-section-head"><div><span className="cs-icon"><WalletCards size={18}/></span><div><h3>رتبه‌بندی اعتباری و توان مالی</h3><p>نمای پای‌چارتی بر اساس ارزیابی نهایی، سابقه همکاری، تسهیلات، کیف پول و معرفی‌های ثبت‌شده.</p></div></div><span className="cs-credit-badge">{credit.grade.code}</span></div><div className="cv3-financial-pie-layout"><div className="cv3-financial-pie-wrap"><div className="cv3-financial-pie" style={{"--cv3-p":`${progress}%`} as React.CSSProperties}><div className="cv3-financial-pie-center"><small>رتبه اعتباری</small><strong>{credit.grade.code}</strong><span>{credit.grade.title}</span></div></div><div className="cv3-financial-pie-caption">{credit.next?`${fa(progress)}٪ از مسیر رسیدن به ${text(credit.next.title,"سطح بعدی")}`:credit.top?"بالاترین سطح فعال شما بر اساس داده‌های فعلی":"در حال ساخت سابقه اعتباری"}</div><div className="cv3-credit-levels" aria-label="سطوح رتبه اعتباری">{[1,2,3,4,5].map(n=><span key={n} className={n<=active?"active":""}/>)}</div></div><div className="cv3-financial-facts"><article><span>سقف تسهیلات فعلی</span><strong>{credit.limit?money(credit.limit):"هنوز فعال نشده"}</strong></article><article><span>قابل تسویه</span><strong>{money(wallet.availableToman||0)}</strong></article><article><span>مانده کیف پول</span><strong>{money(wallet.balanceToman||0)}</strong></article><article><span>تسویه در جریان</span><strong>{money(wallet.pendingSettlementToman||0)}</strong></article><article><span>معرفی موفق</span><strong>{fa(referrals.completedReferrals||0)}</strong></article><article><span>امتیاز مؤثر سطح بعد</span><strong>{candidate?.evaluation?.metric==null?"—":fa(candidate.evaluation.metric)}</strong></article>{credit.next&&<article className="wide"><span>سطح اعتباری بعدی</span><strong>{text(credit.next.title)} • {money(credit.next.amountToman||0)}</strong><small>پیشرفت سابقه {fa(credit.next.progressPercent||0)}٪ • حد امتیاز {fa(credit.next.evaluation?.threshold||credit.next.scoreThreshold||0)}</small></article>}</div></div></Card>}

function FinancialSection({financial,credit,homeMode}:{financial:any;credit:ReturnType<typeof creditRank>;homeMode:boolean}){if(homeMode)return <HomeFinancialPie financial={financial} credit={credit}/>;const wallet=financial?.wallet?.summary||{},referrals=financial?.referrals?.summary||{},openCreditRequests=(financial?.wallet?.creditRequests||[]).filter((x:any)=>["REQUESTED","UNDER_REVIEW","APPROVED"].includes(String(x.status))).length;return <Card><div className="cs-section-head"><div><span className="cs-icon"><WalletCards size={18}/></span><div><h3>رتبه‌بندی اعتباری و توان مالی</h3><p>این بخش مستقیماً از ماژول اعتبارات مالی، قواعد تسهیلات، کیف پول و سابقه معرفی تغذیه می‌شود.</p></div></div><span className="cs-credit-badge">{credit.grade.code}</span></div><section className="cs-fin-metrics"><Metric label="مانده کیف پول" value={money(wallet.balanceToman||0)}/><Metric label="قابل تسویه" value={money(wallet.availableToman||0)}/><Metric label="تسویه در جریان" value={money(wallet.pendingSettlementToman||0)}/><Metric label="معرفی موفق" value={fa(referrals.completedReferrals||0)}/><Metric label="درخواست اعتبار باز" value={fa(openCreditRequests)}/></section><div className="cs-credit-ladder">{credit.loans.map((loan:any)=><article key={loan.key} className={loan.eligible?"eligible":""}><header><div><strong>{text(loan.title,"تسهیلات")}</strong><small>{money(loan.amountToman||0)}</small></div><span>{loan.eligible?"واجد شرایط":status(loan.status)}</span></header><Progress value={loan.progressPercent}/><div><span>پیشرفت سابقه {fa(loan.progressPercent||0)}٪</span><span>امتیاز ملاک {loan.evaluation?.metric==null?"—":fa(loan.evaluation.metric)} / حد {fa(loan.evaluation?.threshold||0)}</span></div></article>)}</div>{credit.next&&<div className="cs-next-credit"><Landmark size={21}/><div><strong>سطح اعتباری بعدی: {text(credit.next.title)}</strong><span>برای رسیدن به {money(credit.next.amountToman)}، پیشرفت فعلی {fa(credit.next.progressPercent||0)}٪ است.</span></div></div>}</Card>}

export function CaregiverScorecardView({scorecard,financial,profile}:{scorecard:any;financial:any;profile?:any}){
 const person=profile||financial?.caregiver||scorecard?.caregiver||{},summary=scorecard?.summary||{},rank=scorecard?.rank||{},analysis=scorecard?.analysis||null,license=scorecard?.license||{},records=scorecard?.records||{},credit=useMemo(()=>creditRank(financial),[financial]);
 const indicators=Array.isArray(scorecard?.indicators)?scorecard.indicators:[],history=Array.isArray(scorecard?.history)?scorecard.history:[];const score=summary.score,official=Boolean(summary.official),homeMode=typeof window!=="undefined"&&(location.pathname==="/mobile"||location.pathname==="/mobile/");
 return <div className="cs-card-stack caregiver-self-scorecard">
  <Card className="cs-identity"><div className="cs-avatar">{scorecard?.caregiver?.avatarUrl?<img src={scorecard.caregiver.avatarUrl} alt={text(person.fullName,"مراقب")}/>:initials(person.fullName)}</div><div className="cs-person"><div className="cs-title-row"><div><span>کارنامه فعالیت مراقب</span><h2>{text(person.fullName,"مراقب")}</h2><p>{text(person.membershipCode||scorecard?.caregiver?.membershipCode)} • {text(person.mobile||scorecard?.caregiver?.mobile)} • {text(person.specialty||person.primaryType||scorecard?.caregiver?.serviceGroup)}</p></div><span className={`cs-official ${official?"yes":"no"}`}>{official?"کارنامه رسمی":"در حال ارزیابی"}</span></div><div className="cs-quick"><span><ShieldCheck size={15}/>{text(license.professionalLevel||person.professionalLevel,"ارزیابی نشده")}</span><span><Award size={15}/>{text(license.number,"بدون شماره پروانه")}</span><span><Activity size={15}/>{status(person.accountStatus||person.status)}</span></div></div></Card>
  <section className="cs-primary-metrics"><article><span>امتیاز حرفه‌ای</span><strong><Score value={score}/><small>از ۱۰۰</small></strong><div><p>{text(rank.title,"در انتظار ارزیابی")} {rank.code?`• ${rank.code}`:""}</p><GoldStars stars={rank.stars}/></div></article><article className="credit"><span>رتبه اعتباری داخلی</span><strong>{credit.grade.code}<small>{credit.grade.title}</small></strong><p>{credit.limit?`حد تسهیلات فعلی ${money(credit.limit)}`:"هنوز سطح تسهیلات فعال نشده"}</p></article><article><span>پروانه حرفه‌ای</span><strong>{text(license.status,"ثبت نشده")}</strong><p>{text(license.number,"شماره پروانه هنوز ایجاد نشده")}</p></article><article><span>سابقه فعالیت ثبت‌شده</span><strong>{fa(records.contractsCount||0)}<small>قرارداد</small></strong><p>{fa(records.completedTrainingCount||0)} آموزش تکمیل‌شده از {fa(records.trainingCount||0)}</p></article></section>
  <Card><div className="cs-section-head"><div><span className="cs-icon"><Star size={18}/></span><div><h3>نظام ارزیابی و رتبه حرفه‌ای</h3><p>{text(summary.notice,"آخرین اطلاعات نظام ارزیابی و پروانه")}</p></div></div><strong>{official?"نهایی":"غیرنهایی"}</strong></div><div className="cs-eval-overview"><div><span>شاخص‌های تکمیل‌شده</span><strong>{fa(summary.completedIndicators||0)} / {fa(summary.totalIndicators||0)}</strong><Progress value={Number(summary.totalIndicators)?Number(summary.completedIndicators||0)/Number(summary.totalIndicators)*100:0}/></div><div><span>معیارهای امتیازدهی‌شده</span><strong>{fa(summary.scoredCriteria||0)} / {fa(summary.totalCriteria||0)}</strong><Progress value={Number(summary.totalCriteria)?Number(summary.scoredCriteria||0)/Number(summary.totalCriteria)*100:0}/></div></div><div className="cs-indicator-grid">{indicators.map((ind:any)=><article key={ind.code} className={ind.complete?"complete":""}><div><span>{ind.code}</span><strong>{text(ind.title,"شاخص")}</strong></div><Score value={ind.score??ind.liveScore}/><Progress value={ind.score??ind.liveScore}/><small>{fa(ind.scoredCount||0)} از {fa(ind.criteriaCount||0)} معیار ثبت شده</small></article>)}</div></Card>
  {analysis&&<Card><div className="cs-section-head"><div><span className="cs-icon"><Star size={18}/></span><div><h3>تحلیل نقاط قوت و ضعف</h3><p>تحلیل خودکار فقط بر پایه امتیاز معیارهای همین کارنامه.</p></div></div></div><EvaluationAnalysis analysis={analysis}/></Card>}
  <FinancialSection financial={financial} credit={credit} homeMode={homeMode}/>
  <Card><div className="cs-section-head"><div><span className="cs-icon"><BriefcaseBusiness size={18}/></span><div><h3>خلاصه فعالیت حرفه‌ای</h3><p>وضعیت قرارداد، آموزش و ارزیابی شما از اطلاعات ثبت‌شده در سامانه.</p></div></div></div><div className="cs-activity-grid"><article><BriefcaseBusiness size={22}/><strong>{fa(records.contractsCount||0)}</strong><span>قرارداد ثبت‌شده</span></article><article><BookOpen size={22}/><strong>{fa(records.trainingCount||0)}</strong><span>آموزش تخصیص‌یافته</span></article><article><BadgeCheck size={22}/><strong>{fa(records.completedTrainingCount||0)}</strong><span>آموزش تکمیل‌شده</span></article><article><Award size={22}/><strong>{fa(history.length)}</strong><span>دوره ارزیابی</span></article></div></Card>
  {history.length>0&&<Card><div className="cs-section-head"><div><span className="cs-icon"><Activity size={18}/></span><div><h3>تاریخچه ارزیابی</h3><p>دوره‌های ثبت‌شده در نظام ارزیابی و پروانه</p></div></div></div><div className="da-table-wrap"><table className="da-table"><thead><tr><th>دوره</th><th>وضعیت</th><th>امتیاز نهایی</th><th>تاریخ نهایی‌سازی</th></tr></thead><tbody>{history.slice(0,8).map((row:any)=><tr key={row.id}><td>{text(row.title,"دوره ارزیابی")}</td><td>{status(row.status)}</td><td>{row.finalScore==null?"—":fa(row.finalScore)}</td><td>{dateFa(row.finalizedAt||row.updatedAt)}</td></tr>)}</tbody></table></div></Card>}
 </div>
}

export function CaregiverScorecard({profile}:{profile?:any}){const [scorecard,setScorecard]=useState<any>(null),[financial,setFinancial]=useState<any>(null),[error,setError]=useState("");const load=async()=>{setError("");try{const [s,f]:any=await Promise.all([api("/api/caregiver/platform/scorecard-v2"),api("/api/caregiver/platform/financial-profile")]);setScorecard(s.data);setFinancial(f.data)}catch(e:any){setError(e.message)}};useEffect(()=>{void load()},[]);if(error)return <ErrorState message={error} retry={load}/>;if(!scorecard||!financial)return <Loading label="در حال ساخت کارنامه فعالیت..."/>;return <CaregiverScorecardView scorecard={scorecard} financial={financial} profile={profile||financial.caregiver}/>}
