import React,{useEffect,useRef,useState} from "react";
import {TrainingPage as TrainingPageV1} from "./caregiver-training-tabs-v1";
import {Notify} from "./caregiver-core-v2";

function normalizedUrl(value:unknown){const raw=String(value||"").trim();return /^www\./i.test(raw)?`https://${raw}`:raw}
export function TrainingPage({notify}:{notify:Notify}){
 const shell=useRef<HTMLDivElement>(null),[assignments,setAssignments]=useState<any[]>([]);const ref=useRef<any[]>([]);ref.current=assignments;
 const load=async()=>{try{const response=await fetch("/api/training/my",{credentials:"same-origin",cache:"no-store"});if(!response.ok)return;const payload:any=await response.json();setAssignments(Array.isArray(payload?.data?.assignments)?payload.data.assignments:[])}catch{}};useEffect(()=>{void load()},[]);
 useEffect(()=>{const root=shell.current;if(!root)return;const decorate=()=>{const rows=ref.current;root.querySelectorAll<HTMLElement>(".mr-course-card").forEach(card=>{if(card.querySelector(".ctev1-exam-button"))return;const title=String(card.querySelector("h3")?.textContent||"").trim(),item=rows.find(x=>String(x.title||"").trim()===title),examUrl=normalizedUrl(item?.examUrl);if(!examUrl)return;const a=document.createElement("a");a.className="mr-btn ctev1-exam-button";a.href=examUrl;a.target="_blank";a.rel="noopener noreferrer";a.innerHTML='<span>ورود به آزمون</span><span aria-hidden="true">↗</span>';card.appendChild(a)});const detailHead=Array.from(root.querySelectorAll<HTMLElement>(".mr-card-head")).find(node=>node.closest(".mr-course-card")==null&&node.querySelector("h3"));if(detailHead){const title=String(detailHead.querySelector("h3")?.textContent||"").trim(),item=rows.find(x=>String(x.title||"").trim()===title),examUrl=normalizedUrl(item?.examUrl),card=detailHead.closest<HTMLElement>(".mr-card");if(examUrl&&card&&!card.querySelector(".ctev1-exam-button")){const a=document.createElement("a");a.className="mr-btn ctev1-exam-button detail";a.href=examUrl;a.target="_blank";a.rel="noopener noreferrer";a.innerHTML='<span>ورود به آزمون این آموزش</span><span aria-hidden="true">↗</span>';card.appendChild(a)}}};decorate();const observer=new MutationObserver(decorate);observer.observe(root,{subtree:true,childList:true});return()=>observer.disconnect()},[assignments]);
 return <div ref={shell} className="ctev1-shell"><style>{`.ctev1-exam-button{margin-top:8px!important;display:flex!important;align-items:center;justify-content:center;gap:8px;text-decoration:none!important;border:1px solid #087443!important;color:#087443!important;background:#f4fbf7!important;font-weight:900!important}.ctev1-exam-button.detail{margin-top:10px!important}`}</style><TrainingPageV1 notify={notify}/></div>;
}
