const PUSH_SW="/caregiver-push-sw.js?v=2.0.0";
const CONFIG_API="/api/caregiver/push/config";
const SUB_API="/api/caregiver/push/subscriptions";
const TEST_API="/api/caregiver/push/test";
let initialized=false,booting=false;

type PushConfig={configured:boolean;publicKey:string;activeSubscriptions:number;version:string};

function isIos(){return /iPad|iPhone|iPod/.test(navigator.userAgent)||(navigator.platform==="MacIntel"&&navigator.maxTouchPoints>1)}
function isStandalone(){return matchMedia("(display-mode: standalone)").matches||Boolean((navigator as any).standalone)}
function supported(){return "serviceWorker" in navigator&&"PushManager" in window&&"Notification" in window}
function platform(){return isIos()?"ios":/Android/i.test(navigator.userAgent)?"android":"web"}
function decodeKey(value:string){const padded=value+"=".repeat((4-value.length%4)%4),raw=atob(padded.replace(/-/g,"+").replace(/_/g,"/")),bytes=new Uint8Array(raw.length);for(let i=0;i<raw.length;i++)bytes[i]=raw.charCodeAt(i);return bytes}
async function requestJson(path:string,init:RequestInit={}){const headers=new Headers(init.headers||{});if(typeof init.body==="string"&&!headers.has("content-type"))headers.set("content-type","application/json");const response=await fetch(path,{credentials:"same-origin",cache:"no-store",...init,headers});const payload:any=await response.json().catch(()=>({}));if(!response.ok)throw Object.assign(new Error(payload?.message||`خطای ${response.status}`),{status:response.status,code:payload?.error});return payload}
function toast(message:string,tone="success"){document.querySelector(".cwp-toast")?.remove();const el=document.createElement("div");el.className=`cwp-toast ${tone}`;el.textContent=message;document.body.appendChild(el);setTimeout(()=>el.remove(),3600)}
function removePrompt(){document.querySelector(".cwp-prompt")?.remove()}
function closeSheet(){document.querySelector(".cwp-sheet-backdrop")?.remove()}
async function registration(){return navigator.serviceWorker.register(PUSH_SW,{scope:"/"})}
async function currentSubscription(){const reg=await navigator.serviceWorker.ready;return reg.pushManager.getSubscription()}
async function persistSubscription(sub:PushSubscription){const value=sub.toJSON();await requestJson(SUB_API,{method:"POST",body:JSON.stringify({...value,platform:platform()})})}
async function subscribe(config:PushConfig){const reg=await registration();const permission=Notification.permission==="granted"?"granted":await Notification.requestPermission();if(permission!=="granted")throw new Error(permission==="denied"?"اجازه اعلان در تنظیمات مرورگر مسدود شده است.":"برای فعال‌سازی اعلان باید اجازه نمایش اعلان را تأیید کنید.");let sub=await reg.pushManager.getSubscription();if(!sub)sub=await reg.pushManager.subscribe({userVisibleOnly:true,applicationServerKey:decodeKey(config.publicKey)});await persistSubscription(sub);return sub}
async function disable(){const sub=await currentSubscription();if(sub){await requestJson(SUB_API,{method:"DELETE",body:JSON.stringify({endpoint:sub.endpoint})}).catch(()=>undefined);await sub.unsubscribe().catch(()=>false)}toast("اعلان‌های این دستگاه غیرفعال شد.","info");closeSheet();showPrompt(await loadConfig(),true)}
async function testPush(){try{await requestJson(TEST_API,{method:"POST",body:"{}"});toast("اعلان آزمایشی ارسال شد.")}catch(error:any){toast(error?.message||"ارسال اعلان آزمایشی انجام نشد.","error")}}

function showIosInstallGuide(){if(document.querySelector(".cwp-prompt"))return;const box=document.createElement("section");box.className="cwp-prompt install";box.innerHTML=`<button class="cwp-close" type="button" aria-label="بستن">×</button><div class="cwp-icon">🔔</div><div class="cwp-copy"><strong>اعلان‌های سلامت اول روی آیفون</strong><p>برای دریافت اعلان بدون پیامک، ابتدا باشگاه را از Safari با گزینه «Add to Home Screen» به صفحه اصلی اضافه کنید؛ سپس از آیکون باشگاه وارد شوید و اعلان را فعال کنید.</p></div><button class="cwp-primary" type="button">متوجه شدم</button>`;box.querySelectorAll("button").forEach(button=>button.addEventListener("click",()=>box.remove()));document.body.appendChild(box)}

function showPrompt(config:PushConfig,force=false){if(!config.configured||document.querySelector(".cwp-prompt"))return;if(Notification.permission==="denied"&&!force)return;if(isIos()&&!isStandalone()){showIosInstallGuide();return}const box=document.createElement("section");box.className="cwp-prompt";box.innerHTML=`<button class="cwp-close" type="button" aria-label="بستن">×</button><div class="cwp-icon">🔔</div><div class="cwp-copy"><strong>اعلان‌های باشگاه را روی موبایل بگیرید</strong><p>آگهی، قرارداد، آموزش، امتیاز و پیام‌های مهم را حتی وقتی صفحه باز نیست دریافت کنید. پیامک‌های فعلی سلامت اول هم همچنان برقرار می‌مانند.</p></div><button class="cwp-primary" type="button">فعال‌سازی اعلان‌ها</button>`;box.querySelector(".cwp-close")?.addEventListener("click",()=>box.remove());box.querySelector(".cwp-primary")?.addEventListener("click",async event=>{const button=event.currentTarget as HTMLButtonElement;button.disabled=true;button.textContent="در حال فعال‌سازی...";try{await subscribe(config);removePrompt();toast("اعلان‌های موبایل فعال شد؛ پیامک‌ها نیز بدون تغییر باقی ماندند.");setTimeout(()=>void testPush(),500)}catch(error:any){button.disabled=false;button.textContent="فعال‌سازی اعلان‌ها";toast(error?.message||"فعال‌سازی اعلان انجام نشد.","error")}});document.body.appendChild(box)}

async function showSettings(config:PushConfig){closeSheet();const sub=await currentSubscription().catch(()=>null),active=Boolean(sub&&Notification.permission==="granted");const wrap=document.createElement("div");wrap.className="cwp-sheet-backdrop";wrap.innerHTML=`<section class="cwp-sheet"><div class="cwp-sheet-handle"></div><header><div><strong>اعلان‌های موبایل</strong><small>${active?"این دستگاه متصل است":"این دستگاه هنوز متصل نیست"}</small></div><button type="button" class="cwp-sheet-close">×</button></header><div class="cwp-status ${active?"on":"off"}"><span></span><div><b>${active?"اعلان فعال است":"اعلان غیرفعال است"}</b><small>پیامک‌های فعلی مستقل از این تنظیم و همچنان فعال هستند.</small></div></div><div class="cwp-sheet-actions">${active?`<button class="cwp-test" type="button">ارسال اعلان آزمایشی</button><button class="cwp-disable" type="button">غیرفعال‌کردن روی این دستگاه</button>`:`<button class="cwp-enable" type="button">فعال‌سازی اعلان‌ها</button>`}</div></section>`;wrap.addEventListener("mousedown",e=>{if(e.target===wrap)closeSheet()});wrap.querySelector(".cwp-sheet-close")?.addEventListener("click",closeSheet);wrap.querySelector(".cwp-test")?.addEventListener("click",()=>void testPush());wrap.querySelector(".cwp-disable")?.addEventListener("click",()=>void disable());wrap.querySelector(".cwp-enable")?.addEventListener("click",async()=>{try{await subscribe(config);toast("اعلان‌های این دستگاه فعال شد.");closeSheet()}catch(error:any){toast(error?.message||"فعال‌سازی اعلان انجام نشد.","error")}});document.body.appendChild(wrap)}

function installSettingsButton(config:PushConfig){if(document.querySelector(".cwp-settings-button"))return;const button=document.createElement("button");button.type="button";button.className="cwp-settings-button";button.innerHTML="<span>🔔</span><b>اعلان موبایل</b>";button.addEventListener("click",()=>void showSettings(config));document.body.appendChild(button);const sync=()=>{const onNotifications=location.pathname.startsWith("/mobile/notifications");button.classList.toggle("visible",onNotifications)};sync();const originalPush=history.pushState.bind(history),originalReplace=history.replaceState.bind(history);history.pushState=function(...args:any[]){const result=originalPush(...args as [any,string,any]);setTimeout(sync);return result};history.replaceState=function(...args:any[]){const result=originalReplace(...args as [any,string,any]);setTimeout(sync);return result};addEventListener("popstate",sync)}

async function loadConfig():Promise<PushConfig>{const payload:any=await requestJson(CONFIG_API);return payload.data||payload}

async function boot(){if(initialized||booting)return;booting=true;try{const config=await loadConfig();if(!config.configured){initialized=true;return}if(!supported()){if(isIos()&&!isStandalone())showIosInstallGuide();initialized=true;return}await registration();const existing=await currentSubscription();if(existing){await persistSubscription(existing).catch(()=>undefined)}else if(Notification.permission==="granted"){await subscribe(config).catch(()=>undefined)}else if(Notification.permission==="default"){setTimeout(()=>showPrompt(config),900)}installSettingsButton(config);initialized=true}catch(error:any){if(error?.status!==401&&error?.status!==403)console.warn("caregiver_web_push_boot",error?.message||error)}finally{booting=false}}

if(typeof window!=="undefined"){
  void boot();
  const id=window.setInterval(()=>{if(initialized){window.clearInterval(id);return}void boot()},2500);
  window.setTimeout(()=>window.clearInterval(id),120000);
}
