import "./caregiver-requests-v1.css";

const esc=(value:unknown)=>String(value??"").replace(/[&<>"']/g,ch=>({"&":"&amp;","<":"&lt;",">":"&gt;","\"":"&quot;","'":"&#39;"}[ch]||ch));
const fa=(value:unknown)=>Number(value||0).toLocaleString("fa-IR");
const money=(value:unknown)=>`${fa(value)} تومان`;
const dateFa=(value:unknown)=>{const d=new Date(String(value||""));return Number.isNaN(d.getTime())?"—":new Intl.DateTimeFormat("fa-IR-u-ca-persian",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit"}).format(d)};
const statusClass=(s:string)=>["COMPLETED","PAID","APPROVED"].includes(s)?"done":["REJECTED","CANCELLED"].includes(s)?"rejected":"open";
const icon=(type:string)=>type==="SETTLEMENT"?"◉":type==="REFERRAL_LOAN"?"◇":"◆";
const typeLabel=(type:string)=>type==="SETTLEMENT"?"تسویه کیف پول":type==="REFERRAL_LOAN"?"وام معرفی":"تسهیلات";
let loading=false;
async function mount(force=false){
 if(location.pathname.replace(/\/+$/,"")!=="/mobile/benefits")return;const active=document.querySelector(".cv2-tabs button:nth-child(4).active");const target=document.querySelector<HTMLElement>(".cv2-requests");if(!active||!target||loading)return;if(target.dataset.unifiedRequests==="1"&&!force)return;loading=true;target.dataset.unifiedRequests="1";target.innerHTML='<div class="crq1-wrap"><div class="mr-card">در حال دریافت تاریخچه همه درخواست‌ها...</div></div>';
 try{const response=await fetch("/api/caregiver/platform/requests",{credentials:"same-origin",headers:{accept:"application/json"}}),payload:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(String(payload?.error?.message||payload?.message||"دریافت درخواست‌ها انجام نشد."));const data=payload.data||{},items=Array.isArray(data.items)?data.items:[],summary=data.summary||{};const rows=items.map((item:any)=>{const s=String(item.status||"").toUpperCase(),timeline=Array.isArray(item.timeline)?item.timeline:[];return `<article class="crq1-row"><div class="crq1-icon">${icon(String(item.type))}</div><div class="crq1-main"><header><div><small>${esc(typeLabel(String(item.type)))}</small><strong>${esc(item.title||"درخواست")}</strong></div><span class="crq1-status ${statusClass(s)}">${esc(item.statusLabel||item.status||"—")}</span></header><div class="crq1-meta"><span>${esc(money(item.amountToman||0))}</span><span>ثبت: ${esc(dateFa(item.requestedAt))}</span>${item.cycleNumber?`<span>دوره ${esc(fa(item.cycleNumber))}</span>`:""}${item.paymentTrackingNumber?`<span>پیگیری: ${esc(item.paymentTrackingNumber)}</span>`:""}</div>${item.decisionNote?`<p class="crq1-decision">✓ نتیجه بررسی: ${esc(item.decisionNote)}</p>`:""}${timeline.length?`<div class="crq1-timeline">${timeline.map((step:any)=>`<div class="crq1-step"><span class="crq1-dot">✓</span><div><b>${esc(step.label||step.status)}</b><small>${esc(dateFa(step.at))}${step.note?` • ${esc(step.note)}`:""}</small></div></div>`).join("")}</div>`:""}</div></article>`}).join("");target.innerHTML=`<div class="crq1-wrap"><div class="mr-card"><div class="mr-card-head"><div><h3>همه درخواست‌های من</h3><p>تمام درخواست‌های ارسال‌شده از طرف شما به مدیر سامانه، همراه با تاریخچه و نتیجه، در این بخش قابل پیگیری است.</p></div><span class="crq1-total">${esc(fa(summary.total||0))} درخواست</span></div><div class="crq1-summary"><span><b>${esc(fa(summary.open||0))}</b> در جریان</span><span><b>${esc(fa(summary.settlements||0))}</b> تسویه</span><span><b>${esc(fa(summary.referralLoans||0))}</b> وام معرفی</span><span><b>${esc(fa(summary.credits||0))}</b> تسهیلات</span></div></div>${rows||'<div class="mr-card"><strong>هنوز درخواستی ثبت نشده است.</strong><p>درخواست تسویه، وام معرفی و سایر درخواست‌های مالی پس از ثبت اینجا نمایش داده می‌شوند.</p></div>'}</div>`}catch(error:any){target.dataset.unifiedRequests="";target.innerHTML=`<div class="mr-card"><strong>دریافت درخواست‌ها انجام نشد.</strong><p>${esc(error?.message||"")}</p></div>`}finally{loading=false}}
function sync(){setTimeout(()=>void mount(false),0)}
if(typeof window!=="undefined"){addEventListener("popstate",sync);addEventListener("click",event=>{const el=(event.target as HTMLElement|null)?.closest?.(".cv2-tabs button:nth-child(4)");if(el)setTimeout(()=>void mount(true),0);else sync()},true);new MutationObserver(()=>void mount(false)).observe(document.documentElement,{childList:true,subtree:true});sync()}
