import React,{useCallback,useEffect,useState} from "react";
import {Bell,BookOpen,BriefcaseBusiness,ClipboardCheck,Headphones,Megaphone,Smartphone,UsersRound,WalletCards} from "lucide-react";
import {api,dateTimeFa,Empty,ErrorState,fa,Loading,RouteKey,text} from "./caregiver-core-v2";
import "./caregiver-notification-center-v1.css";

export type NotificationItem={id:string;moduleKey:string;kind:string;title:string;body:string;createdAt:string;route:RouteKey;unread:boolean};
export type NotificationState={items:NotificationItem[];unreadByModule:Record<string,number>;unreadTotal:number;generatedAt?:string};
const emptyState:NotificationState={items:[],unreadByModule:{},unreadTotal:0};
const PUSH_SETTINGS_EVENT="salamat:caregiver-push-settings";

export function useCaregiverNotifications(){const [state,setState]=useState<NotificationState>(emptyState),[loading,setLoading]=useState(true);const refresh=useCallback(async()=>{try{const p:any=await api("/api/caregiver/notifications");setState(p.data||emptyState)}finally{setLoading(false)}},[]);useEffect(()=>{void refresh();const id=window.setInterval(()=>void refresh(),60000);return()=>window.clearInterval(id)},[refresh]);const markModuleSeen=useCallback(async(moduleKey:string)=>{if(!moduleKey||moduleKey==="notifications"||moduleKey==="home")return;setState(prev=>({...prev,items:prev.items.map(x=>x.moduleKey===moduleKey?{...x,unread:false}:x),unreadTotal:Math.max(0,prev.unreadTotal-Number(prev.unreadByModule[moduleKey]||0)),unreadByModule:{...prev.unreadByModule,[moduleKey]:0}}));try{await api("/api/caregiver/notifications/read",{method:"POST",body:JSON.stringify({moduleKey})})}catch{}},[]);return{state,loading,refresh,markModuleSeen}}

const iconFor=(kind:string)=>{if(kind==="JOB_AD")return Megaphone;if(kind==="EVALUATION")return ClipboardCheck;if(kind==="SUPPORT")return Headphones;if(kind==="WALLET")return WalletCards;if(kind==="REFERRAL_CONFIRMATION")return UsersRound;if(kind==="CREDIT"||kind==="CONTRACT_POINTS")return BriefcaseBusiness;return BookOpen};
export function NotificationBell({count,onClick}:{count:number;onClick:()=>void}){return <button className="cvn-bell" onClick={onClick} aria-label="اعلان‌ها"><Bell size={20}/>{count>0&&<span>{count>99?"۹۹+":fa(count)}</span>}</button>}
export function ModuleUnreadDot({count}:{count?:number}){return Number(count||0)>0?<span className="cvn-module-dot" aria-label={`${fa(count)} اعلان خوانده‌نشده`}/>:null}

function PushActivationCard(){const open=()=>window.dispatchEvent(new Event(PUSH_SETTINGS_EVENT));return <section className="cvn-push-card"><span className="cvn-push-icon"><Smartphone size={24}/><i>🔔</i></span><span className="cvn-push-copy"><strong>اعلان روی موبایل</strong><small>آگهی‌ها، آموزش، قرارداد، امتیاز و پیام‌های مهم را حتی وقتی باشگاه باز نیست دریافت کنید.</small><em>پیامک‌های فعلی سلامت اول مستقل از این قابلیت و همچنان فعال می‌مانند.</em></span><button type="button" onClick={open}>تنظیم و فعال‌سازی</button></section>}

export function CaregiverNotificationCenter({state,loading,navigate,markSeen,refresh}:{state:NotificationState;loading:boolean;navigate:(route:RouteKey)=>void;markSeen:(moduleKey:string)=>Promise<void>;refresh:()=>Promise<void>}){const [error,setError]=useState("");const open=async(item:NotificationItem)=>{setError("");try{await markSeen(item.moduleKey);navigate(item.route)}catch(e:any){setError(e.message)}};if(error)return <ErrorState message={error} retry={()=>{setError("");void refresh()}}/>;return <div className="cvn-page"><header className="cvn-title"><div><strong>اعلان‌های من</strong><small>اعلان فقط وقتی خوانده می‌شود که وارد ماژول مربوطه شوید.</small></div>{state.unreadTotal>0&&<span>{fa(state.unreadTotal)} جدید</span>}</header><PushActivationCard/>{loading?<Loading label="در حال دریافت اعلان‌ها..."/>:state.items.length?<div className="cvn-list">{state.items.map(item=>{const Icon=iconFor(item.kind);return <button key={item.id} className={`cvn-item ${item.unread?"unread":""}`} onClick={()=>void open(item)}><span className="cvn-kind"><Icon size={20}/>{item.unread&&<i/>}</span><span className="cvn-copy"><strong>{text(item.title)}</strong><small>{text(item.body)}</small><em>{dateTimeFa(item.createdAt)}</em></span></button>})}</div>:<Empty title="اعلان جدیدی ندارید" description="تغییرات کارنامه، آگهی‌ها، مزایا، کیف پول و پشتیبانی اینجا نمایش داده می‌شود."/>}</div>}
