import React,{FormEvent,useState} from "react";
import {createRoot,Root} from "react-dom/client";
import {ArrowRight,BadgeCheck,ShieldCheck,X} from "lucide-react";
import "./mobile-signup-v1.css";

const normalizeDigits=(value:unknown)=>String(value||"").replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/\D/g,"");
const normalizeMobile=(value:unknown)=>{const digits=normalizeDigits(value);if(digits.startsWith("0098"))return `0${digits.slice(4)}`;if(digits.startsWith("98"))return `0${digits.slice(2)}`;if(digits.length===10&&digits.startsWith("9"))return `0${digits}`;return digits};

function Signup({close}:{close:()=>void}){
 const [busy,setBusy]=useState(false),[error,setError]=useState(""),[result,setResult]=useState<any>(null);
 const submit=async(e:FormEvent<HTMLFormElement>)=>{e.preventDefault();const form=e.currentTarget;if(!form.reportValidity())return;const fd=new FormData(form),fullName=String(fd.get("fullName")||"").trim(),mobile=normalizeMobile(fd.get("mobile")),nationalId=normalizeDigits(fd.get("nationalId")),referralCode=normalizeDigits(fd.get("referralCode")),consent=fd.get("consent")==="on";if(fullName.length<3)return setError("نام و نام خانوادگی را کامل وارد کنید.");if(!/^09\d{9}$/.test(mobile))return setError("شماره همراه معتبر نیست.");if(!/^\d{10}$/.test(nationalId))return setError("کد ملی ۱۰ رقمی الزامی است.");if(referralCode&&!/^\d{6}$/.test(referralCode))return setError("کد معرف باید دقیقاً ۶ رقم باشد.");if(!consent)return setError("تأیید صحت اطلاعات الزامی است.");setBusy(true);setError("");try{const response=await fetch("/api/public/caregivers/register",{method:"POST",credentials:"same-origin",cache:"no-store",headers:{"content-type":"application/json","cache-control":"no-cache"},body:JSON.stringify({fullName,name:fullName,mobile,nationalId,referralCode:referralCode||undefined,serviceGroup:String(fd.get("serviceGroup")||"مراقبت سالمند"),city:String(fd.get("city")||"").trim(),birthDate:String(fd.get("birthDate")||"").trim(),skills:String(fd.get("skills")||"").trim(),address:String(fd.get("address")||"").trim(),bio:String(fd.get("bio")||"").trim()})});const payload:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload?.message||"ثبت درخواست عضویت انجام نشد.");setResult({...payload?.data,mobile})}catch(x:any){setError(x?.message||"ثبت درخواست عضویت انجام نشد.")}finally{setBusy(false)}};
 if(result)return <div className="mrs-overlay" role="dialog" aria-modal="true" aria-label="عضویت در شبکه مراقبین"><section className="mrs-card mrs-success"><button className="mrs-close" type="button" onClick={close}><X size={20}/></button><div className="mrs-success-icon"><BadgeCheck size={34}/></div><h1>درخواست عضویت ثبت شد</h1><p>حساب شما در وضعیت <strong>در انتظار تأیید مدیر سامانه</strong> قرار گرفت. پس از تأیید می‌توانید با شماره موبایل و کد ملی خود وارد نسخه React باشگاه شوید.</p><div className="mrs-result"><span>نام کاربری اولیه</span><strong>{result.mobile}</strong>{result.requestCode&&<><span>کد درخواست</span><strong>{result.requestCode}</strong></>}{result.caregiverId&&<><span>شناسه پرونده</span><strong>{result.caregiverId}</strong></>}</div><button type="button" className="mrs-submit" onClick={close}><ArrowRight size={18}/>بازگشت به ورود</button></section></div>;
 return <div className="mrs-overlay" role="dialog" aria-modal="true" aria-label="فرم عضویت مراقب"><section className="mrs-card"><header className="mrs-head"><button className="mrs-close" type="button" onClick={close}><X size={20}/></button><span><ShieldCheck size={20}/></span><div><small>شبکه حرفه‌ای سلامت اول</small><h1>عضویت مراقب</h1><p>درخواست شما ابتدا در انتظار تأیید مدیر سامانه خواهد بود.</p></div></header><form onSubmit={submit} className="mrs-form"><label><span>نام و نام خانوادگی</span><input name="fullName" autoComplete="name" required/></label><label><span>شماره همراه</span><input name="mobile" inputMode="tel" autoComplete="tel" dir="ltr" placeholder="09128668837" required/></label><label><span>کد ملی</span><input name="nationalId" inputMode="numeric" maxLength={10} dir="ltr" required/></label><label><span>کد معرف <em>اختیاری</em></span><input name="referralCode" inputMode="numeric" maxLength={6} dir="ltr" placeholder="۶ رقم"/></label><label><span>گروه خدمتی</span><select name="serviceGroup"><option>مراقبت سالمند</option><option>مراقبت بیمار</option><option>مراقبت کودک</option><option>خدمات تخصصی</option></select></label><label><span>شهر</span><input name="city" placeholder="تهران"/></label><label><span>تاریخ تولد</span><input name="birthDate" placeholder="۱۳۷۰/۰۱/۰۱"/></label><label className="wide"><span>مهارت‌ها</span><input name="skills" placeholder="مراقبت سالمند، همراه بیمار و ..."/></label><label className="wide"><span>نشانی</span><textarea name="address" rows={2}/></label><label className="wide"><span>سوابق و معرفی حرفه‌ای</span><textarea name="bio" rows={3}/></label><label className="mrs-consent wide"><input name="consent" type="checkbox" required/><span>صحت اطلاعات را تأیید می‌کنم و می‌پذیرم فعال‌شدن حساب منوط به تأیید مدیر سامانه است.</span></label>{error&&<div className="mrs-error wide" role="alert">{error}</div>}<button type="submit" className="mrs-submit wide" disabled={busy}>{busy?"در حال ثبت درخواست...":"ثبت درخواست عضویت"}</button></form></section></div>;
}

let mountedRoot:Root|null=null;
function closeSignup(){if(mountedRoot){mountedRoot.unmount();mountedRoot=null}document.getElementById("mobile-react-signup-v1")?.remove()}
function openSignup(){if(mountedRoot)return;const host=document.createElement("div");host.id="mobile-react-signup-v1";document.body.appendChild(host);mountedRoot=createRoot(host);mountedRoot.render(<Signup close={closeSignup}/>)}
function captureJoin(event:Event){const target=event.target instanceof Element?event.target.closest(".mr-join"):null;if(!target)return;event.preventDefault();event.stopPropagation();event.stopImmediatePropagation();openSignup()}
document.addEventListener("click",captureJoin,true);
if(new URL(location.href).searchParams.get("signup")==="1")queueMicrotask(openSignup);

export const mobileReactSignupV1={open:openSignup,close:closeSignup};
