const VERSION="1.0.3";
const OPEN_STATUSES=new Set(["REQUESTED","UNDER_REVIEW","APPROVED"]);
const LEGACY_REFERRAL_CONFIRM_MESSAGE="معرفی تأیید شد و پاداش ۲۰۰ هزار تومانی به کیف پول شما اضافه شد.";
const REFERRAL_CONFIRM_MESSAGE="معرفی تأیید شد. پس از فعال‌شدن حساب مراقب معرفی‌شده، درخواست پاداش ۲۰۰ هزار تومانی برای تأیید مدیر سامانه در اعتبارات مالی قرار می‌گیرد.";
let cache:any=null,loadedAt=0,promise:Promise<any>|null=null,frame=0,installed=false;
const $=<T extends Element=HTMLElement>(selector:string,root:ParentNode=document)=>root.querySelector(selector) as T|null;
const text=(value:unknown)=>String(value??"").trim();
const money=(value:unknown)=>`${Number(value||0).toLocaleString("fa-IR")} تومان`;
function isCaregiverMobile(){return location.pathname==="/mobile"||location.pathname.startsWith("/mobile/")}
function isHome(){return location.pathname==="/mobile"||location.pathname==="/mobile/"}
function isBenefits(){return /^\/mobile\/benefits\/?$/.test(location.pathname)}
async function api(path:string,options:RequestInit={}){const headers=new Headers(options.headers||{});if(typeof options.body==="string"&&!headers.has("content-type"))headers.set("content-type","application/json");const response=await fetch(path,{credentials:"same-origin",cache:"no-store",...options,headers});const raw=await response.text();let payload:any={};try{payload=raw?JSON.parse(raw):{}}catch{payload={message:raw}}if(!response.ok)throw new Error(payload.message||`خطای ${response.status}`);return payload}
async function profile(force=false){if(cache&&!force&&Date.now()-loadedAt<20000)return cache;if(promise)return promise;promise=api("/api/caregiver/platform/financial-profile").then(p=>{cache=p.data||{};loadedAt=Date.now();return cache}).finally(()=>{promise=null});return promise}
function styles(){if($("#cmfa-v1-style"))return;const style=document.createElement("style");style.id="cmfa-v1-style";style.textContent=`
.cmfa-referral{margin:0 0 18px;padding:15px 16px;border-radius:21px;background:linear-gradient(135deg,#087443,#0d9255);color:#fff;display:grid;grid-template-columns:minmax(0,1fr) auto;gap:8px 12px;align-items:center;box-shadow:0 12px 30px rgba(8,116,67,.16)}.cmfa-referral small{grid-column:1/-1;font-size:9px;font-weight:800;opacity:.86}.cmfa-referral strong{font-size:23px;letter-spacing:2px;direction:ltr;text-align:right}.cmfa-referral button{border:0;border-radius:11px;padding:9px 12px;background:#fff;color:#087443;font:900 10px inherit;display:inline-flex;align-items:center;gap:6px;justify-content:center;min-width:92px}.cmfa-referral button:disabled{opacity:.55}.cmfa-loan{margin:0 0 12px;padding:14px;border:1px solid #bfe1ce;border-radius:17px;background:linear-gradient(145deg,#f1faf5,#fff);display:flex;align-items:center;justify-content:space-between;gap:12px}.cmfa-loan>div{min-width:0}.cmfa-loan strong{display:block;color:#075f38;font-size:12px}.cmfa-loan small{display:block;margin-top:5px;color:#65776d;font-size:9px;line-height:1.9}.cmfa-loan button{border:0;border-radius:11px;padding:10px 12px;background:#087443;color:#fff;font:900 10px inherit;white-space:nowrap;min-height:40px}.cmfa-loan button:disabled{opacity:.55}.cmfa-loan.requested{background:#fff8e8;border-color:#ead9aa}.cmfa-loan.requested strong{color:#7a5a10}.cmfa-toast{position:fixed;left:16px;right:16px;bottom:calc(96px + env(safe-area-inset-bottom));z-index:9999;padding:11px 13px;border-radius:13px;background:#173d2c;color:#fff;text-align:center;font:800 10px/1.8 inherit;box-shadow:0 12px 35px rgba(0,0,0,.18)}.cmfa-toast.error{background:#a42f42}@media(min-width:760px){.cmfa-referral,.cmfa-loan{display:none!important}}
`;document.head.appendChild(style)}
function toast(message:string,error=false){document.querySelectorAll(".cmfa-toast").forEach(x=>x.remove());const node=document.createElement("div");node.className=`cmfa-toast${error?" error":""}`;node.textContent=message;document.body.appendChild(node);window.setTimeout(()=>node.remove(),2800)}
async function copy(value:string,button:HTMLButtonElement){if(!value)return;try{await navigator.clipboard.writeText(value)}catch{const ta=document.createElement("textarea");ta.value=value;ta.style.position="fixed";ta.style.opacity="0";document.body.appendChild(ta);ta.select();document.execCommand("copy");ta.remove()}const old=button.textContent;button.textContent="کپی شد ✓";window.setTimeout(()=>{button.textContent=old||"کپی کد"},1500)}
function referralCard(){const cards=Array.from(document.querySelectorAll<HTMLElement>("#cmfa-referral-home"));cards.slice(1).forEach(node=>node.remove());return cards[0]||null}
async function renderReferral(){const launcher=$(".cv4-mobile-launcher");if(!launcher||!isHome()){document.querySelectorAll("#cmfa-referral-home").forEach(node=>node.remove());return}if($(".cv2-referral")){document.querySelectorAll("#cmfa-referral-home").forEach(node=>node.remove());return}let card=referralCard();if(card)return;try{const data=await profile();if(!isHome()||!document.contains(launcher))return;card=referralCard();if(card)return;const code=text(data?.caregiver?.referralCode);if(!code)return;card=document.createElement("section");card.id="cmfa-referral-home";card.className="cmfa-referral";card.innerHTML=`<small>کد معرفی یکتای شما</small><strong>${code.replace(/[^0-9]/g,"")||code}</strong><button type="button" aria-label="کپی کد معرفی"><span>کپی کد</span></button>`;const button=$("button",card) as HTMLButtonElement|null;button?.addEventListener("click",()=>void copy(code,button));launcher.insertBefore(card,launcher.firstChild);referralCard()}catch{}}
function openRequest(data:any){return (data?.wallet?.creditRequests||[]).find((x:any)=>OPEN_STATUSES.has(String(x.status||"").toUpperCase()))}
function bestEligible(data:any){const loans=Array.isArray(data?.loans)?data.loans.filter((x:any)=>Boolean(x?.eligible)&&String(x?.key||"")!=="REFERRAL_LOAN_10"):[];if(loans.length)return [...loans].sort((a:any,b:any)=>Number(b.amountToman||0)-Number(a.amountToman||0))[0];if(data?.allowance?.eligible)return {...data.allowance,key:data.allowance.key||"ASSISTANCE_2M",_allowance:true};return null}
async function requestBenefit(item:any,button:HTMLButtonElement){if(button.disabled)return;const title=item?._allowance?"کمک‌هزینه":"وام",amountToman=Number(item?.amountToman||0);if(!confirm(`تقاضای ${title}${amountToman?` به مبلغ ${money(amountToman)}`:""} برای بررسی واحد اعتبارات مالی ارسال شود؟`))return;button.disabled=true;button.textContent="در حال ارسال...";try{await api("/api/caregiver/platform/credit-requests",{method:"POST",body:JSON.stringify({benefitKey:item.key||"ASSISTANCE_2M"})});cache=null;loadedAt=0;toast("درخواست شما ثبت شد و برای بررسی به واحد اعتبارات مالی ارسال شد.");await renderLoanCta(true)}catch(e:any){toast(e.message||"ثبت درخواست انجام نشد.",true);button.disabled=false;button.textContent=item?._allowance?"تقاضای کمک‌هزینه":"تقاضای وام"}}
async function renderLoanCta(force=false){const root=$(".cv2-benefits");if(!root||!isBenefits()){$("#cmfa-loan-cta")?.remove();return}try{const data=await profile(force),open=openRequest(data),item=bestEligible(data);let card=$("#cmfa-loan-cta");if(!item&&!open){card?.remove();return}if(!card){card=document.createElement("section");card.id="cmfa-loan-cta";const tabs=$(".cv2-tabs-card",root);if(tabs)root.insertBefore(card,tabs);else root.appendChild(card)}card.className=`cmfa-loan${open?" requested":""}`;if(open){const label=String(open.status||"").toUpperCase()==="APPROVED"?"تأیید شده":String(open.status||"").toUpperCase()==="UNDER_REVIEW"?"در حال بررسی":"در انتظار بررسی";card.innerHTML=`<div><strong>درخواست تسهیلات شما ${label} است</strong><small>${money(open.requestedAmountToman)} • نتیجه هر تصمیم از طریق اعلان‌های پنل به شما اطلاع داده می‌شود.</small></div><button type="button" disabled>درخواست در جریان</button>`;return}const allowance=Boolean(item?._allowance),label=allowance?"کمک‌هزینه":"وام";card.innerHTML=`<div><strong>شما واجد شرایط ${label} شده‌اید</strong><small>${text(item.title)||label} • ${money(item.amountToman)}. درخواست پس از ثبت برای نقش دارای اختیار «اعتبارات مالی» ارسال می‌شود.</small></div><button type="button">${allowance?"تقاضای کمک‌هزینه":"تقاضای وام"}</button>`;const button=$("button",card) as HTMLButtonElement|null;button?.addEventListener("click",()=>void requestBenefit(item,button))}catch{}}
function normalizeReferralConfirmationCopy(){if(!isBenefits())return;document.querySelectorAll<HTMLElement>(".cv2-benefits .mr-card").forEach(node=>{if(text(node.textContent)===LEGACY_REFERRAL_CONFIRM_MESSAGE)node.textContent=REFERRAL_CONFIRM_MESSAGE})}
async function render(force=false){if(!isCaregiverMobile())return;styles();await Promise.all([renderReferral(),renderLoanCta(force)]);normalizeReferralConfirmationCopy()}
function schedule(){if(frame)return;frame=requestAnimationFrame(()=>{frame=0;void render(false)})}
function install(){if(installed)return;installed=true;styles();const root=$("#mobile-react-root");if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true});window.addEventListener("popstate",schedule,{passive:true});window.addEventListener("salamat-authenticated",schedule as EventListener,{passive:true});schedule();(window as any).SalamatCaregiverFinancialActionsV1={version:VERSION,refresh:()=>render(true)}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
export {};
