type TabKey="technical"|"analysis"|"credit"|"activity"|"training_exam";
const VERSION="1.3.0";
const TABS:Array<{key:TabKey;label:string}>=[
 {key:"technical",label:"کارنامه فنی"},{key:"analysis",label:"تحلیل فنی"},{key:"credit",label:"رتبه‌بندی اعتباری"},{key:"activity",label:"خلاصه فعالیت"},{key:"training_exam",label:"آزمون‌های آموزش"},
];
const ICONS:Record<TabKey,string>={
 technical:`<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M8 4.5h8M9 3h6a1 1 0 0 1 1 1v2H8V4a1 1 0 0 1 1-1Z"/><path d="M6.5 5.5h11a2 2 0 0 1 2 2v11a2 2 0 0 1-2 2h-11a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2Z"/><path d="M8 14h2l1.2-3 2 6 1.3-3H17"/></svg>`,
 analysis:`<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 18.5V14l3-3 3 2 4.5-5 3.5 2.5"/><path d="M15.5 8H19v3.5"/><path d="M5 5.5h3M6.5 4v3"/><path d="M5 20h14"/></svg>`,
 credit:`<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M12 3.5 19 6v5.2c0 4.4-2.8 7.6-7 9.3-4.2-1.7-7-4.9-7-9.3V6l7-2.5Z"/><path d="m12 7.4 1.25 2.55 2.8.4-2.03 1.98.48 2.8L12 13.82l-2.5 1.31.48-2.8-2.03-1.98 2.8-.4L12 7.4Z"/></svg>`,
 activity:`<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M8.5 7V5.5A1.5 1.5 0 0 1 10 4h4a1.5 1.5 0 0 1 1.5 1.5V7"/><path d="M5 7h14a2 2 0 0 1 2 2v9a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2V9a2 2 0 0 1 2-2Z"/><path d="M3 12.5c2.5 1.4 5.5 2.1 9 2.1s6.5-.7 9-2.1M10.2 14.4v1.8h3.6v-1.8"/></svg>`,
 training_exam:`<svg viewBox="0 0 24 24" fill="none" aria-hidden="true"><path d="M5 4.5h14v15H5z"/><path d="M8 8h8M8 12h4M8 16h3"/><path d="m14.5 15 1.4 1.4 2.6-3"/></svg>`,
};
let active:TabKey="technical",frame=0,installed=false,examData:any=null,examError="",examPromise:Promise<void>|null=null;
const text=(value:unknown)=>String(value??"").trim();
const esc=(value:unknown)=>text(value).replace(/[&<>"']/g,char=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[char]||char));
const fa=(value:unknown)=>Number(value||0).toLocaleString("fa-IR");
const dateFa=(value:unknown)=>{const raw=text(value);if(!raw)return"—";const d=new Date(`${raw}T00:00:00`);return Number.isNaN(d.getTime())?raw:d.toLocaleDateString("fa-IR")};
const isScorecard=()=>/^\/mobile\/scorecard\/?$/.test(location.pathname)||/^\/mobile\/admin\/(?:caregivers|job_ads)(?:\/.*)?$/.test(location.pathname)||/^\/app\/job_ads\/?$/.test(location.pathname);
const sectionOf=(node:Element):TabKey|"identity"|"tabs"|"unknown"=>{if(node.id==="cmsc-scorecard-tabs")return"tabs";if(node.id==="cmsc-training-exams")return"training_exam";if(node.classList.contains("cs-identity"))return"identity";if(node.classList.contains("cs-primary-metrics"))return"technical";const heading=text(node.querySelector(".cs-section-head h3")?.textContent);if(heading.includes("نظام ارزیابی")||heading.includes("رتبه حرفه‌ای"))return"technical";if(heading.includes("تحلیل نقاط قوت")||heading.includes("تحلیل فنی"))return"analysis";if(heading.includes("رتبه‌بندی اعتباری")||heading.includes("توان مالی"))return"credit";if(heading.includes("خلاصه فعالیت حرفه‌ای")||heading.includes("تاریخچه ارزیابی"))return"activity";return"unknown"};
function ensureEmpty(root:HTMLElement){let empty=root.querySelector<HTMLElement>("#cmsc-analysis-empty");const hasAnalysis=Array.from(root.children).some(node=>sectionOf(node)==="analysis");if(hasAnalysis){empty?.remove();return}if(!empty){empty=document.createElement("section");empty.id="cmsc-analysis-empty";empty.className="cmsc-analysis-empty";empty.dataset.cmscSection="analysis";empty.innerHTML="<strong>تحلیل فنی هنوز آماده نیست</strong><small>پس از ثبت معیارهای کافی در نظام ارزیابی، تحلیل نقاط قوت و زمینه‌های قابل بهبود در این تب نمایش داده می‌شود.</small>";root.appendChild(empty)}empty.hidden=active!=="analysis"}
async function loadExamData(){if(examPromise)return examPromise;examPromise=(async()=>{try{const response=await fetch("/api/training/exam-results",{credentials:"same-origin",cache:"no-store"});const payload:any=await response.json().catch(()=>({}));if(!response.ok)throw new Error(payload.message||`خطای ${response.status}`);examData=payload.data||{};examError=""}catch(error:any){examError=error?.message||"دریافت نتایج آزمون انجام نشد."}finally{examPromise=null;schedule()}})();return examPromise}
function examMarkup(){if(examError)return `<div class="cmsc-exam-state error"><strong>دریافت نتایج آزمون انجام نشد</strong><small>${esc(examError)}</small></div>`;if(!examData)return '<div class="cmsc-exam-state"><strong>در حال دریافت نتایج آزمون‌ها...</strong></div>';const courses=Array.isArray(examData.courses)?examData.courses:[],results=Array.isArray(examData.results)?examData.results:[];const current=courses.length?courses.map((course:any)=>{const r=course.latestResult,url=text(course.examUrl);return `<article class="cmsc-exam-row"><div><strong>${esc(course.title||"آموزش")}</strong><small>${r?`${fa(r.score)} از ۲۰ • آزمون ${dateFa(r.examDate)} • اعتبار تا ${dateFa(r.validUntil)}`:"هنوز نتیجه آزمون ثبت نشده"}</small></div><span class="${r?.validityStatus==="VALID"?"valid":"expired"}">${r?r.validityStatus==="VALID"?"معتبر":"منقضی":"بدون نتیجه"}</span>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer">ورود به آزمون</a>`:""}</article>`}).join(""):'<div class="cmsc-exam-state"><strong>هنوز آموزشی برای شما تخصیص داده نشده است.</strong></div>';const history=results.length?results.map((r:any)=>`<article class="cmsc-exam-history"><div><strong>${esc(r.courseTitle||"آموزش")}</strong><small>${dateFa(r.examDate)} • معتبر تا ${dateFa(r.validUntil)}</small></div><b>${fa(r.score)} / ۲۰</b></article>`).join(""):'<div class="cmsc-exam-state"><small>هنوز نتیجه آزمونی در کارنامه ثبت نشده است.</small></div>';return `<div class="cmsc-exam-head"><div><strong>آزمون‌های آموزش</strong><small>نمره هر آزمون از ۲۰ است و هر نوبت یک سال از تاریخ آزمون اعتبار دارد.</small></div><span>اعتبار ۱ سال</span></div><div class="cmsc-exam-list">${current}</div><div class="cmsc-exam-history-title">تاریخچه نوبت‌های آزمون</div><div class="cmsc-exam-history-list">${history}</div>`}
function ensureTrainingExams(root:HTMLElement){let section=root.querySelector<HTMLElement>("#cmsc-training-exams");if(!section){section=document.createElement("section");section.id="cmsc-training-exams";section.className="cmsc-training-exams";section.dataset.cmscSection="training_exam";root.appendChild(section)}const markup=examMarkup();if(section.innerHTML!==markup)section.innerHTML=markup;section.hidden=active!=="training_exam";if(active==="training_exam"&&!examData&&!examError)void loadExamData()}
function ensureTabs(root:HTMLElement){let nav=root.querySelector<HTMLElement>("#cmsc-scorecard-tabs");if(nav)return nav;nav=document.createElement("nav");nav.id="cmsc-scorecard-tabs";nav.className="cmsc-scorecard-tabs";nav.setAttribute("aria-label","بخش‌های کارنامه مراقب");nav.setAttribute("role","tablist");for(const item of TABS){const button=document.createElement("button");button.type="button";button.dataset.tab=item.key;button.setAttribute("role","tab");button.setAttribute("aria-label",item.label);button.innerHTML=`<span class="cmsc-tab-icon" aria-hidden="true">${ICONS[item.key]}</span><span class="cmsc-tab-label">${item.label}</span>`;button.addEventListener("click",()=>{active=item.key;renderRoot(root);nav?.scrollIntoView({block:"nearest",behavior:"smooth"})});nav.appendChild(button)}const identity=Array.from(root.children).find(node=>sectionOf(node)==="identity");if(identity?.nextSibling)root.insertBefore(nav,identity.nextSibling);else root.prepend(nav);return nav}
function renderRoot(root:HTMLElement){root.classList.add("cmsc-scorecard-tabbed");const nav=ensureTabs(root);ensureTrainingExams(root);nav.querySelectorAll<HTMLButtonElement>("button[data-tab]").forEach(button=>{const selected=button.dataset.tab===active;button.classList.toggle("active",selected);button.setAttribute("aria-selected",selected?"true":"false");button.tabIndex=selected?0:-1});Array.from(root.children).forEach(node=>{if(!(node instanceof HTMLElement))return;const section=sectionOf(node);if(section==="identity"||section==="tabs"){node.hidden=false;return}if(section==="unknown")return;node.dataset.cmscSection=section;node.hidden=section!==active});ensureEmpty(root)}
function render(){if(!isScorecard())return;const roots=document.querySelectorAll<HTMLElement>(".caregiver-self-scorecard");if(!roots.length)return;roots.forEach(renderRoot)}
function schedule(){if(frame)return;frame=requestAnimationFrame(()=>{frame=0;render()})}
function install(){if(installed)return;installed=true;const root=document.querySelector("#mobile-react-root,#mobile-admin-root,#desktop-react-root");if(root)new MutationObserver(schedule).observe(root,{childList:true,subtree:true});window.addEventListener("popstate",schedule,{passive:true});window.addEventListener("salamat-admin-route-v2",schedule as EventListener,{passive:true});schedule();(window as any).SalamatCaregiverScorecardTabsV1={version:VERSION,refresh:render,reloadTrainingExams:()=>{examData=null;examError="";return loadExamData()}}}
if(document.readyState==="loading")document.addEventListener("DOMContentLoaded",install,{once:true});else install();
export {};
