type JobAdCriteria={id:string;workWeekdays:string[];caregiverGender:string|null};
const WEEKDAY_LABELS:Record<string,string>={SAT:'شنبه',SUN:'یکشنبه',MON:'دوشنبه',TUE:'سه‌شنبه',WED:'چهارشنبه',THU:'پنجشنبه',FRI:'جمعه'};
const DEFAULT_WEEKDAYS=['SAT','SUN','MON','TUE','WED','THU'];
let latestAds:JobAdCriteria[]=[],latestDetail:JobAdCriteria|null=null,scheduled=false;
const fa=(value:number)=>Number(value||0).toLocaleString('fa-IR');
function weekdays(value:unknown){const items=Array.isArray(value)?value.map(x=>String(x).toUpperCase()).filter(x=>WEEKDAY_LABELS[x]):[];return items.length?items:DEFAULT_WEEKDAYS}
function criteria(ad:any):JobAdCriteria{return{id:String(ad?.id||''),workWeekdays:weekdays(ad?.workWeekdays),caregiverGender:['FEMALE','MALE'].includes(String(ad?.caregiverGender||'').toUpperCase())?String(ad.caregiverGender).toUpperCase():null}}
function genderLabel(value:string|null){return value==='FEMALE'?'زن':value==='MALE'?'مرد':'تعیین نشده'}
function weekdayText(days:string[]){return days.map(day=>WEEKDAY_LABELS[day]||day).join('، ')}
function criterionMarkup(item:JobAdCriteria,detail=false){const days=weekdays(item.workWeekdays);return `<div class="sal-cja-criterion sal-cja-days"><span>${fa(days.length)} روز در هفته</span><small>${weekdayText(days)}</small></div><div class="sal-cja-criterion sal-cja-gender"><span>مراقب موردنیاز</span><strong>${genderLabel(item.caregiverGender)}</strong></div>${detail?'<div class="sal-cja-detail-note">روزهای حضور و جنسیت موردنیاز بخشی از شرایط همین پرونده هستند.</div>':''}`}
function adTime(ad:any){const value=Date.parse(String(ad?.publishedAt||ad?.createdAt||''));return Number.isFinite(value)?value:0}
function prioritizeAds(rows:any[]){return [...rows].sort((a,b)=>{const aApplied=Number(a?.applicationCount||0)>0,bApplied=Number(b?.applicationCount||0)>0;if(aApplied!==bApplied)return aApplied?1:-1;const points=Number(b?.contractPoints||0)-Number(a?.contractPoints||0);if(points)return points;const recent=adTime(b)-adTime(a);if(recent)return recent;return String(b?.id||'').localeCompare(String(a?.id||''))})}

function injectStyle(){if(document.getElementById('sal-cja-experience-style'))return;const style=document.createElement('style');style.id='sal-cja-experience-style';style.textContent=`
.cja-page .cja-list{gap:14px}.cja-page .cja-card{position:relative;overflow:hidden;border:1px solid #d6e8df!important;border-radius:24px!important;padding:16px!important;background:linear-gradient(155deg,#fff 0%,#fbfefc 62%,#f1faf5 100%)!important;box-shadow:0 13px 34px rgba(18,74,49,.08)!important;transition:transform .18s ease,box-shadow .18s ease,border-color .18s ease}.cja-page .cja-card:before{content:'';position:absolute;inset:0 0 auto;height:4px;background:linear-gradient(90deg,#087443,#16a463,#79cf9e)}.cja-page .cja-card:hover{transform:translateY(-2px);border-color:#b8ddc9!important;box-shadow:0 17px 42px rgba(18,74,49,.12)!important}.cja-page .cja-card:active{transform:scale(.992)}.cja-page .cja-card-top{align-items:start}.cja-page .cja-card .cja-icon{background:linear-gradient(145deg,#087443,#15a05f)!important;color:#fff!important;box-shadow:0 8px 18px rgba(8,116,67,.18)}.cja-page .cja-card .cja-condition{background:#f3f7f5!important}.cja-page .cja-card .cja-salary{padding:8px 10px!important;background:linear-gradient(135deg,#e4f8ed,#f8fcfa)!important;box-shadow:inset 0 0 0 1px rgba(8,116,67,.03)}.cja-page .cja-card>p{margin:12px 0!important;padding:10px 11px;border-radius:13px;background:rgba(255,255,255,.75);color:#53695e!important}.cja-page .cja-card footer{margin-top:2px;padding-top:11px!important}.sal-cja-criteria{display:grid;grid-template-columns:minmax(0,1.55fr) minmax(120px,.8fr);gap:8px;margin:11px 0 2px}.sal-cja-criterion{min-width:0;border:1px solid #dce9e3;border-radius:13px;background:#fff;padding:9px 10px;text-align:right}.sal-cja-criterion span,.sal-cja-criterion small,.sal-cja-criterion strong{display:block!important}.sal-cja-criterion span{font-size:9px;font-weight:950;color:#254c3a}.sal-cja-criterion small{margin-top:4px!important;font-size:8px!important;line-height:1.7!important;color:#718178!important}.sal-cja-gender{background:linear-gradient(135deg,#f5f8ff,#fbfcff);border-color:#dbe3f1}.sal-cja-gender span{color:#536582}.sal-cja-gender strong{margin-top:4px;font-size:11px;color:#273e65}.sal-cja-detail-criteria{display:grid;grid-template-columns:minmax(0,1.5fr) minmax(120px,.8fr);gap:8px}.sal-cja-detail-criteria .sal-cja-criterion{padding:11px 12px}.sal-cja-detail-note{grid-column:1/-1;padding:8px 10px;border-radius:11px;background:#f3f8f5;color:#64796e;font-size:8.5px;line-height:1.8}.cja-modal .sal-cja-detail-criteria{margin-top:-2px}
@media(max-width:620px){.cja-page .cja-card{border-radius:21px!important;padding:14px!important}.sal-cja-criteria,.sal-cja-detail-criteria{grid-template-columns:1fr 115px}.sal-cja-criterion{padding:8px 9px}.sal-cja-days small{white-space:normal}.sal-cja-gender strong{font-size:10px}}
`;document.head.appendChild(style)}
function decorateCard(card:HTMLElement,item:JobAdCriteria){card.dataset.salJobAdId=item.id;if(card.querySelector(':scope > .sal-cja-criteria'))return;const box=document.createElement('div');box.className='sal-cja-criteria';box.setAttribute('aria-label','شرایط حضور و جنسیت مراقب');box.innerHTML=criterionMarkup(item);const paragraph=card.querySelector(':scope > p'),footer=card.querySelector(':scope > footer');if(paragraph)card.insertBefore(box,paragraph);else if(footer)card.insertBefore(box,footer);else card.appendChild(box)}
function decorateDetail(modal:HTMLElement,item:JobAdCriteria){const existing=modal.querySelector(':scope > .sal-cja-detail-criteria');if(existing){if(existing.getAttribute('data-ad')===item.id)return;existing.remove()}const box=document.createElement('div');box.className='sal-cja-detail-criteria';box.setAttribute('data-ad',item.id);box.setAttribute('aria-label','شرایط موردنیاز آگهی');box.innerHTML=criterionMarkup(item,true);const head=modal.querySelector(':scope > .cja-detail-head');if(head)head.insertAdjacentElement('afterend',box);else modal.prepend(box)}
function scan(){scheduled=false;injectStyle();const cards=[...document.querySelectorAll<HTMLElement>('.cja-list .cja-card')];cards.forEach((card,index)=>{const item=latestAds[index];if(item)decorateCard(card,item)});const modal=document.querySelector<HTMLElement>('.cja-modal');if(modal&&latestDetail)decorateDetail(modal,latestDetail)}
function schedule(){if(scheduled)return;scheduled=true;requestAnimationFrame(scan)}
new MutationObserver(schedule).observe(document.documentElement,{childList:true,subtree:true});schedule();

const nativeFetch=window.fetch.bind(window);
window.fetch=async(input:RequestInfo|URL,init?:RequestInit)=>{
 const raw=typeof input==='string'?input:input instanceof URL?input.toString():input.url,url=new URL(raw,location.origin),method=String(init?.method||(input instanceof Request?input.method:'GET')).toUpperCase();
 const response=await nativeFetch(input as any,init);
 if(method==='GET'&&url.origin===location.origin&&url.pathname==='/api/caregiver/job-ads'&&response.ok){try{const payload:any=await response.clone().json();if(Array.isArray(payload?.data?.ads)){payload.data.ads=prioritizeAds(payload.data.ads);latestAds=payload.data.ads.map(criteria);schedule();const headers=new Headers(response.headers);headers.delete('content-length');headers.set('cache-control','private, no-store, max-age=0');return new Response(JSON.stringify(payload),{status:response.status,statusText:response.statusText,headers})}}catch{}}
 else if(method==='GET'&&url.origin===location.origin&&/^\/api\/caregiver\/job-ads\/[^/]+$/.test(url.pathname)&&response.ok){try{const payload:any=await response.clone().json();latestDetail=criteria(payload?.data?.ad||{});schedule()}catch{}}
 return response;
};

export {};
