function injectStyle(){if(document.getElementById('sal-job-applicant-status-style'))return;const style=document.createElement('style');style.id='sal-job-applicant-status-style';style.textContent=`
.maj-applicant.sal-app-rejected{border-color:#fecaca!important;background:linear-gradient(135deg,#fff7f7,#fff1f2)!important;box-shadow:0 8px 20px rgba(185,28,28,.06)}.maj-applicant.sal-app-contracted{border-color:#bbf7d0!important;background:linear-gradient(135deg,#f3fff8,#ecfdf5)!important;box-shadow:0 8px 20px rgba(5,150,105,.07)}.maj-applicant.sal-app-dispatched{border-color:#fde68a!important;background:linear-gradient(135deg,#fffdf3,#fffbeb)!important;box-shadow:0 8px 20px rgba(180,83,9,.06)}
.maj-applicant.sal-app-rejected .maj-applicant-person small,.maj-applicant.sal-app-contracted .maj-applicant-person small,.maj-applicant.sal-app-dispatched .maj-applicant-person small{display:inline-flex!important;width:max-content;margin-top:5px;padding:4px 8px;border-radius:999px;font-weight:950!important}.maj-applicant.sal-app-rejected .maj-applicant-person small{background:#fee2e2;color:#b91c1c!important}.maj-applicant.sal-app-contracted .maj-applicant-person small{background:#d1fae5;color:#047857!important}.maj-applicant.sal-app-dispatched .maj-applicant-person small{background:#fef3c7;color:#92400e!important}
.maj-applicant.sal-app-rejected{border-inline-start-width:4px!important}.maj-applicant.sal-app-contracted{border-inline-start-width:4px!important}.maj-applicant.sal-app-dispatched{border-inline-start-width:4px!important}
`;document.head.appendChild(style)}
function classify(label:string){const value=label.replace(/\s+/g,' ').trim();if(value.includes('رد'))return'sal-app-rejected';if(value.includes('در قرارداد'))return'sal-app-contracted';if(value.includes('اعزام'))return'sal-app-dispatched';return''}
function scan(){injectStyle();document.querySelectorAll<HTMLElement>('.maj-applicant').forEach(row=>{row.classList.remove('sal-app-rejected','sal-app-contracted','sal-app-dispatched');const label=row.querySelector<HTMLElement>('.maj-applicant-person small')?.textContent||'',status=classify(label);if(status)row.classList.add(status)})}
scan();new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true,characterData:true});
export {};
