type Rule={label:string;normal:number;temporary:number};
const RULES:Record<string,Record<string,Rule>>={
 ELDERLY:{HEALTHY:{label:"سالم",normal:80,temporary:3},WALKER:{label:"واکری",normal:90,temporary:4},DIAPER:{label:"پوشکی",normal:130,temporary:8},BEDPAN:{label:"لگنی",normal:150,temporary:10},GAVAGE:{label:"گاواژ",normal:160,temporary:11},PARKINSON:{label:"پارکینسون",normal:170,temporary:12},ALZHEIMER:{label:"آلزایمر",normal:200,temporary:15}},
 CHILD:{MOTHER_ASSISTANT:{label:"مادریار",normal:120,temporary:7},CHILD_CARE:{label:"کودکیار",normal:140,temporary:9}},
 HOUSEKEEPING:{HOUSEHOLD:{label:"امور منزل",normal:110,temporary:6}},
};
const fa=(v:number)=>Number(v||0).toLocaleString("fa-IR");
const digits=(value:string)=>String(value||"").replace(/[۰-۹]/g,d=>String("۰۱۲۳۴۵۶۷۸۹".indexOf(d))).replace(/[٠-٩]/g,d=>String("٠١٢٣٤٥٦٧٨٩".indexOf(d))).replace(/[^0-9]/g,"");
let isAdmin=false,installed=false;

function injectStyle(){if(document.getElementById("sal-job-points-style"))return;const style=document.createElement("style");style.id="sal-job-points-style";style.textContent=`
.sal-job-condition-label>span,.sal-job-points-title{font-weight:900}.sal-job-points-card{grid-column:1/-1;position:relative;overflow:hidden;border:1px solid #c9e4d5;border-radius:18px;padding:14px 16px;background:linear-gradient(145deg,#f3faf6 0%,#ffffff 72%);color:#123d2a;display:grid;grid-template-columns:minmax(0,1fr) auto;grid-template-areas:"label score" "help score";gap:3px 14px;align-items:center;box-shadow:0 8px 24px rgba(8,116,67,.07)}.sal-job-points-card:before{content:"";position:absolute;inset:0 auto 0 0;width:4px;background:#087443}.sal-job-points-title{grid-area:label;font-size:11px;color:#48665a}.sal-job-points-card strong{grid-area:score;font-size:24px;font-weight:950;color:#087443;white-space:nowrap;letter-spacing:-.4px}.sal-job-points-card small{grid-area:help;font-size:9.5px;line-height:1.9;color:#667d72}.sal-job-points-card[data-ready="0"] strong{color:#7e8d85;font-size:15px}.sal-job-special{grid-column:1/-1;border:1px solid #cfe4d7;border-radius:16px;padding:12px;background:#f1f9f5;display:grid;gap:10px}.sal-job-special label{display:flex!important;align-items:center;gap:8px!important}.sal-job-special input[type=checkbox]{width:18px!important;height:18px!important;min-height:18px!important}.sal-job-special input[type=number]{min-height:44px}.sal-job-special-note{font-size:9px;color:#60756a;line-height:1.9}.sal-job-condition-help{display:block;margin-top:4px;font-size:9px;color:#7b887f;line-height:1.8}@media(max-width:899px){.sal-job-points-card{padding:13px 14px;border-radius:16px;grid-template-columns:minmax(0,1fr) auto}.sal-job-points-card strong{font-size:21px}.sal-job-points-card small,.sal-job-condition-help,.sal-job-special-note{font-size:9.5px}.sal-job-special{padding:12px;border-radius:15px}}
`;document.head.appendChild(style)}

function calc(contractType:string,condition:string,shiftType:string,duration:number){const rule=RULES[contractType]?.[condition];if(!rule||duration<=0)return null;const temporary=shiftType==="TEMPORARY",basis=temporary?10:180,base=temporary?rule.temporary:rule.normal;return {points:Math.max(1,Math.round(base*duration/basis)),basis,base,label:rule.label}}
function formState(form:HTMLFormElement){const type=form.querySelector<HTMLSelectElement>('select[name="contractType"]'),shift=form.querySelector<HTMLSelectElement>('select[name="shiftType"]'),duration=form.querySelector<HTMLInputElement>('[name="durationDays"]'),condition=form.querySelector<HTMLSelectElement>('[data-sal-job-condition]'),specialToggle=form.querySelector<HTMLInputElement>('[data-sal-job-special-toggle]'),specialInput=form.querySelector<HTMLInputElement>('[data-sal-job-special-value]');const automatic=calc(String(type?.value||""),String(condition?.value||""),String(shift?.value||""),Number(digits(duration?.value||"")));return {type,shift,duration,condition,specialToggle,specialInput,automatic}}

function updateConditionOptions(form:HTMLFormElement,force=false){const {type,condition}=formState(form);if(!type||!condition)return;const rules=RULES[type.value]||{},current=condition.value;if(force||condition.dataset.forType!==type.value){condition.innerHTML="";condition.dataset.forType=type.value;const entries=Object.entries(rules);if(entries.length){for(const [key,rule] of entries){const o=document.createElement("option");o.value=key;o.textContent=rule.label;condition.appendChild(o)}condition.disabled=false;if(rules[current])condition.value=current}else{const o=document.createElement("option");o.value="";o.textContent="برای بیمار مبنای خودکار تعریف نشده";condition.appendChild(o);condition.disabled=true}}
}
function refresh(form:HTMLFormElement,forceOptions=false){updateConditionOptions(form,forceOptions);const state=formState(form),card=form.querySelector<HTMLElement>('[data-sal-job-points-card]'),hidden=form.querySelector<HTMLInputElement>('[data-sal-job-points-hidden]'),specialBox=form.querySelector<HTMLElement>('[data-sal-job-special-box]');if(!card||!hidden)return;const specialOn=Boolean(isAdmin&&state.specialToggle?.checked),specialValue=Math.trunc(Number(state.specialInput?.value||0)),finalPoints=specialOn&&specialValue>0?specialValue:Number(state.automatic?.points||0);hidden.value=String(finalPoints||0);card.dataset.ready=finalPoints>0?"1":"0";card.dataset.points=String(finalPoints||0);if(state.specialInput&&!state.specialInput.value&&state.automatic)state.specialInput.value=String(state.automatic.points);const title=card.querySelector<HTMLElement>("strong"),help=card.querySelector<HTMLElement>("small");if(title)title.textContent=finalPoints>0?`${fa(finalPoints)} امتیاز`:"در انتظار تکمیل";if(help){if(specialOn)help.textContent=`امتیاز ویژه مدیر سامانه فعال است؛ امتیاز خودکار سیستم ${state.automatic?fa(state.automatic.points):"تعریف‌نشده"} امتیاز است.`;else if(state.automatic)help.textContent=`${state.automatic.label} • پایه ${fa(state.automatic.base)} امتیاز برای ${fa(state.automatic.basis)} روز • مدت فعلی ${fa(Number(digits(state.duration?.value||"0")))} روز`;else help.textContent=state.type?.value==="PATIENT"?"برای نوع بیمار مبنای امتیاز خودکار تعریف نشده است؛ فقط مدیر سامانه می‌تواند امتیاز ویژه ثبت کند.":"شرایط خدمت‌گیرنده و مدت قرارداد را تکمیل کنید تا امتیاز همین‌جا محاسبه شود."}if(specialBox)specialBox.style.display=isAdmin?"grid":"none"}

function enhance(form:HTMLFormElement){if(form.dataset.salJobAutoPoints==="1")return;const type=form.querySelector<HTMLSelectElement>('select[name="contractType"]'),shift=form.querySelector<HTMLSelectElement>('select[name="shiftType"]'),duration=form.querySelector<HTMLInputElement>('[name="durationDays"]'),legacyPoints=form.querySelector<HTMLSelectElement>('select[name="contractPoints"]');if(!type||!shift||!duration||!legacyPoints)return;form.dataset.salJobAutoPoints="1";injectStyle();const legacyLabel=legacyPoints.closest("label");if(legacyLabel instanceof HTMLElement)legacyLabel.style.display="none";legacyPoints.disabled=true;
 const conditionLabel=document.createElement("label");conditionLabel.className="sal-job-condition-label";conditionLabel.innerHTML='<span>شرایط خدمت‌گیرنده</span><select data-sal-job-condition></select><small class="sal-job-condition-help">امتیاز پایه متناسب با نوع خدمت و این شرایط توسط سیستم تعیین می‌شود.</small>';const typeLabel=type.closest("label");typeLabel?.insertAdjacentElement("afterend",conditionLabel);
 const hidden=document.createElement("input");hidden.type="hidden";hidden.name="contractPoints";hidden.setAttribute("data-sal-job-points-hidden","1");form.appendChild(hidden);
 const grid=form.querySelector(".ma-form-grid,.ja-form-grid")||form;const card=document.createElement("div");card.className="sal-job-points-card";card.setAttribute("data-sal-job-points-card","1");card.setAttribute("aria-live","polite");card.dataset.ready="0";card.innerHTML='<span class="sal-job-points-title">امتیاز آگهی • محاسبه زنده</span><strong>در انتظار تکمیل</strong><small>با تغییر شرایط، شیفت یا مدت قرارداد امتیاز فوراً به‌روزرسانی می‌شود.</small>';const durationLabel=duration.closest("label");if(durationLabel)durationLabel.insertAdjacentElement("afterend",card);else grid.appendChild(card);
 const special=document.createElement("div");special.className="sal-job-special";special.setAttribute("data-sal-job-special-box","1");special.innerHTML='<label><input type="checkbox" data-sal-job-special-toggle><b>ثبت امتیاز ویژه توسط مدیر سامانه</b></label><input type="number" min="1" step="1" inputmode="numeric" data-sal-job-special-value placeholder="امتیاز ویژه"><span class="sal-job-special-note">با فعال‌کردن این گزینه، امتیاز خودکار سیستم فقط برای همین آگهی Override می‌شود.</span>';card.insertAdjacentElement("afterend",special);
 const rerender=(force=false)=>refresh(form,force);type.addEventListener("change",()=>rerender(true));shift.addEventListener("change",()=>rerender());duration.addEventListener("input",()=>rerender());conditionLabel.querySelector("select")?.addEventListener("change",()=>rerender());special.querySelector("[data-sal-job-special-toggle]")?.addEventListener("change",()=>rerender());special.querySelector("[data-sal-job-special-value]")?.addEventListener("input",()=>rerender());rerender(true)}

function scan(){document.querySelectorAll<HTMLFormElement>("form").forEach(enhance)}
function activeJobForm(){return [...document.querySelectorAll<HTMLFormElement>('form[data-sal-job-auto-points="1"]')].find(f=>f.offsetParent!==null)||document.querySelector<HTMLFormElement>('form[data-sal-job-auto-points="1"]')}
function augmentBody(body:any){const form=activeJobForm();if(!form)return body;refresh(form);const s=formState(form),hidden=form.querySelector<HTMLInputElement>('[data-sal-job-points-hidden]');return {...body,recipientCondition:s.condition?.value||"",contractPoints:Number(hidden?.value||0),specialPointsEnabled:Boolean(isAdmin&&s.specialToggle?.checked),specialContractPoints:isAdmin&&s.specialToggle?.checked?Math.trunc(Number(s.specialInput?.value||0)):0}}

async function install(){if(installed)return;installed=true;try{const r=await fetch("/api/auth/me",{credentials:"same-origin",cache:"no-store"}),p:any=await r.json().catch(()=>({}));isAdmin=String(p?.data?.role||"").toUpperCase()==="ADMIN"}catch{isAdmin=false}const nativeFetch=window.fetch.bind(window);window.fetch=async(input:RequestInfo|URL,init?:RequestInit)=>{const url=typeof input==="string"?input:input instanceof URL?input.toString():input.url,method=String(init?.method||(input instanceof Request?input.method:"GET")).toUpperCase();if((method==="POST"||method==="PATCH")&&/\/api\/staff\/job-ads(?:\/[^/]+)?(?:\?.*)?$/.test(url)){try{const raw=typeof init?.body==="string"?init.body:input instanceof Request?await input.clone().text():"",body=raw?JSON.parse(raw):null;if(body&&body.contractType){const next=augmentBody(body),headers=new Headers(init?.headers||(input instanceof Request?input.headers:undefined));headers.set("content-type","application/json");init={...init,headers,body:JSON.stringify(next)}}}catch{}}return nativeFetch(input as any,init)};scan();new MutationObserver(scan).observe(document.documentElement,{childList:true,subtree:true})}
void install();
export {};
