import { requireAccess } from "./access-control";
import { ensureProfileImageSchema } from "./profile-images";
import { ensurePerformanceSchema } from "./performance-schema";
import { type AuthUser, type Env, ensureSchema, json, str } from "./lib";

const PAGE_SIZE = 50;
const COUNTS_TTL_MS = 60_000;
const FILTERED_TOTAL_TTL_MS = 30_000;
const FILTERED_TOTAL_CACHE_LIMIT = 100;
type Row = Record<string, unknown>;
type CacheSource = "hit" | "miss" | "skipped";
type CountsResult = { value: Row; source: CacheSource; rowsRead: number };
type TotalResult = { total: number; source: CacheSource; rowsRead: number };
let countsCache: { expiresAt: number; value: Row } | null = null;
const filteredTotalCache = new Map<string, { expiresAt: number; total: number }>();

function publicMobile(value: unknown) {const mobile=str(value);return /^(internal|legacy|crm-login|deleted)-/i.test(mobile)?"":mobile}
function parsePermissions(value: unknown) {try{const parsed=JSON.parse(str(value)||"[]");return Array.isArray(parsed)?parsed:[]}catch{return[]}}
function resultRowsRead(result:{meta?:unknown}){const meta=result.meta as {rows_read?:number}|undefined;return Number(meta?.rows_read||0)}
function cachedFilteredTotal(key:string){const entry=filteredTotalCache.get(key);if(!entry||entry.expiresAt<=Date.now()){filteredTotalCache.delete(key);return null}return entry.total}
function storeFilteredTotal(key:string,total:number){if(filteredTotalCache.size>=FILTERED_TOTAL_CACHE_LIMIT)filteredTotalCache.delete(filteredTotalCache.keys().next().value||"");filteredTotalCache.set(key,{total,expiresAt:Date.now()+FILTERED_TOTAL_TTL_MS})}
function normalizedIso(value:string){if(!value)return"";const time=Date.parse(value);return Number.isFinite(time)?new Date(time).toISOString():""}
function withPerformanceHeaders(response:Response,metrics:{schemaMs:number;summaryMs:number;rowsMs:number;totalMs:number;rowsRead:number;dbQueries:number;countsSource:CacheSource;totalSource:CacheSource}){const headers=new Headers(response.headers);headers.set("server-timing",[`schema;dur=${metrics.schemaMs.toFixed(2)}`,`summary;dur=${metrics.summaryMs.toFixed(2)}`,`rows;dur=${metrics.rowsMs.toFixed(2)}`,`handler;dur=${metrics.totalMs.toFixed(2)}`].join(", "));headers.set("x-salamat-db-queries",String(metrics.dbQueries));headers.set("x-salamat-rows-read",String(metrics.rowsRead));headers.set("x-salamat-counts-cache",metrics.countsSource);headers.set("x-salamat-total-cache",metrics.totalSource);return new Response(response.body,{status:response.status,statusText:response.statusText,headers})}
const validCaregiverName=`TRIM(COALESCE(c.full_name,'')) NOT IN ('در انتظار ورود','در انتظار ورود در انتظار ورود')`;
const visibleUser=`upper(u.status)<>'DELETED' AND (upper(u.role)<>'CAREGIVER' OR c.id IS NULL OR ${validCaregiverName})`;

async function directoryCounts(env:Env):Promise<CountsResult>{const now=Date.now();if(countsCache&&countsCache.expiresAt>now)return{value:countsCache.value,source:"hit",rowsRead:0};const result=await env.DB.prepare(`SELECT (SELECT COUNT(*) FROM users u LEFT JOIN caregivers c ON c.id=u.caregiver_id WHERE ${visibleUser}) AS accounts,(SELECT COUNT(*) FROM users u LEFT JOIN caregivers c ON c.id=u.caregiver_id WHERE upper(u.role)='CAREGIVER' AND ${visibleUser}) AS caregiverAccounts,(SELECT COUNT(*) FROM caregivers c WHERE (c.cooperation_status IS NULL OR c.cooperation_status<>'حذف‌شده') AND ${validCaregiverName}) AS caregiverProfiles,(SELECT COUNT(*) FROM users u LEFT JOIN caregivers c ON c.id=u.caregiver_id WHERE upper(u.status) IN ('ACTIVE','APPROVED') AND (${visibleUser})) AS activeAccounts,(SELECT COUNT(*) FROM caregivers c WHERE (c.cooperation_status IS NULL OR c.cooperation_status<>'حذف‌شده') AND ${validCaregiverName} AND NOT EXISTS(SELECT 1 FROM users u WHERE u.caregiver_id=c.id AND upper(u.role)='CAREGIVER' AND upper(u.status)<>'DELETED')) AS profilesWithoutAccounts,(SELECT COUNT(*) FROM users u WHERE upper(u.role)='CAREGIVER' AND upper(u.status)<>'DELETED' AND (u.caregiver_id IS NULL OR NOT EXISTS(SELECT 1 FROM caregivers c WHERE c.id=u.caregiver_id))) AS accountsWithoutProfiles`).all<Row>();const value=result.results?.[0]||{};countsCache={value,expiresAt:now+COUNTS_TTL_MS};return{value,source:"miss",rowsRead:resultRowsRead(result)}}
async function filteredTotal(env:Env,cacheKey:string,sql:string,args:unknown[]):Promise<TotalResult>{const cached=cachedFilteredTotal(cacheKey);if(cached!==null)return{total:cached,source:"hit",rowsRead:0};const result=await env.DB.prepare(sql).bind(...args).all<{total:number}>();const total=Number(result.results?.[0]?.total||0);storeFilteredTotal(cacheKey,total);return{total,source:"miss",rowsRead:resultRowsRead(result)}}
export function invalidateAdminDirectoryCounts(){countsCache=null;filteredTotalCache.clear()}

export async function adminDirectoryLight(request:Request,env:Env,actor:AuthUser){
  const denied=await requireAccess(env,actor,"staff.users","view");if(denied)return denied;
  const handlerStarted=performance.now(),schemaStarted=performance.now();await ensureSchema(env);await ensureProfileImageSchema(env);await ensurePerformanceSchema(env);const schemaMs=performance.now()-schemaStarted;
  const url=new URL(request.url),query=str(url.searchParams.get("q")).slice(0,120),includeCounts=url.searchParams.get("includeCounts")!=="0",requestedPage=Number.parseInt(url.searchParams.get("page")||"1",10),requested=Number.isFinite(requestedPage)&&requestedPage>0?requestedPage:1,pageSize=PAGE_SIZE,pattern=`%${query}%`,numeric=/^\d+$/.test(query),roleFilter=str(url.searchParams.get("role")).toUpperCase(),statusFilter=str(url.searchParams.get("status")).toUpperCase(),registrationFilter=str(url.searchParams.get("registration")).toUpperCase(),createdFrom=normalizedIso(str(url.searchParams.get("createdFrom"))),createdTo=normalizedIso(str(url.searchParams.get("createdTo"))),sort=str(url.searchParams.get("sort")).toUpperCase()==="OLDEST"?"OLDEST":"NEWEST";
  const conditions:string[]=[visibleUser],userArgs:unknown[]=[];
  if(query){if(numeric){conditions.push(`(COALESCE(u.username,'')=? OR COALESCE(u.mobile,'')=? OR COALESCE(c.membership_code,'')=? OR COALESCE(c.national_id,'')=? OR u.full_name LIKE ?)`);userArgs.push(query,query,query,query,pattern)}else{conditions.push(`(u.full_name LIKE ? OR COALESCE(u.username,'') LIKE ? OR COALESCE(u.mobile,'') LIKE ? OR COALESCE(c.membership_code,'') LIKE ? OR COALESCE(c.national_id,'') LIKE ?)`);userArgs.push(pattern,pattern,pattern,pattern,pattern)}}
  if(roleFilter){conditions.push("upper(u.role)=?");userArgs.push(roleFilter)}
  if(statusFilter){conditions.push("upper(u.status)=?");userArgs.push(statusFilter)}
  if(registrationFilter==="SELF_REGISTERED")conditions.push("(upper(COALESCE(c.recruitment_stage,''))='SELF_REGISTERED' OR upper(COALESCE(c.crm_record_id,'')) LIKE 'SELF-%')");
  if(createdFrom){conditions.push("u.created_at>=?");userArgs.push(createdFrom)}
  if(createdTo){conditions.push("u.created_at<?");userArgs.push(createdTo)}
  const userWhere=`WHERE ${conditions.join(" AND ")}`,cacheKey=JSON.stringify({numeric,query:query.toLowerCase(),roleFilter,statusFilter,registrationFilter,createdFrom,createdTo});
  const summaryStarted=performance.now(),countsPromise=includeCounts?directoryCounts(env):Promise.resolve<CountsResult>({value:{},source:"skipped",rowsRead:0}),totalPromise=filteredTotal(env,cacheKey,`SELECT COUNT(*) AS total FROM users u LEFT JOIN caregivers c ON c.id=u.caregiver_id ${userWhere}`,userArgs),[countsResult,totalResult]=await Promise.all([countsPromise,totalPromise]),summaryMs=performance.now()-summaryStarted;
  const total=totalResult.total,totalPages=Math.max(1,Math.ceil(total/pageSize)),page=Math.min(requested,totalPages),offset=(page-1)*pageSize,rowsStarted=performance.now(),direction=sort==="OLDEST"?"ASC":"DESC";
  const accountResult=await env.DB.prepare(`SELECT u.id,u.caregiver_id AS caregiverId,u.full_name AS fullName,u.mobile,u.username,u.role,u.status,u.permissions_json AS permissionsJson,u.last_login_at AS lastLoginAt,u.created_at AS createdAt,c.membership_code AS membershipCode,c.full_name AS caregiverFullName,c.mobile AS caregiverMobile,c.cooperation_status AS fileStatus,c.national_id AS nationalId,c.city,c.service_region AS address,c.birth_date AS birthDate,c.primary_type AS primaryType,c.work_history AS workHistory,c.professional_level AS professionalLevel,c.professional_score AS professionalScore,c.license_status AS licenseStatus,(SELECT pi.id FROM profile_images pi WHERE pi.user_id=u.id OR (u.caregiver_id IS NOT NULL AND pi.caregiver_id=u.caregiver_id) ORDER BY pi.updated_at DESC LIMIT 1) AS avatarId FROM users u LEFT JOIN caregivers c ON c.id=u.caregiver_id ${userWhere} ORDER BY u.created_at ${direction},u.id ${direction} LIMIT ? OFFSET ?`).bind(...userArgs,pageSize,offset).all<Row>();const rowsMs=performance.now()-rowsStarted;
  const accounts:Row[]=(accountResult.results||[]).map((row):Row=>({...row,mobile:publicMobile(row.mobile),caregiverMobile:publicMobile(row.caregiverMobile),permissions:parsePermissions(row.permissionsJson),permissionsJson:undefined,avatarUrl:row.avatarId?`/api/profile-images/${encodeURIComponent(str(row.avatarId))}`:null,linked:str(row.role).toUpperCase()!=="CAREGIVER"||Boolean(row.caregiverId&&row.membershipCode)}));
  const caregivers=accounts.filter(row=>row.caregiverId).map(row=>({id:row.caregiverId,membershipCode:row.membershipCode,nationalId:row.nationalId,fullName:row.caregiverFullName||row.fullName,mobile:row.caregiverMobile||row.mobile,city:row.city,address:row.address,birthDate:row.birthDate,fileStatus:row.fileStatus,primaryType:row.primaryType,workHistory:row.workHistory,professionalLevel:row.professionalLevel,professionalScore:row.professionalScore,licenseStatus:row.licenseStatus,createdAt:row.createdAt,userId:row.id,username:row.username,accountStatus:row.status,avatarId:row.avatarId,avatarUrl:row.avatarUrl,hasAccount:true}));
  const counts=includeCounts?{accounts:Number(countsResult.value?.accounts||0),caregiverAccounts:Number(countsResult.value?.caregiverAccounts||0),caregiverProfiles:Number(countsResult.value?.caregiverProfiles||0),activeAccounts:Number(countsResult.value?.activeAccounts||0),profilesWithoutAccounts:Number(countsResult.value?.profilesWithoutAccounts||0),accountsWithoutProfiles:Number(countsResult.value?.accountsWithoutProfiles||0)}:null;
  const response=json({status:"ok",data:{accounts,caregivers,counts,countsIncluded:includeCounts,pagination:{page,pageSize,total,totalPages,hasNext:page<totalPages,hasPrevious:page>1},query,filters:{role:roleFilter,status:statusFilter,registration:registrationFilter,createdFrom,createdTo,sort},migration:{scanned:0,migrated:0,mode:"disabled_on_read"},reconciliation:{mode:"disabled_on_read"}}});
  const rowsRead=countsResult.rowsRead+totalResult.rowsRead+resultRowsRead(accountResult),dbQueries=1+(countsResult.source==="miss"?1:0)+(totalResult.source==="miss"?1:0);
  return withPerformanceHeaders(response,{schemaMs,summaryMs,rowsMs,totalMs:performance.now()-handlerStarted,rowsRead,dbQueries,countsSource:countsResult.source,totalSource:totalResult.source});
}
