import {invalidateAdminDirectoryCounts} from "./admin-directory-light";
import {invalidateCaregiverDirectoryCache} from "./caregiver-directory-page";
import {MODULE_DEFINITIONS,ROLE_DEFINITIONS,ensureAccessControlSchema} from "./access-control";
import {individualEffectivePermissions} from "./individual-access-v2";
import {type AuthUser,type Env,audit,fail,getUser,json,normalizeRole,nowIso,readBody,securityHeaders,str} from "./lib";

const ACTIONS=["view","create","update","delete"] as const;
async function hasFullUsersAccess(env:Env,actor:AuthUser){const module=(await individualEffectivePermissions(env,actor)).find(item=>item.key==="staff.users");return Boolean(module&&ACTIONS.every(action=>Boolean(module.actions[action])))}
async function account(env:Env,id:string){return env.DB.prepare(`SELECT id,caregiver_id AS caregiverId,full_name AS fullName,mobile,username,password_hash AS passwordHash,role,status,permissions_json AS permissionsJson FROM users WHERE id=? AND upper(status)<>'DELETED' LIMIT 1`).bind(id).first<any>()}
async function overrides(env:Env,id:string){const r=await env.DB.prepare(`SELECT module_key AS moduleKey,can_view AS canView,can_create AS canCreate,can_update AS canUpdate,can_delete AS canDelete FROM user_module_permissions WHERE user_id=?`).bind(id).all<any>();return r.results||[]}
function permission(value:any){if(!value||typeof value!=="object")return null;const moduleKey=str(value.moduleKey||value.key);if(!MODULE_DEFINITIONS.some(x=>x.key===moduleKey))return null;const b=(a:any,c:any)=>a===undefined&&c===undefined?null:Boolean(a??c);return{moduleKey,canView:b(value.view,value.canView),canCreate:b(value.create,value.canCreate),canUpdate:b(value.update,value.canUpdate),canDelete:b(value.delete,value.canDelete)}}

export async function routeDelegatedCaregiverApprovalV1(request:Request,env:Env):Promise<Response|null>{
 const url=new URL(request.url),method=request.method.toUpperCase(),approvalMatch=url.pathname.match(/^\/api\/users\/([^/]+)$/),accessMatch=url.pathname.match(/^\/api\/admin\/access\/users\/([^/]+)$/),config=url.pathname==="/api/admin/access/config"&&method==="GET";
 const approvalCandidate=Boolean(approvalMatch&&method==="PATCH");if(!approvalCandidate&&!accessMatch&&!config)return null;
 const actor=await getUser(request,env);if(!actor)return securityHeaders(fail("ابتدا وارد حساب شوید.",401,"unauthorized"));if(normalizeRole(actor.role)==="ADMIN")return null;
 if(!await hasFullUsersAccess(env,actor))return securityHeaders(fail("این عملیات نیازمند هر چهار اختیار مشاهده، ثبت، تغییر و حذف در ماژول کاربران و دسترسی‌ها است.",403,"full_users_access_required"));
 await ensureAccessControlSchema(env);
 if(config){const r=await env.DB.prepare(`SELECT role,module_key AS moduleKey,can_view AS canView,can_create AS canCreate,can_update AS canUpdate,can_delete AS canDelete FROM role_module_permissions ORDER BY role,module_key`).all<any>();return securityHeaders(json({data:{roles:ROLE_DEFINITIONS,modules:MODULE_DEFINITIONS,rolePermissions:r.results||[],delegated:true}}))}
 if(accessMatch){
  const userId=decodeURIComponent(accessMatch[1]),target=await account(env,userId);if(!target)return securityHeaders(fail("حساب کاربری پیدا نشد.",404,"user_not_found"));if(normalizeRole(target.role)!=="CAREGIVER")return securityHeaders(fail("اختیار تفویض‌شده در این مسیر فقط برای حساب مراقب قابل استفاده است.",403,"delegated_caregiver_only"));
  if(method==="GET"){const [effective,userOverrides]=await Promise.all([individualEffectivePermissions(env,target),overrides(env,userId)]);return securityHeaders(json({data:{user:{id:target.id,caregiverId:target.caregiverId,fullName:target.fullName,mobile:target.mobile,username:target.username,role:"CAREGIVER",status:target.status},effective,overrides:userOverrides,policy:{delegated:true,caregiverOnly:true}}}))}
  if(method==="PUT"){const body=await readBody(request);if(!body)return securityHeaders(fail("اطلاعات دسترسی معتبر نیست."));if(body.role!==undefined&&normalizeRole(body.role)!=="CAREGIVER")return securityHeaders(fail("کاربر دارای اختیار تفویض‌شده نمی‌تواند نقش حساب مراقب را تغییر دهد.",403,"delegated_role_locked"));const permissions=Array.isArray(body.permissions)?body.permissions.map(permission).filter(Boolean):[],ts=nowIso(),statements:D1PreparedStatement[]=[env.DB.prepare("DELETE FROM user_module_permissions WHERE user_id=?").bind(userId)];for(const p of permissions as any[])statements.push(env.DB.prepare(`INSERT INTO user_module_permissions(user_id,module_key,can_view,can_create,can_update,can_delete,updated_by_user_id,updated_at) VALUES(?,?,?,?,?,?,?,?)`).bind(userId,p.moduleKey,p.canView===null?null:p.canView?1:0,p.canCreate===null?null:p.canCreate?1:0,p.canUpdate===null?null:p.canUpdate?1:0,p.canDelete===null?null:p.canDelete?1:0,actor.id,ts));await env.DB.batch(statements);await audit(request,env,actor,"UPDATE_CAREGIVER_PERMISSIONS_DELEGATED","user",userId,{permissions,caregiverOnly:true});return securityHeaders(json({ok:true,userId,role:"CAREGIVER",updatedAt:ts,delegated:true}))}
  return null;
 }
 const body=await readBody(request.clone());if(str(body?.approvalAction).toUpperCase()!=="APPROVE_SELF_REGISTRATION")return null;
 const userId=decodeURIComponent(approvalMatch![1]),row=await env.DB.prepare(`SELECT u.id,u.caregiver_id AS caregiverId,u.full_name AS fullName,u.mobile,u.username,u.password_hash AS passwordHash,u.status,u.role,c.recruitment_stage AS recruitmentStage FROM users u JOIN caregivers c ON c.id=u.caregiver_id WHERE u.id=? AND upper(u.role)='CAREGIVER' AND upper(u.status)<>'DELETED' LIMIT 1`).bind(userId).first<any>();
 if(!row||String(row.recruitmentStage||"").toUpperCase()!=="SELF_REGISTERED")return null;if(String(row.status||"").toUpperCase()!=="PENDING")return securityHeaders(fail("این حساب دیگر در وضعیت انتظار تأیید نیست.",409,"account_not_pending"));if(!str(row.username)||!str(row.passwordHash))return securityHeaders(fail("اطلاعات ورود اولیه مراقب کامل نیست؛ تکمیل اطلاعات ورود فقط توسط مدیرسامانه انجام می‌شود.",409,"pending_credentials_incomplete"));
 const requestedUsername=str(body?.username);if(requestedUsername&&requestedUsername.toLowerCase()!==str(row.username).toLowerCase())return securityHeaders(fail("کاربر دارای اختیار تفویض‌شده فقط مجاز به فعال‌سازی حساب در انتظار است و نمی‌تواند نام کاربری مراقب را تغییر دهد.",403,"delegated_approval_credentials_locked"));if(str(body?.password))return securityHeaders(fail("کاربر دارای اختیار تفویض‌شده هنگام تأیید حساب مجاز به تغییر رمز عبور مراقب نیست.",403,"delegated_approval_credentials_locked"));
 const ts=nowIso();await env.DB.batch([env.DB.prepare("UPDATE users SET status='ACTIVE',updated_at=? WHERE id=? AND upper(status)='PENDING'").bind(ts,userId),env.DB.prepare("UPDATE caregivers SET active=1,recruitment_stage='APPROVED',cooperation_status='CP-01 فعال',updated_at=? WHERE id=?").bind(ts,row.caregiverId)]);invalidateAdminDirectoryCounts();invalidateCaregiverDirectoryCache();await audit(request,env,actor,"APPROVE_SELF_REGISTERED_ACCOUNT_DELEGATED","caregiver",row.caregiverId,{accountId:userId,fullUsersAccess:true,credentialsChanged:false});return securityHeaders(json({ok:true,data:{id:userId,userId,caregiverId:row.caregiverId,fullName:row.fullName,mobile:row.mobile,username:row.username,role:"CAREGIVER",status:"ACTIVE",approved:true,delegatedApproval:true},updatedAt:ts}));
}
