import {requireAccess,type AccessAction} from "./access-control";
import {loadScorecard} from "./caregiver-scorecard-v2";
import {type AuthUser,type Env,audit,fail,getUser,json,nowIso,randomId,readBody,securityHeaders,str} from "./lib";

const CONTRACT_TYPES=new Set(["ELDERLY","CHILD","PATIENT","HOUSEKEEPING"]);
const SHIFT_TYPES=new Set(["DAY","NIGHT","LIVE_IN","TEMPORARY"]);
const POINT_VALUES=new Set([20,100,200,300]);
const APPLICATION_STATUSES=new Set(["PENDING_CONSULTANT","TRIAL_DISPATCH","REJECTED","IN_CONTRACT"]);
let schemaReady:Promise<void>|undefined;

export async function ensureJobAdsSchema(env:Env){
 if(!schemaReady)schemaReady=(async()=>{await env.DB.batch([
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS care_job_ads(id TEXT PRIMARY KEY,customer_full_name TEXT NOT NULL,sales_consultant_user_id TEXT NOT NULL,contract_type TEXT NOT NULL,shift_type TEXT NOT NULL,caregiver_salary_rial INTEGER NOT NULL,duration_days INTEGER NOT NULL,contract_points INTEGER NOT NULL,description TEXT NOT NULL DEFAULT '',status TEXT NOT NULL DEFAULT 'DRAFT',created_by_user_id TEXT NOT NULL,published_at TEXT,created_at TEXT NOT NULL,updated_at TEXT NOT NULL,FOREIGN KEY(sales_consultant_user_id) REFERENCES users(id),FOREIGN KEY(created_by_user_id) REFERENCES users(id))`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS care_job_applications(id TEXT PRIMARY KEY,ad_id TEXT NOT NULL,caregiver_id TEXT NOT NULL,status TEXT NOT NULL DEFAULT 'PENDING_CONSULTANT',applied_at TEXT NOT NULL,updated_at TEXT NOT NULL,UNIQUE(ad_id,caregiver_id),FOREIGN KEY(ad_id) REFERENCES care_job_ads(id) ON DELETE CASCADE,FOREIGN KEY(caregiver_id) REFERENCES caregivers(id) ON DELETE CASCADE)`),
  env.DB.prepare(`CREATE TABLE IF NOT EXISTS caregiver_contract_point_ledger(id TEXT PRIMARY KEY,caregiver_id TEXT NOT NULL,ad_id TEXT NOT NULL,application_id TEXT NOT NULL UNIQUE,points INTEGER NOT NULL,awarded_by_user_id TEXT NOT NULL,awarded_at TEXT NOT NULL,FOREIGN KEY(caregiver_id) REFERENCES caregivers(id) ON DELETE CASCADE,FOREIGN KEY(ad_id) REFERENCES care_job_ads(id),FOREIGN KEY(application_id) REFERENCES care_job_applications(id),FOREIGN KEY(awarded_by_user_id) REFERENCES users(id))`),
  env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_care_job_ads_status_created ON care_job_ads(status,created_at DESC)"),
  env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_care_job_applications_ad ON care_job_applications(ad_id,applied_at DESC)"),
  env.DB.prepare("CREATE INDEX IF NOT EXISTS idx_contract_point_ledger_caregiver ON caregiver_contract_point_ledger(caregiver_id,awarded_at DESC)"),
 ])})().catch(e=>{schemaReady=undefined;throw e});return schemaReady;
}

async function staffAccess(env:Env,actor:AuthUser,action:AccessAction){return requireAccess(env,actor,"staff.job_ads",action)}
function adSelect(){return `SELECT a.id,a.customer_full_name AS customerFullName,a.sales_consultant_user_id AS salesConsultantUserId,u.full_name AS salesConsultantName,a.city,a.region,a.contract_type AS contractType,a.shift_type AS shiftType,a.caregiver_salary_rial AS caregiverSalaryRial,a.duration_days AS durationDays,a.contract_points AS contractPoints,a.description,a.status,a.published_at AS publishedAt,a.created_at AS createdAt,a.updated_at AS updatedAt,(SELECT COUNT(*) FROM care_job_applications ap WHERE ap.ad_id=a.id) AS applicationCount FROM care_job_ads a JOIN users u ON u.id=a.sales_consultant_user_id`}
function cleanBody(body:any){const customerFullName=str(body?.customerFullName),city=str(body?.city),region=str(body?.region),salesConsultantUserId=str(body?.salesConsultantUserId),contractType=str(body?.contractType).toUpperCase(),shiftType=str(body?.shiftType).toUpperCase(),caregiverSalaryRial=Math.max(0,Math.trunc(Number(body?.caregiverSalaryRial||0))),durationDays=Math.max(0,Math.trunc(Number(body?.durationDays||0))),contractPoints=Math.trunc(Number(body?.contractPoints||0)),description=str(body?.description);if(!customerFullName)return {error:"نام و نام خانوادگی مشترک الزامی است."};if(!city)return {error:"شهر آگهی الزامی است."};if(!region)return {error:"منطقه آگهی الزامی است."};if(!salesConsultantUserId)return {error:"مشاور پرونده را انتخاب کنید."};if(!CONTRACT_TYPES.has(contractType))return {error:"نوع قرارداد معتبر نیست."};if(!SHIFT_TYPES.has(shiftType))return {error:"شیفت خدمت معتبر نیست."};if(caregiverSalaryRial<=0)return {error:"حقوق ماهانه مراقب را به ریال وارد کنید."};if(durationDays<=0)return {error:"مدت قرارداد باید حداقل یک روز باشد."};if(!POINT_VALUES.has(contractPoints))return {error:"امتیاز قرارداد باید یکی از ۲۰، ۱۰۰، ۲۰۰ یا ۳۰۰ باشد."};if(description.length>3000)return {error:"شرح آگهی نمی‌تواند بیشتر از ۳۰۰۰ کاراکتر باشد."};return {customerFullName,city,region,salesConsultantUserId,contractType,shiftType,caregiverSalaryRial,durationDays,contractPoints,description}}
async function consultantExists(env:Env,id:string){return env.DB.prepare("SELECT id FROM users WHERE id=? AND role='SALES_CONSULTANT' AND status='ACTIVE' LIMIT 1").bind(id).first<{id:string}>()}
async function adForStaff(env:Env,actor:AuthUser,id:string){const ad=await env.DB.prepare(`${adSelect()} WHERE a.id=? LIMIT 1`).bind(id).first<any>();if(!ad)return null;if(actor.role.toUpperCase()==="SALES_CONSULTANT"&&ad.salesConsultantUserId!==actor.id)return false;return ad}

export async function contractPointsSummary(env:Env,caregiverId:string){await ensureJobAdsSchema(env);const row=await env.DB.prepare("SELECT COALESCE(SUM(points),0) AS totalPoints,COUNT(*) AS awardedContracts FROM caregiver_contract_point_ledger WHERE caregiver_id=?").bind(caregiverId).first<{totalPoints:number;awardedContracts:number}>();const totalPoints=Number(row?.totalPoints||0),thresholds=[200,400,600],nextThreshold=thresholds.find(x=>totalPoints<x)||600;return {totalPoints,awardedContracts:Number(row?.awardedContracts||0),nextThreshold,remainingToNext:Math.max(0,nextThreshold-totalPoints),maxThreshold:600,progressPercent:Math.min(100,Math.round(totalPoints/600*1000)/10)}}

async function consultants(request:Request,env:Env,actor:AuthUser){const denied=await staffAccess(env,actor,"view");if(denied)return denied;const q=str(new URL(request.url).searchParams.get("q")),like=`%${q}%`;const r=await env.DB.prepare(`SELECT id,full_name AS fullName,mobile,username FROM users WHERE role='SALES_CONSULTANT' AND status='ACTIVE' AND (?='' OR full_name LIKE ? OR mobile LIKE ? OR username LIKE ?) ORDER BY full_name LIMIT 80`).bind(q,like,like,like).all();return json({data:{consultants:r.results||[]}})}
async function staffList(request:Request,env:Env,actor:AuthUser){const denied=await staffAccess(env,actor,"view");if(denied)return denied;const u=new URL(request.url),q=str(u.searchParams.get("q")),status=str(u.searchParams.get("status")).toUpperCase(),like=`%${q}%`;let sql=`${adSelect()} WHERE (?='' OR a.customer_full_name LIKE ? OR u.full_name LIKE ? OR a.description LIKE ? OR a.city LIKE ? OR a.region LIKE ?)`;const binds:any[]=[q,like,like,like,like,like];if(status){sql+=" AND a.status=?";binds.push(status)}if(actor.role.toUpperCase()==="SALES_CONSULTANT"){sql+=" AND a.sales_consultant_user_id=?";binds.push(actor.id)}sql+=" ORDER BY CASE a.status WHEN 'PUBLISHED' THEN 0 WHEN 'DRAFT' THEN 1 ELSE 2 END,a.created_at DESC LIMIT 200";const r=await env.DB.prepare(sql).bind(...binds).all();return json({data:{ads:r.results||[]}})}
async function staffDetail(env:Env,actor:AuthUser,id:string){const denied=await staffAccess(env,actor,"view");if(denied)return denied;const ad=await adForStaff(env,actor,id);if(ad===null)return fail("آگهی پیدا نشد.",404,"job_ad_not_found");if(ad===false)return fail("این آگهی به مشاور دیگری تخصیص داده شده است.",403,"forbidden");const apps=await env.DB.prepare(`SELECT ap.id,ap.caregiver_id AS caregiverId,c.full_name AS caregiverName,c.membership_code AS membershipCode,c.mobile,c.professional_level AS professionalLevel,
  (SELECT p.final_score FROM caregiver_evaluation_periods p WHERE p.caregiver_id=c.id AND p.status='FINAL' AND p.archived_at IS NULL ORDER BY COALESCE(p.finalized_at,p.updated_at,p.created_at) DESC LIMIT 1) AS evaluationScore,
  (SELECT p.id FROM caregiver_evaluation_periods p WHERE p.caregiver_id=c.id AND p.status='FINAL' AND p.archived_at IS NULL ORDER BY COALESCE(p.finalized_at,p.updated_at,p.created_at) DESC LIMIT 1) AS evaluationId,
  ap.status,ap.applied_at AS appliedAt,ap.updated_at AS updatedAt,CASE WHEN l.id IS NULL THEN 0 ELSE 1 END AS pointsAwarded
  FROM care_job_applications ap JOIN caregivers c ON c.id=ap.caregiver_id LEFT JOIN caregiver_contract_point_ledger l ON l.application_id=ap.id WHERE ap.ad_id=? ORDER BY ap.applied_at DESC`).bind(id).all();return json({data:{ad,applications:apps.results||[]}})}
async function createAd(request:Request,env:Env,actor:AuthUser){const denied=await staffAccess(env,actor,"create");if(denied)return denied;const parsed=cleanBody(await readBody(request));if("error" in parsed)return fail(String(parsed.error||"اطلاعات آگهی معتبر نیست."));if(!await consultantExists(env,parsed.salesConsultantUserId))return fail("مشاور فروش انتخاب‌شده فعال نیست.",400,"consultant_invalid");if(actor.role.toUpperCase()==="SALES_CONSULTANT"&&parsed.salesConsultantUserId!==actor.id)return fail("مشاور فروش فقط می‌تواند آگهی خود را ایجاد کند.",403,"forbidden");const id=randomId("ad_"),ts=nowIso();await env.DB.prepare(`INSERT INTO care_job_ads(id,customer_full_name,city,region,sales_consultant_user_id,contract_type,shift_type,caregiver_salary_rial,duration_days,contract_points,description,status,created_by_user_id,created_at,updated_at) VALUES(?,?,?,?,?,?,?,?,?,?,?,'DRAFT',?,?,?)`).bind(id,parsed.customerFullName,parsed.city,parsed.region,parsed.salesConsultantUserId,parsed.contractType,parsed.shiftType,parsed.caregiverSalaryRial,parsed.durationDays,parsed.contractPoints,parsed.description,actor.id,ts,ts).run();await audit(request,env,actor,"CREATE_JOB_AD","care_job_ad",id,parsed);return json({data:{id,status:"DRAFT"}},201)}
async function updateAd(request:Request,env:Env,actor:AuthUser,id:string){const denied=await staffAccess(env,actor,"update");if(denied)return denied;const current=await env.DB.prepare("SELECT sales_consultant_user_id AS consultantId,status FROM care_job_ads WHERE id=? LIMIT 1").bind(id).first<any>();if(!current)return fail("آگهی پیدا نشد.",404,"job_ad_not_found");if(actor.role.toUpperCase()==="SALES_CONSULTANT"&&current.consultantId!==actor.id)return fail("دسترسی کافی ندارید.",403,"forbidden");if(current.status!=="DRAFT")return fail("فقط آگهی در حال بررسی قابل ویرایش است.",409,"job_ad_locked");const parsed=cleanBody(await readBody(request));if("error" in parsed)return fail(String(parsed.error||"اطلاعات آگهی معتبر نیست."));if(!await consultantExists(env,parsed.salesConsultantUserId))return fail("مشاور فروش انتخاب‌شده فعال نیست.",400,"consultant_invalid");if(actor.role.toUpperCase()==="SALES_CONSULTANT"&&parsed.salesConsultantUserId!==actor.id)return fail("مشاور فروش فقط می‌تواند آگهی خود را نگه دارد.",403,"forbidden");await env.DB.prepare(`UPDATE care_job_ads SET customer_full_name=?,city=?,region=?,sales_consultant_user_id=?,contract_type=?,shift_type=?,caregiver_salary_rial=?,duration_days=?,contract_points=?,description=?,updated_at=? WHERE id=?`).bind(parsed.customerFullName,parsed.city,parsed.region,parsed.salesConsultantUserId,parsed.contractType,parsed.shiftType,parsed.caregiverSalaryRial,parsed.durationDays,parsed.contractPoints,parsed.description,nowIso(),id).run();await audit(request,env,actor,"UPDATE_JOB_AD","care_job_ad",id,parsed);return json({ok:true})}
async function publishAd(request:Request,env:Env,actor:AuthUser,id:string){const denied=await staffAccess(env,actor,"update");if(denied)return denied;const row=await env.DB.prepare("SELECT sales_consultant_user_id AS consultantId,status FROM care_job_ads WHERE id=? LIMIT 1").bind(id).first<any>();if(!row)return fail("آگهی پیدا نشد.",404,"job_ad_not_found");if(actor.role.toUpperCase()==="SALES_CONSULTANT"&&row.consultantId!==actor.id)return fail("دسترسی کافی ندارید.",403,"forbidden");if(row.status==='CLOSED')return fail("آگهی منقضی قابل انتشار مجدد نیست.",409,"job_ad_expired");const ts=nowIso();await env.DB.prepare("UPDATE care_job_ads SET status='PUBLISHED',published_at=COALESCE(published_at,?),updated_at=? WHERE id=?").bind(ts,ts,id).run();await audit(request,env,actor,"PUBLISH_JOB_AD","care_job_ad",id);return json({ok:true,status:"PUBLISHED"})}
async function closeAd(request:Request,env:Env,actor:AuthUser,id:string){const denied=await staffAccess(env,actor,"update");if(denied)return denied;const row=await env.DB.prepare("SELECT sales_consultant_user_id AS consultantId,status FROM care_job_ads WHERE id=? LIMIT 1").bind(id).first<any>();if(!row)return fail("آگهی پیدا نشد.",404,"job_ad_not_found");if(actor.role.toUpperCase()==="SALES_CONSULTANT"&&row.consultantId!==actor.id)return fail("دسترسی کافی ندارید.",403,"forbidden");if(row.status==='CLOSED')return json({ok:true,status:'CLOSED'});const ts=nowIso();await env.DB.prepare("UPDATE care_job_ads SET status='CLOSED',updated_at=? WHERE id=?").bind(ts,id).run();await audit(request,env,actor,"CLOSE_JOB_AD","care_job_ad",id);return json({ok:true,status:"CLOSED"})}
async function caregiverList(request:Request,env:Env,actor:AuthUser){if(actor.role.toUpperCase()!=="CAREGIVER"||!actor.caregiverId)return fail("این مسیر مخصوص مراقبین است.",403,"caregiver_only");const q=str(new URL(request.url).searchParams.get("q")),like=`%${q}%`;const r=await env.DB.prepare(`${adSelect()} WHERE a.status='PUBLISHED' AND (?='' OR a.customer_full_name LIKE ? OR a.description LIKE ? OR u.full_name LIKE ? OR a.city LIKE ? OR a.region LIKE ?) ORDER BY a.published_at DESC,a.created_at DESC LIMIT 150`).bind(q,like,like,like,like,like).all();const points=await contractPointsSummary(env,actor.caregiverId),ads=(r.results||[]).map((x:any)=>x);for(const ad of ads){const mine=await env.DB.prepare("SELECT id,status,applied_at AS appliedAt FROM care_job_applications WHERE ad_id=? AND caregiver_id=? LIMIT 1").bind(ad.id,actor.caregiverId).first();ad.myApplication=mine||null}return json({data:{ads,points}})}
async function caregiverDetail(env:Env,actor:AuthUser,id:string){if(actor.role.toUpperCase()!=="CAREGIVER"||!actor.caregiverId)return fail("این مسیر مخصوص مراقبین است.",403,"caregiver_only");const ad=await env.DB.prepare(`${adSelect()} WHERE a.id=? AND a.status='PUBLISHED' LIMIT 1`).bind(id).first<any>();if(!ad)return fail("آگهی فعال پیدا نشد.",404,"job_ad_not_found");const myApplication=await env.DB.prepare("SELECT id,status,applied_at AS appliedAt FROM care_job_applications WHERE ad_id=? AND caregiver_id=? LIMIT 1").bind(id,actor.caregiverId).first();return json({data:{ad,myApplication,points:await contractPointsSummary(env,actor.caregiverId)}})}
async function apply(request:Request,env:Env,actor:AuthUser,id:string){if(actor.role.toUpperCase()!=="CAREGIVER"||!actor.caregiverId)return fail("این مسیر مخصوص مراقبین است.",403,"caregiver_only");const ad=await env.DB.prepare("SELECT id,status FROM care_job_ads WHERE id=? LIMIT 1").bind(id).first<any>();if(!ad||ad.status!=="PUBLISHED")return fail("این آگهی فعال نیست و امکان اپلای ندارد.",409,"job_ad_unavailable");const ts=nowIso(),appId=randomId("app_");await env.DB.prepare(`INSERT OR IGNORE INTO care_job_applications(id,ad_id,caregiver_id,status,applied_at,updated_at) VALUES(?,?,?,'PENDING_CONSULTANT',?,?)`).bind(appId,id,actor.caregiverId,ts,ts).run();const row=await env.DB.prepare("SELECT id,status,applied_at AS appliedAt FROM care_job_applications WHERE ad_id=? AND caregiver_id=? LIMIT 1").bind(id,actor.caregiverId).first();await audit(request,env,actor,"APPLY_JOB_AD","care_job_ad",id,{applicationId:(row as any)?.id});return json({data:{application:row}})}
async function updateApplication(request:Request,env:Env,actor:AuthUser,adId:string,applicationId:string){const denied=await staffAccess(env,actor,"update");if(denied)return denied;const body=await readBody(request),next=str(body?.status).toUpperCase();if(!APPLICATION_STATUSES.has(next))return fail("وضعیت اپلای معتبر نیست.");const row=await env.DB.prepare(`SELECT ap.id,ap.caregiver_id AS caregiverId,ap.ad_id AS adId,a.contract_points AS contractPoints,a.sales_consultant_user_id AS consultantId,a.status AS adStatus FROM care_job_applications ap JOIN care_job_ads a ON a.id=ap.ad_id WHERE ap.id=? AND ap.ad_id=? LIMIT 1`).bind(applicationId,adId).first<any>();if(!row)return fail("اپلای پیدا نشد.",404,"application_not_found");if(actor.role.toUpperCase()==="SALES_CONSULTANT"&&row.consultantId!==actor.id)return fail("دسترسی کافی ندارید.",403,"forbidden");if(row.adStatus==='CLOSED'&&next!=='IN_CONTRACT')return fail("این آگهی منقضی شده و وضعیت متقاضیان آن دیگر قابل تغییر نیست.",409,"job_ad_expired");const ts=nowIso(),statements=[env.DB.prepare("UPDATE care_job_applications SET status=?,updated_at=? WHERE id=?").bind(next,ts,applicationId)];if(next==="IN_CONTRACT"){statements.push(env.DB.prepare(`INSERT OR IGNORE INTO caregiver_contract_point_ledger(id,caregiver_id,ad_id,application_id,points,awarded_by_user_id,awarded_at) VALUES(?,?,?,?,?,?,?)`).bind(randomId("pt_"),row.caregiverId,row.adId,applicationId,Number(row.contractPoints||0),actor.id,ts));statements.push(env.DB.prepare("UPDATE care_job_ads SET status='CLOSED',updated_at=? WHERE id=?").bind(ts,adId))}await env.DB.batch(statements);await audit(request,env,actor,"UPDATE_JOB_APPLICATION_STATUS","care_job_application",applicationId,{adId,status:next,points:next==="IN_CONTRACT"?row.contractPoints:0,adExpired:next==="IN_CONTRACT"});return json({data:{status:next,adStatus:next==="IN_CONTRACT"?"CLOSED":row.adStatus,points:await contractPointsSummary(env,row.caregiverId)}})}
async function applicantScorecard(env:Env,actor:AuthUser,adId:string,applicationId:string){const denied=await staffAccess(env,actor,"view");if(denied)return denied;const row=await env.DB.prepare(`SELECT ap.caregiver_id AS caregiverId,a.sales_consultant_user_id AS consultantId FROM care_job_applications ap JOIN care_job_ads a ON a.id=ap.ad_id WHERE ap.id=? AND ap.ad_id=? LIMIT 1`).bind(applicationId,adId).first<any>();if(!row)return fail("متقاضی این آگهی پیدا نشد.",404,"application_not_found");if(actor.role.toUpperCase()==="SALES_CONSULTANT"&&row.consultantId!==actor.id)return fail("دسترسی کافی ندارید.",403,"forbidden");const scorecard=await loadScorecard(env,row.caregiverId,null);if(!scorecard)return fail("کارنامه مراقب پیدا نشد.",404,"caregiver_not_found");return json({data:scorecard})}

export async function routeJobAds(request:Request,env:Env):Promise<Response|null>{const url=new URL(request.url),method=request.method.toUpperCase();if(!url.pathname.startsWith("/api/staff/job-ads")&&!url.pathname.startsWith("/api/caregiver/job-ads")&&url.pathname!=="/api/caregiver/contract-points")return null;const actor=await getUser(request,env);if(!actor)return securityHeaders(fail("ابتدا وارد حساب شوید.",401,"unauthorized"));await ensureJobAdsSchema(env);if(url.pathname==="/api/caregiver/contract-points"&&method==="GET"){if(actor.role.toUpperCase()!=="CAREGIVER"||!actor.caregiverId)return fail("این مسیر مخصوص مراقبین است.",403,"caregiver_only");return json({data:await contractPointsSummary(env,actor.caregiverId)})}if(url.pathname==="/api/staff/job-ads/consultants"&&method==="GET")return consultants(request,env,actor);if(url.pathname==="/api/staff/job-ads"&&method==="GET")return staffList(request,env,actor);if(url.pathname==="/api/staff/job-ads"&&method==="POST")return createAd(request,env,actor);let m=url.pathname.match(/^\/api\/staff\/job-ads\/([^/]+)\/publish$/);if(m&&method==="POST")return publishAd(request,env,actor,decodeURIComponent(m[1]));m=url.pathname.match(/^\/api\/staff\/job-ads\/([^/]+)\/close$/);if(m&&method==="POST")return closeAd(request,env,actor,decodeURIComponent(m[1]));m=url.pathname.match(/^\/api\/staff\/job-ads\/([^/]+)\/applications\/([^/]+)\/scorecard$/);if(m&&method==="GET")return applicantScorecard(env,actor,decodeURIComponent(m[1]),decodeURIComponent(m[2]));m=url.pathname.match(/^\/api\/staff\/job-ads\/([^/]+)\/applications\/([^/]+)$/);if(m&&method==="PATCH")return updateApplication(request,env,actor,decodeURIComponent(m[1]),decodeURIComponent(m[2]));m=url.pathname.match(/^\/api\/staff\/job-ads\/([^/]+)$/);if(m&&method==="GET")return staffDetail(env,actor,decodeURIComponent(m[1]));if(m&&method==="PATCH")return updateAd(request,env,actor,decodeURIComponent(m[1]));if(url.pathname==="/api/caregiver/job-ads"&&method==="GET")return caregiverList(request,env,actor);m=url.pathname.match(/^\/api\/caregiver\/job-ads\/([^/]+)\/apply$/);if(m&&method==="POST")return apply(request,env,actor,decodeURIComponent(m[1]));m=url.pathname.match(/^\/api\/caregiver\/job-ads\/([^/]+)$/);if(m&&method==="GET")return caregiverDetail(env,actor,decodeURIComponent(m[1]));return fail("مسیر بانک آگهی معتبر نیست.",404,"not_found")}
