import {type Env,getUser} from "./lib";
import {contractPointsSummary,ensureJobAdsSchema} from "./job-ads-v1";

const RULES=[
 {key:"POINT_LOAN_200",title:"وام ۱۰ میلیون تومانی",amountToman:10_000_000,targetPoints:200},
 {key:"POINT_LOAN_400",title:"وام ۲۰ میلیون تومانی",amountToman:20_000_000,targetPoints:400},
 {key:"POINT_LOAN_600",title:"وام ۵۰ میلیون تومانی",amountToman:50_000_000,targetPoints:600},
] as const;
const REFERRAL_LOAN={key:"REFERRAL_LOAN_10",title:"وام ۵ میلیون تومانی معرفی موفق",amountToman:5_000_000,targetReferrals:10} as const;

function pointLoan(totalPoints:number,rule:(typeof RULES)[number]){const eligible=totalPoints>=rule.targetPoints;const progressPercent=Math.min(100,Math.round(totalPoints/rule.targetPoints*1000)/10);return {...rule,type:"LOAN",eligible,status:eligible?"ELIGIBLE":"IN_PROGRESS",progressPercent,currentPoints:totalPoints,remainingPoints:Math.max(0,rule.targetPoints-totalPoints),scoreThreshold:rule.targetPoints,serviceMode:"POINTS",targetMonths:0,targetDays:rule.targetPoints,serviceDays:totalPoints,serviceDuration:{months:0,days:totalPoints},remainingDays:Math.max(0,rule.targetPoints-totalPoints),projectedEligibilityDate:null,evaluation:{count:0,averageScore:null,minimumScore:null,latestScore:null,metric:totalPoints,metricMode:"CONTRACT_POINTS",threshold:rule.targetPoints,comparison:"GTE",passed:eligible,windowStart:null,windowEnd:null}}}
function referralLoan(completedReferrals:number){const eligible=completedReferrals>=REFERRAL_LOAN.targetReferrals,progressPercent=Math.min(100,Math.round(completedReferrals/REFERRAL_LOAN.targetReferrals*1000)/10);return {...REFERRAL_LOAN,type:"LOAN",eligible,status:eligible?"ELIGIBLE":"IN_PROGRESS",progressPercent,currentReferrals:completedReferrals,remainingReferrals:Math.max(0,REFERRAL_LOAN.targetReferrals-completedReferrals),scoreThreshold:REFERRAL_LOAN.targetReferrals,serviceMode:"REFERRALS",targetMonths:0,targetDays:REFERRAL_LOAN.targetReferrals,serviceDays:completedReferrals,serviceDuration:{months:0,days:completedReferrals},remainingDays:Math.max(0,REFERRAL_LOAN.targetReferrals-completedReferrals),projectedEligibilityDate:null,evaluation:{count:completedReferrals,averageScore:null,minimumScore:null,latestScore:null,metric:completedReferrals,metricMode:"SUCCESSFUL_REFERRALS",threshold:REFERRAL_LOAN.targetReferrals,comparison:"GTE",passed:eligible,windowStart:null,windowEnd:null}}}
async function referralCompletedCount(env:Env,caregiverId:string){try{const row=await env.DB.prepare(`SELECT COUNT(*) AS total FROM caregiver_referral_cases WHERE referrer_caregiver_id=? AND status='COMPLETED' AND contract_reward_transaction_id IS NOT NULL AND referrer_confirmation_status='APPROVED'`).bind(caregiverId).first<{total:number}>();return Number(row?.total||0)}catch{return 0}}

export async function applyPointBenefitsToFinancialPayload(env:Env,payload:any,caregiverId:string){await ensureJobAdsSchema(env);const [points,completedReferrals]=await Promise.all([contractPointsSummary(env,caregiverId),referralCompletedCount(env,caregiverId)]);const data=payload?.data;if(!data||typeof data!=="object")return payload;const referral=referralLoan(completedReferrals),pointLoans=RULES.map(rule=>pointLoan(points.totalPoints,rule)),loans=[referral,...pointLoans];const maxProgress=Math.min(100,Math.round(points.totalPoints/600*1000)/10);data.loans=loans;data.contractPoints=points;data.benefitRules={...(data.benefitRules||{}),eligibilityModel:"CONTRACT_POINTS_AND_REFERRALS_V2",loanThresholds:RULES.map(x=>({key:x.key,targetPoints:x.targetPoints,amountToman:x.amountToman,title:x.title})),referralLoan:{...REFERRAL_LOAN,eligibilityRule:"10_COMPLETED_REFERRALS"}};data.service={...(data.service||{}),credit:{eligibilityModel:"CONTRACT_POINTS_AND_REFERRALS_V2",eligible:points.totalPoints>=200||referral.eligible,status:points.totalPoints>=200||referral.eligible?"ELIGIBLE":"IN_PROGRESS",currentPoints:points.totalPoints,nextThreshold:points.nextThreshold,remainingToNext:points.remainingToNext,maxThreshold:600,progressPercent:Math.max(maxProgress,referral.progressPercent),referralLoanEligible:referral.eligible,completedReferrals}};const referrals=data.referrals&&typeof data.referrals==="object"?data.referrals:(data.referrals={});const summary=referrals.summary&&typeof referrals.summary==="object"?referrals.summary:(referrals.summary={});Object.assign(summary,{completedReferrals,progressInCycle:Math.min(REFERRAL_LOAN.targetReferrals,completedReferrals),remainingToMilestone:Math.max(0,REFERRAL_LOAN.targetReferrals-completedReferrals),nextMilestoneTarget:REFERRAL_LOAN.targetReferrals,milestoneSize:REFERRAL_LOAN.targetReferrals,milestoneRewardToman:0,milestoneRewardsCount:0,nextMilestoneRewardToman:0,loanEligible:referral.eligible,loanEligibilityAmountToman:REFERRAL_LOAN.amountToman,remainingToLoan:referral.remainingReferrals});data.dataUnity={...(data.dataUnity||{}),benefitsSource:"caregiver_contract_point_ledger+caregiver_referral_cases",contractPointsSource:"caregiver_contract_point_ledger",referralLoanSource:"caregiver_referral_cases",pointsPolicyVersion:"2.0.0"};return payload}

export async function rewriteFinancialResponseWithPoints(request:Request,env:Env,response:Response){if(!response.ok)return response;const url=new URL(request.url);let caregiverId="";if(url.pathname==="/api/caregiver/platform/financial-profile"){const actor=await getUser(request,env);caregiverId=actor?.role?.toUpperCase()==="CAREGIVER"?String(actor.caregiverId||""):""}else{const match=url.pathname.match(/^\/api\/staff\/financial-credits\/caregivers\/([^/]+)\/profile$/);if(match)caregiverId=decodeURIComponent(match[1])}if(!caregiverId)return response;const payload:any=await response.clone().json().catch(()=>null);if(!payload)return response;await applyPointBenefitsToFinancialPayload(env,payload,caregiverId);const headers=new Headers(response.headers);headers.delete("content-length");headers.set("cache-control","private, no-store");return new Response(JSON.stringify(payload),{status:response.status,statusText:response.statusText,headers})}
