import {type Env} from "./lib";
import {contractPointsSummary,ensureJobAdsSchema} from "./job-ads-v1";

const RULES=[
 {key:"POINT_LOAN_200",title:"وام ۱۰ میلیون تومانی",amountToman:10_000_000,targetPoints:200},
 {key:"POINT_LOAN_400",title:"وام ۲۰ میلیون تومانی",amountToman:20_000_000,targetPoints:400},
 {key:"POINT_LOAN_600",title:"وام ۵۰ میلیون تومانی",amountToman:50_000_000,targetPoints:600},
] as const;

function pointLoan(totalPoints:number,rule:(typeof RULES)[number]){const eligible=totalPoints>=rule.targetPoints;const progressPercent=Math.min(100,Math.round(totalPoints/rule.targetPoints*1000)/10);return {...rule,type:"LOAN",eligible,status:eligible?"ELIGIBLE":"IN_PROGRESS",progressPercent,currentPoints:totalPoints,remainingPoints:Math.max(0,rule.targetPoints-totalPoints),scoreThreshold:rule.targetPoints,serviceMode:"POINTS",targetMonths:0,targetDays:rule.targetPoints,serviceDays:totalPoints,serviceDuration:{months:0,days:totalPoints},remainingDays:Math.max(0,rule.targetPoints-totalPoints),projectedEligibilityDate:null,evaluation:{count:0,averageScore:null,minimumScore:null,latestScore:null,metric:totalPoints,metricMode:"CONTRACT_POINTS",threshold:rule.targetPoints,comparison:"GTE",passed:eligible,windowStart:null,windowEnd:null}}}

export async function applyPointBenefitsToFinancialPayload(env:Env,payload:any,caregiverId:string){await ensureJobAdsSchema(env);const points=await contractPointsSummary(env,caregiverId);const data=payload?.data;if(!data||typeof data!=="object")return payload;const loans=RULES.map(rule=>pointLoan(points.totalPoints,rule));const maxProgress=Math.min(100,Math.round(points.totalPoints/600*1000)/10);data.loans=loans;data.contractPoints=points;data.benefitRules={...(data.benefitRules||{}),eligibilityModel:"CONTRACT_POINTS_V1",loanThresholds:RULES.map(x=>({key:x.key,targetPoints:x.targetPoints,amountToman:x.amountToman,title:x.title}))};data.service={...(data.service||{}),credit:{eligibilityModel:"CONTRACT_POINTS_V1",eligible:points.totalPoints>=200,status:points.totalPoints>=200?"ELIGIBLE":"IN_PROGRESS",currentPoints:points.totalPoints,nextThreshold:points.nextThreshold,remainingToNext:points.remainingToNext,maxThreshold:600,progressPercent:maxProgress}};data.dataUnity={...(data.dataUnity||{}),benefitsSource:"caregiver_contract_point_ledger",contractPointsSource:"caregiver_contract_point_ledger",pointsPolicyVersion:"1.0.0"};return payload}

export async function rewriteFinancialResponseWithPoints(request:Request,env:Env,response:Response){if(!response.ok)return response;const url=new URL(request.url);let caregiverId="";if(url.pathname==="/api/caregiver/platform/financial-profile"){try{const authUrl=new URL(request.url);authUrl.pathname="/api/caregiver/contract-points";authUrl.search="";const actorResponse=await fetch(authUrl.toString(),{headers:request.headers});void actorResponse}catch{}return response}const match=url.pathname.match(/^\/api\/staff\/financial-credits\/caregivers\/([^/]+)\/profile$/);if(match)caregiverId=decodeURIComponent(match[1]);if(!caregiverId)return response;const payload:any=await response.clone().json().catch(()=>null);if(!payload)return response;await applyPointBenefitsToFinancialPayload(env,payload,caregiverId);const headers=new Headers(response.headers);headers.delete("content-length");headers.set("cache-control","private, no-store");return new Response(JSON.stringify(payload),{status:response.status,headers})}
