import {requireAccess} from "./access-control";
import {ensureReferralRewardsSchema,routeReferralRewardsV1} from "./referral-rewards-v1";
import {routeReferralRewardsV2} from "./referral-rewards-v2";
import {type AuthUser,type Env,audit,ensureSchema,fail,getUser,json,normalizeMobile,nowIso,randomId,readBody,securityHeaders,str} from "./lib";

const REGISTRATION_REWARD_TOMAN=200_000;
const CONTRACT_REWARD_TOMAN=300_000;
const REFERRAL_LOAN_TOMAN=5_000_000;
const REFERRAL_LOAN_TARGET=10;
const STAFF_FINANCE_MODULE="staff.financial_credits";

type JsonRecord=Record<string,unknown>;
const upper=(v:unknown)=>str(v).toUpperCase();

function randomSixDigitCode(){const value=crypto.getRandomValues(new Uint32Array(1))[0];return String(100_000+(value%900_000))}
async function ensureReferralCode(env:Env,caregiverId:string){const existing=await env.DB.prepare("SELECT referral_code AS referralCode FROM caregiver_referral_codes WHERE caregiver_id=? LIMIT 1").bind(caregiverId).first<{referralCode:string}>();if(existing?.referralCode)return existing.referralCode;const ts=nowIso();for(let i=0;i<40;i+=1){const code=randomSixDigitCode();await env.DB.prepare("INSERT OR IGNORE INTO caregiver_referral_codes(caregiver_id,referral_code,created_at) VALUES(?,?,?)").bind(caregiverId,code,ts).run();const row=await env.DB.prepare("SELECT referral_code AS referralCode FROM caregiver_referral_codes WHERE caregiver_id=? LIMIT 1").bind(caregiverId).first<{referralCode:string}>();if(row?.referralCode)return row.referralCode}throw new Error("referral_code_exhausted")}
async function resolveReferrer(env:Env,referralCode:string,registeringMobile:string){if(!referralCode)return null;if(!/^\d{6}$/.test(referralCode))throw new Error("invalid_referral_code");const row=await env.DB.prepare(`SELECT c.id,c.full_name AS fullName,c.mobile,rc.referral_code AS referralCode
 FROM caregiver_referral_codes rc JOIN caregivers c ON c.id=rc.caregiver_id
 LEFT JOIN users u ON u.caregiver_id=c.id AND upper(u.role)='CAREGIVER' AND upper(u.status)<>'DELETED'
 WHERE rc.referral_code=? AND c.active=1 AND (u.id IS NULL OR upper(u.status) IN ('ACTIVE','APPROVED')) LIMIT 1`).bind(referralCode).first<{id:string;fullName:string;mobile:string|null;referralCode:string}>();if(!row)throw new Error("invalid_referral_code");if(normalizeMobile(row.mobile)===registeringMobile)throw new Error("self_referral_not_allowed");return row}

async function registerProfileOnlyWithReferral(request:Request,env:Env){await Promise.all([ensureSchema(env),ensureReferralRewardsSchema(env)]);const body=await readBody(request);if(!body)return fail("اطلاعات ثبت‌نام معتبر نیست.");const fullName=str(body.fullName||body.name),mobile=normalizeMobile(str(body.mobile)),nationalId=str(body.nationalId).replace(/\D/g,"")||null,referralCode=str(body.referralCode||body.referrerCode).replace(/\D/g,"");if(fullName.length<3)return fail("نام و نام خانوادگی را کامل وارد کنید.");if(!mobile||!/^09\d{9}$/.test(mobile))return fail("شماره همراه معتبر نیست.");if(nationalId&&!/^\d{10}$/.test(nationalId))return fail("کد ملی باید ۱۰ رقم باشد.");if(referralCode&&!/^\d{6}$/.test(referralCode))return fail("کد معرف باید دقیقاً ۶ رقم باشد.",400,"invalid_referral_code_format");const duplicate=await env.DB.prepare(`SELECT id FROM caregivers WHERE mobile=? OR (national_id=? AND ? IS NOT NULL)
 UNION ALL SELECT id FROM users WHERE mobile=? AND upper(status)<>'DELETED' LIMIT 1`).bind(mobile,nationalId,nationalId,mobile).first();if(duplicate)return fail("برای این شماره همراه یا کد ملی قبلاً پرونده ثبت شده است.",409,"duplicate_registration");let referrer:Awaited<ReturnType<typeof resolveReferrer>>=null;try{referrer=await resolveReferrer(env,referralCode,mobile)}catch(error){const code=error instanceof Error?error.message:"invalid_referral_code";if(code==="self_referral_not_allowed")return fail("استفاده از کد معرف متعلق به شماره همراه خودتان مجاز نیست.",409,code);return fail("کد معرف معتبر نیست یا حساب معرف فعال نیست.",409,"invalid_referral_code")}
 const caregiverId=`CP-${Date.now().toString(36).toUpperCase()}${Math.random().toString(36).slice(2,5).toUpperCase()}`,requestCode=randomId("req_"),ts=nowIso(),skills=str(body.skills).split(/[,،]/).map(x=>x.trim()).filter(Boolean);const statements=[env.DB.prepare(`INSERT INTO caregivers(id,crm_record_id,membership_code,national_id,full_name,mobile,city,service_region,cooperation_status,active,birth_date,primary_type,skills_json,work_history,recruitment_stage,professional_level,profile_completed,last_synced_at,created_at,updated_at)
 VALUES(?,?,?,?,?,?,?,?,?,0,?,?,?,?, 'SELF_REGISTERED','NEW',1,?,?,?)`).bind(caregiverId,`SELF-PROFILE-${requestCode}`,caregiverId,nationalId,fullName,mobile,str(body.city)||null,str(body.address)||null,"در انتظار تأیید مدیر",str(body.birthDate)||null,str(body.serviceGroup)||null,JSON.stringify(skills),str(body.bio)||null,ts,ts,ts)];let referralCaseId:string|null=null;if(referrer){referralCaseId=randomId("ref_");statements.push(env.DB.prepare(`INSERT INTO caregiver_referral_cases(id,referrer_caregiver_id,referred_caregiver_id,referral_code,registration_reward_toman,contract_reward_toman,status,referrer_confirmation_status,created_at,updated_at)
 VALUES(?,?,?,?,?,?,'PENDING_REGISTRATION_REVIEW','PENDING',?,?)`).bind(referralCaseId,referrer.id,caregiverId,referrer.referralCode,REGISTRATION_REWARD_TOMAN,CONTRACT_REWARD_TOMAN,ts,ts))}await env.DB.batch(statements);const ownReferralCode=await ensureReferralCode(env,caregiverId);await audit(request,env,null,"SELF_REGISTER_PROFILE","caregiver",caregiverId,{fullName,mobile,requestCode,accountCreated:false,referralCaseId,referralCode:referrer?.referralCode||null});if(referralCaseId&&referrer)await audit(request,env,null,"CREATE_REFERRAL_CASE_WAITING_REFERRER","caregiver_referral_case",referralCaseId,{referrerCaregiverId:referrer.id,referredCaregiverId:caregiverId,registrationRewardToman:REGISTRATION_REWARD_TOMAN,contractRewardToman:CONTRACT_REWARD_TOMAN});return json({data:{requestCode,caregiverId,membershipCode:caregiverId,referralCode:ownReferralCode,status:"PENDING",accountCreated:false,referral:referralCaseId?{caseId:referralCaseId,status:"WAITING_REFERRER_CONFIRMATION",referralCode:referrer?.referralCode}:null}},201)}

async function caregiverSummary(env:Env,actor:AuthUser){if(upper(actor.role)!=="CAREGIVER"||!actor.caregiverId)return fail("این مسیر فقط برای حساب مراقب فعال است.",403,"caregiver_only");await ensureReferralRewardsSchema(env);const referralCode=await ensureReferralCode(env,actor.caregiverId);const caregiver=await env.DB.prepare("SELECT id,membership_code AS membershipCode,full_name AS fullName FROM caregivers WHERE id=? LIMIT 1").bind(actor.caregiverId).first<JsonRecord>();if(!caregiver)return fail("پرونده مراقب پیدا نشد.",404,"caregiver_not_found");const result=await env.DB.prepare(`SELECT r.id,r.referred_caregiver_id AS referredCaregiverId,c.membership_code AS referredMembershipCode,c.full_name AS referredName,
 r.status,r.referrer_confirmation_status AS referrerConfirmationStatus,r.referrer_confirmed_at AS referrerConfirmedAt,r.referrer_rejected_at AS referrerRejectedAt,r.referrer_decision_note AS referrerDecisionNote,
 r.registration_reward_toman AS registrationRewardToman,r.contract_reward_toman AS contractRewardToman,r.registration_reward_transaction_id AS registrationRewardTransactionId,r.contract_reward_transaction_id AS contractRewardTransactionId,
 r.registration_reviewed_at AS registrationReviewedAt,r.contract_reviewed_at AS contractReviewedAt,r.registration_decision_note AS registrationDecisionNote,r.contract_decision_note AS contractDecisionNote,r.created_at AS createdAt,r.updated_at AS updatedAt
 FROM caregiver_referral_cases r JOIN caregivers c ON c.id=r.referred_caregiver_id WHERE r.referrer_caregiver_id=? ORDER BY r.created_at DESC LIMIT 300`).bind(actor.caregiverId).all<JsonRecord>();const rows=(result.results||[]).map(row=>({...row,effectiveStatus:upper(row.referrerConfirmationStatus)==="PENDING"?"WAITING_REFERRER_CONFIRMATION":upper(row.referrerConfirmationStatus)==="REJECTED"?"REFERRER_REJECTED":String(row.status||"")}));let confirmedRewardToman=0,pendingRewardToman=0,completedReferrals=0,awaitingMyConfirmation=0;for(const item of rows){if(item.registrationRewardTransactionId)confirmedRewardToman+=REGISTRATION_REWARD_TOMAN;if(item.contractRewardTransactionId){confirmedRewardToman+=CONTRACT_REWARD_TOMAN;completedReferrals+=1}if(item.effectiveStatus==="WAITING_REFERRER_CONFIRMATION"){awaitingMyConfirmation+=1;pendingRewardToman+=REGISTRATION_REWARD_TOMAN}else if(item.effectiveStatus==="WAITING_CONTRACT")pendingRewardToman+=CONTRACT_REWARD_TOMAN}const loanEligible=completedReferrals>=REFERRAL_LOAN_TARGET,progressInCycle=Math.min(REFERRAL_LOAN_TARGET,completedReferrals),remainingToLoan=Math.max(0,REFERRAL_LOAN_TARGET-completedReferrals);return json({data:{caregiver:{...caregiver,referralCode},summary:{totalReferrals:rows.length,completedReferrals,confirmedRewardToman,pendingRewardToman,awaitingMyConfirmation,milestoneRewardToman:0,milestoneRewardsCount:0,progressInCycle,remainingToMilestone:remainingToLoan,nextMilestoneTarget:REFERRAL_LOAN_TARGET,milestoneSize:REFERRAL_LOAN_TARGET,nextMilestoneRewardToman:0,loanEligible,loanEligibilityAmountToman:REFERRAL_LOAN_TOMAN,remainingToLoan},cases:rows,milestones:[],policy:{registrationRewardToman:REGISTRATION_REWARD_TOMAN,contractRewardToman:CONTRACT_REWARD_TOMAN,referralLoanTarget:REFERRAL_LOAN_TARGET,referralLoanAmountToman:REFERRAL_LOAN_TOMAN}}})}

async function caregiverDecision(request:Request,env:Env,actor:AuthUser,id:string){if(upper(actor.role)!=="CAREGIVER"||!actor.caregiverId)return fail("این مسیر فقط برای حساب مراقب فعال است.",403,"caregiver_only");const body=await readBody(request);if(!body)return fail("اطلاعات تصمیم معتبر نیست.");const action=upper(body.action);if(!["CONFIRM","REJECT"].includes(action))return fail("اقدام انتخاب‌شده معتبر نیست.");const current=await env.DB.prepare(`SELECT id,referrer_caregiver_id AS referrerCaregiverId,referred_caregiver_id AS referredCaregiverId,status,referrer_confirmation_status AS referrerConfirmationStatus,registration_reward_transaction_id AS registrationRewardTransactionId FROM caregiver_referral_cases WHERE id=? LIMIT 1`).bind(id).first<any>();if(!current||current.referrerCaregiverId!==actor.caregiverId)return fail("درخواست معرفی برای حساب شما پیدا نشد.",404,"referral_case_not_found");if(current.referrerConfirmationStatus!=="PENDING"){if(current.referrerConfirmationStatus==="APPROVED"&&current.registrationRewardTransactionId)return json({data:{id,referrerConfirmationStatus:"APPROVED",status:current.status,transactionId:current.registrationRewardTransactionId,amountToman:REGISTRATION_REWARD_TOMAN}});return fail("تصمیم شما برای این معرفی قبلاً ثبت شده است.",409,"referrer_already_decided")}
 const note=str(body.note)||null,ts=nowIso();if(action==="REJECT"){await env.DB.prepare(`UPDATE caregiver_referral_cases SET referrer_confirmation_status='REJECTED',referrer_rejected_at=?,referrer_decision_note=?,status='REGISTRATION_REJECTED',updated_at=? WHERE id=? AND referrer_caregiver_id=? AND referrer_confirmation_status='PENDING'`).bind(ts,note,ts,id,actor.caregiverId).run();await audit(request,env,actor,"REJECT_REFERRAL_OWNERSHIP","caregiver_referral_case",id,{referredCaregiverId:current.referredCaregiverId,note});return json({data:{id,referrerConfirmationStatus:"REJECTED",status:"REFERRER_REJECTED"}})}const transactionId=randomId("wtx_");try{await env.DB.batch([env.DB.prepare(`INSERT INTO caregiver_wallet_transactions(id,caregiver_id,direction,transaction_type,amount_toman,title,description,reference_type,reference_id,created_by_user_id,created_at)
 VALUES(?,?,'CREDIT','REFERRAL_REGISTRATION_REWARD',?,?,?,'REFERRAL_STAGE1',?,?,?)`).bind(transactionId,actor.caregiverId,REGISTRATION_REWARD_TOMAN,"پاداش تأیید معرفی مراقب","پاداش مرحله اول پس از تأیید استفاده از کد معرف",id,actor.id,ts),env.DB.prepare(`UPDATE caregiver_referral_cases SET referrer_confirmation_status='APPROVED',referrer_confirmed_at=?,referrer_rejected_at=NULL,referrer_decision_note=?,status='WAITING_CONTRACT',registration_reward_transaction_id=?,registration_reviewed_by_user_id=?,registration_reviewed_at=?,registration_decision_note=?,updated_at=? WHERE id=? AND referrer_caregiver_id=? AND referrer_confirmation_status='PENDING'`).bind(ts,note,transactionId,actor.id,ts,"تأیید مستقیم توسط مراقب معرف",ts,id,actor.caregiverId)])}catch(error){const detail=error instanceof Error?error.message:"database_error";if(/UNIQUE|unique/i.test(detail))return fail("پاداش مرحله اول قبلاً ثبت شده است.",409,"duplicate_registration_reward");throw error}await audit(request,env,actor,"CONFIRM_REFERRAL_AND_AWARD_REGISTRATION","caregiver_referral_case",id,{referredCaregiverId:current.referredCaregiverId,amountToman:REGISTRATION_REWARD_TOMAN,transactionId,nextStatus:"WAITING_CONTRACT"});return json({data:{id,referrerConfirmationStatus:"APPROVED",status:"WAITING_CONTRACT",transactionId,amountToman:REGISTRATION_REWARD_TOMAN}})}

async function contractEvidence(env:Env,caregiverId:string){let jobApplication=false,operationalContract=false;try{jobApplication=Boolean(await env.DB.prepare("SELECT id FROM care_job_applications WHERE caregiver_id=? AND status='IN_CONTRACT' LIMIT 1").bind(caregiverId).first())}catch{}try{operationalContract=Boolean(await env.DB.prepare("SELECT id FROM contracts WHERE caregiver_id=? AND status IN ('ACTIVE','COMPLETED') AND deleted_at IS NULL LIMIT 1").bind(caregiverId).first())}catch{}return {eligible:jobApplication||operationalContract,jobApplication,operationalContract}}
async function staffDecision(request:Request,env:Env,actor:AuthUser,id:string){const denied=await requireAccess(env,actor,STAFF_FINANCE_MODULE,"update");if(denied)return denied;const body=await readBody(request.clone()),action=upper(body?.action);const current=await env.DB.prepare("SELECT referrer_confirmation_status AS confirmation,referred_caregiver_id AS referredCaregiverId FROM caregiver_referral_cases WHERE id=? LIMIT 1").bind(id).first<{confirmation:string;referredCaregiverId:string}>();if(!current)return fail("پرونده معرفی پیدا نشد.",404,"referral_case_not_found");if(upper(current.confirmation)!=="APPROVED")return fail("ابتدا مراقب معرف باید استفاده از کد معرف خود را تأیید کند.",409,"referrer_confirmation_required");if(action==="APPROVE_CONTRACT"){const evidence=await contractEvidence(env,current.referredCaregiverId);if(!evidence.eligible)return fail("برای مراقب معرفی‌شده هنوز ورود به قرارداد در سامانه ثبت نشده است.",409,"referred_contract_not_found");await audit(request,env,actor,"VERIFY_REFERRAL_CONTRACT_EVIDENCE","caregiver_referral_case",id,evidence)}const response=await routeReferralRewardsV1(request,env);return response||fail("مسیر تصمیم معرفی پیدا نشد.",404,"not_found")}

export async function routeReferralRewardsV3(request:Request,env:Env):Promise<Response|null>{const url=new URL(request.url),path=url.pathname,method=request.method.toUpperCase();if(path==="/api/public/caregivers/register"&&method==="POST")return securityHeaders(await registerProfileOnlyWithReferral(request,env));if(path==="/api/caregiver/platform/referrals"&&method==="GET"){const actor=await getUser(request,env);if(!actor)return securityHeaders(fail("ابتدا وارد حساب شوید.",401,"unauthorized"));return securityHeaders(await caregiverSummary(env,actor))}const caregiverMatch=path.match(/^\/api\/caregiver\/platform\/referrals\/([^/]+)$/);if(caregiverMatch&&method==="PATCH"){const actor=await getUser(request,env);if(!actor)return securityHeaders(fail("ابتدا وارد حساب شوید.",401,"unauthorized"));return securityHeaders(await caregiverDecision(request,env,actor,decodeURIComponent(caregiverMatch[1])))}if(path==="/api/staff/financial-credits/referrals"&&method==="GET")return routeReferralRewardsV2(request,env);const staffMatch=path.match(/^\/api\/staff\/financial-credits\/referrals\/([^/]+)$/);if(staffMatch&&method==="PATCH"){const actor=await getUser(request,env);if(!actor)return securityHeaders(fail("ابتدا وارد حساب شوید.",401,"unauthorized"));return securityHeaders(await staffDecision(request,env,actor,decodeURIComponent(staffMatch[1])))}if(path.startsWith("/api/staff/financial-credits/referrals"))return routeReferralRewardsV1(request,env);return null}
