import {requireAccess} from "./access-control";
import {type AuthUser,type Env,audit,fail,getUser,json,nowIso,randomId,readBody,securityHeaders,str} from "./lib";

const MODULE="staff.financial_credits";
const BENEFIT_KEY="REFERRAL_LOAN_10";
const AMOUNT_TOMAN=5_000_000;
const TARGET_REFERRALS=10;
const OPEN_STATUSES=new Set(["REQUESTED","UNDER_REVIEW","APPROVED"]);

async function completedReferrals(env:Env,caregiverId:string){const row=await env.DB.prepare(`SELECT COUNT(*) AS total
 FROM caregiver_referral_cases
 WHERE referrer_caregiver_id=? AND status='COMPLETED'
 AND contract_reward_transaction_id IS NOT NULL
 AND referrer_confirmation_status='APPROVED'`).bind(caregiverId).first<{total:number}>();return Number(row?.total||0)}
async function eligibility(env:Env,caregiverId:string){const completed=await completedReferrals(env,caregiverId);return {eligible:completed>=TARGET_REFERRALS,completedReferrals:completed,targetReferrals:TARGET_REFERRALS,remainingReferrals:Math.max(0,TARGET_REFERRALS-completed),amountToman:AMOUNT_TOMAN,benefitKey:BENEFIT_KEY,title:"وام ۵ میلیون تومانی معرفی موفق"}}

async function createRequest(request:Request,env:Env,actor:AuthUser,body:Record<string,unknown>){if(actor.role.toUpperCase()!=="CAREGIVER"||!actor.caregiverId)return fail("این مسیر فقط برای حساب مراقب فعال است.",403,"caregiver_only");const current=await eligibility(env,actor.caregiverId);if(!current.eligible)return fail(`هنوز ${current.remainingReferrals.toLocaleString("fa-IR")} معرفی موفقِ وارد قرارداد تا فعال‌شدن این وام باقی مانده است.`,409,"referral_loan_not_eligible");const open=await env.DB.prepare(`SELECT id,status FROM caregiver_credit_requests WHERE caregiver_id=? AND status IN ('REQUESTED','UNDER_REVIEW','APPROVED') LIMIT 1`).bind(actor.caregiverId).first<{id:string;status:string}>();if(open)return fail("برای شما یک درخواست تسهیلات باز وجود دارد.",409,"credit_request_exists");const id=randomId("crq_"),ts=nowIso(),snapshot={profileVersion:"REFERRAL_LOAN_V1",benefitKey:BENEFIT_KEY,benefitType:"LOAN",benefitTitle:current.title,amountToman:AMOUNT_TOMAN,eligibleAtRequest:true,serviceMode:"REFERRALS",completedReferrals:current.completedReferrals,targetReferrals:TARGET_REFERRALS,eligibilitySource:"caregiver_referral_cases",calculatedAt:ts};await env.DB.prepare(`INSERT INTO caregiver_credit_requests(id,caregiver_id,requested_amount_toman,eligibility_path,continuous_days,cumulative_days,eligibility_snapshot_json,note,status,requested_by_user_id,created_at,updated_at)
 VALUES(?,?,?,?,0,0,?,?,'REQUESTED',?,?,?)`).bind(id,actor.caregiverId,AMOUNT_TOMAN,BENEFIT_KEY,JSON.stringify(snapshot),str(body.note)||null,actor.id,ts,ts).run();await audit(request,env,actor,"CREATE_REFERRAL_LOAN_REQUEST","credit_request",id,snapshot);return json({data:{id,status:"REQUESTED",...snapshot,createdAt:ts}},201)}

async function decideRequest(request:Request,env:Env,actor:AuthUser,id:string,row:any){const denied=await requireAccess(env,actor,MODULE,"update");if(denied)return denied;const body=await readBody(request),decision=str(body?.status||body?.decision).toUpperCase(),reason=str(body?.reason||body?.decisionNote||body?.note);if(!["UNDER_REVIEW","APPROVED","REJECTED","CANCELLED"].includes(decision))return fail("وضعیت تصمیم معتبر نیست.");if(!reason)return fail("ثبت دلیل تصمیم الزامی است.",400,"reason_required");const currentStatus=str(row.status).toUpperCase();const valid=(decision==="UNDER_REVIEW"&&currentStatus==="REQUESTED")||(decision==="APPROVED"&&["REQUESTED","UNDER_REVIEW"].includes(currentStatus))||(decision==="REJECTED"&&["REQUESTED","UNDER_REVIEW"].includes(currentStatus))||(decision==="CANCELLED"&&OPEN_STATUSES.has(currentStatus));if(!valid)return fail("تغییر وضعیت درخواست اعتبار مجاز نیست.",409,"invalid_transition");let verified:any=null;if(decision==="APPROVED"){verified=await eligibility(env,String(row.caregiverId));if(!verified.eligible)return fail("شرط ۱۰ معرفی موفقِ وارد قرارداد در زمان تأیید دیگر احراز نمی‌شود.",409,"referral_loan_not_eligible")}const ts=nowIso();await env.DB.prepare(`UPDATE caregiver_credit_requests SET status=?,reviewed_by_user_id=?,reviewed_at=?,decision_note=?,updated_at=? WHERE id=?`).bind(decision,actor.id,ts,reason,ts,id).run();await audit(request,env,actor,`REFERRAL_LOAN_REQUEST_${decision}`,"credit_request",id,{caregiverId:row.caregiverId,previousStatus:currentStatus,reason,eligibility:verified});return json({data:{id,status:decision,reason,eligibility:verified,updatedAt:ts}})}

export async function routeReferralLoanCreditV1(request:Request,env:Env):Promise<Response|null>{const url=new URL(request.url),path=url.pathname,method=request.method.toUpperCase();if(path==="/api/caregiver/platform/credit-requests"&&method==="POST"){const body=await readBody(request.clone())||{};const key=str(body.benefitKey||body.tierKey);if(key!==BENEFIT_KEY)return null;const actor=await getUser(request,env);if(!actor)return securityHeaders(fail("ابتدا وارد حساب شوید.",401,"unauthorized"));return securityHeaders(await createRequest(request,env,actor,body))}const match=path.match(/^\/api\/staff\/financial-credits\/credit-requests\/([^/]+)$/);if(match&&method==="PATCH"){const id=decodeURIComponent(match[1]);const row=await env.DB.prepare(`SELECT id,caregiver_id AS caregiverId,eligibility_path AS eligibilityPath,status FROM caregiver_credit_requests WHERE id=? LIMIT 1`).bind(id).first<any>();if(!row||str(row.eligibilityPath)!==BENEFIT_KEY)return null;const actor=await getUser(request,env);if(!actor)return securityHeaders(fail("ابتدا وارد حساب شوید.",401,"unauthorized"));return securityHeaders(await decideRequest(request,env,actor,id,row))}return null}
